RestClients:
  #GitHub's v3 REST API.
  github (GitHub v3 REST API):
    UUID: 4895b78f-4d15-49f6-9754-de015d91d52e
    Url: '{ivy.app.baseurl}/api/githubMock'
    Icon: res:/webContent/icons/GitHub-Mark-64px.png
    Features:
    - ch.ivyteam.ivy.rest.client.mapper.JsonFeature
    OpenAPI:
      SpecUrl: https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.json
      Namespace: com.github.api.client
