/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.github.api.client.ActionsEnabled;
import com.github.api.client.AllowedActions;

/**
 * ActionsPermissionsBody2
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class ActionsPermissionsBody2 {
  @JsonProperty("enabled")
  private ActionsEnabled enabled = null;

  @JsonProperty("allowed_actions")
  private AllowedActions allowedActions = null;

  public ActionsPermissionsBody2 enabled(ActionsEnabled enabled) {
    this.enabled = enabled;
    return this;
  }

   /**
   * Get enabled
   * @return enabled
  **/
  public ActionsEnabled getEnabled() {
    return enabled;
  }

  public void setEnabled(ActionsEnabled enabled) {
    this.enabled = enabled;
  }

  public ActionsPermissionsBody2 allowedActions(AllowedActions allowedActions) {
    this.allowedActions = allowedActions;
    return this;
  }

   /**
   * Get allowedActions
   * @return allowedActions
  **/
  public AllowedActions getAllowedActions() {
    return allowedActions;
  }

  public void setAllowedActions(AllowedActions allowedActions) {
    this.allowedActions = allowedActions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActionsPermissionsBody2 actionsPermissionsBody2 = (ActionsPermissionsBody2) o;
    return Objects.equals(this.enabled, actionsPermissionsBody2.enabled) &&
        Objects.equals(this.allowedActions, actionsPermissionsBody2.allowedActions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enabled, allowedActions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActionsPermissionsBody2 {\n");
    
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    allowedActions: ").append(toIndentedString(allowedActions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
