/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Repository actions caches
 */
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class ActionsCacheList {
  @JsonProperty("total_count")
  private Object totalCount = null;

  @JsonProperty("actions_caches")
  private Object actionsCaches = null;

  public ActionsCacheList totalCount(Object totalCount) {
    this.totalCount = totalCount;
    return this;
  }

   /**
   * Total number of caches
   * @return totalCount
  **/
  public Object getTotalCount() {
    return totalCount;
  }

  public void setTotalCount(Object totalCount) {
    this.totalCount = totalCount;
  }

  public ActionsCacheList actionsCaches(Object actionsCaches) {
    this.actionsCaches = actionsCaches;
    return this;
  }

   /**
   * Array of caches
   * @return actionsCaches
  **/
  public Object getActionsCaches() {
    return actionsCaches;
  }

  public void setActionsCaches(Object actionsCaches) {
    this.actionsCaches = actionsCaches;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActionsCacheList actionsCacheList = (ActionsCacheList) o;
    return Objects.equals(this.totalCount, actionsCacheList.totalCount) &&
        Objects.equals(this.actionsCaches, actionsCacheList.actionsCaches);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalCount, actionsCaches);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActionsCacheList {\n");
    
    sb.append("    totalCount: ").append(toIndentedString(totalCount)).append("\n");
    sb.append("    actionsCaches: ").append(toIndentedString(actionsCaches)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
