/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * GitHub Actions Cache Usage by repository.
 */
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class ActionsCacheUsageByRepository {
  @JsonProperty("full_name")
  private Object fullName = null;

  @JsonProperty("active_caches_size_in_bytes")
  private Object activeCachesSizeInBytes = null;

  @JsonProperty("active_caches_count")
  private Object activeCachesCount = null;

  public ActionsCacheUsageByRepository fullName(Object fullName) {
    this.fullName = fullName;
    return this;
  }

   /**
   * The repository owner and name for the cache usage being shown.
   * @return fullName
  **/
  public Object getFullName() {
    return fullName;
  }

  public void setFullName(Object fullName) {
    this.fullName = fullName;
  }

  public ActionsCacheUsageByRepository activeCachesSizeInBytes(Object activeCachesSizeInBytes) {
    this.activeCachesSizeInBytes = activeCachesSizeInBytes;
    return this;
  }

   /**
   * The sum of the size in bytes of all the active cache items in the repository.
   * @return activeCachesSizeInBytes
  **/
  public Object getActiveCachesSizeInBytes() {
    return activeCachesSizeInBytes;
  }

  public void setActiveCachesSizeInBytes(Object activeCachesSizeInBytes) {
    this.activeCachesSizeInBytes = activeCachesSizeInBytes;
  }

  public ActionsCacheUsageByRepository activeCachesCount(Object activeCachesCount) {
    this.activeCachesCount = activeCachesCount;
    return this;
  }

   /**
   * The number of active caches in the repository.
   * @return activeCachesCount
  **/
  public Object getActiveCachesCount() {
    return activeCachesCount;
  }

  public void setActiveCachesCount(Object activeCachesCount) {
    this.activeCachesCount = activeCachesCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActionsCacheUsageByRepository actionsCacheUsageByRepository = (ActionsCacheUsageByRepository) o;
    return Objects.equals(this.fullName, actionsCacheUsageByRepository.fullName) &&
        Objects.equals(this.activeCachesSizeInBytes, actionsCacheUsageByRepository.activeCachesSizeInBytes) &&
        Objects.equals(this.activeCachesCount, actionsCacheUsageByRepository.activeCachesCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fullName, activeCachesSizeInBytes, activeCachesCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActionsCacheUsageByRepository {\n");
    
    sb.append("    fullName: ").append(toIndentedString(fullName)).append("\n");
    sb.append("    activeCachesSizeInBytes: ").append(toIndentedString(activeCachesSizeInBytes)).append("\n");
    sb.append("    activeCachesCount: ").append(toIndentedString(activeCachesCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
