/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.github.api.client.ActionsbillingusageMinutesUsedBreakdown;

/**
 * ActionsBillingUsage
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class ActionsBillingUsage {
  @JsonProperty("total_minutes_used")
  private Object totalMinutesUsed = null;

  @JsonProperty("total_paid_minutes_used")
  private Object totalPaidMinutesUsed = null;

  @JsonProperty("included_minutes")
  private Object includedMinutes = null;

  @JsonProperty("minutes_used_breakdown")
  private ActionsbillingusageMinutesUsedBreakdown minutesUsedBreakdown = null;

  public ActionsBillingUsage totalMinutesUsed(Object totalMinutesUsed) {
    this.totalMinutesUsed = totalMinutesUsed;
    return this;
  }

   /**
   * The sum of the free and paid GitHub Actions minutes used.
   * @return totalMinutesUsed
  **/
  public Object getTotalMinutesUsed() {
    return totalMinutesUsed;
  }

  public void setTotalMinutesUsed(Object totalMinutesUsed) {
    this.totalMinutesUsed = totalMinutesUsed;
  }

  public ActionsBillingUsage totalPaidMinutesUsed(Object totalPaidMinutesUsed) {
    this.totalPaidMinutesUsed = totalPaidMinutesUsed;
    return this;
  }

   /**
   * The total paid GitHub Actions minutes used.
   * @return totalPaidMinutesUsed
  **/
  public Object getTotalPaidMinutesUsed() {
    return totalPaidMinutesUsed;
  }

  public void setTotalPaidMinutesUsed(Object totalPaidMinutesUsed) {
    this.totalPaidMinutesUsed = totalPaidMinutesUsed;
  }

  public ActionsBillingUsage includedMinutes(Object includedMinutes) {
    this.includedMinutes = includedMinutes;
    return this;
  }

   /**
   * The amount of free GitHub Actions minutes available.
   * @return includedMinutes
  **/
  public Object getIncludedMinutes() {
    return includedMinutes;
  }

  public void setIncludedMinutes(Object includedMinutes) {
    this.includedMinutes = includedMinutes;
  }

  public ActionsBillingUsage minutesUsedBreakdown(ActionsbillingusageMinutesUsedBreakdown minutesUsedBreakdown) {
    this.minutesUsedBreakdown = minutesUsedBreakdown;
    return this;
  }

   /**
   * Get minutesUsedBreakdown
   * @return minutesUsedBreakdown
  **/
  public ActionsbillingusageMinutesUsedBreakdown getMinutesUsedBreakdown() {
    return minutesUsedBreakdown;
  }

  public void setMinutesUsedBreakdown(ActionsbillingusageMinutesUsedBreakdown minutesUsedBreakdown) {
    this.minutesUsedBreakdown = minutesUsedBreakdown;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActionsBillingUsage actionsBillingUsage = (ActionsBillingUsage) o;
    return Objects.equals(this.totalMinutesUsed, actionsBillingUsage.totalMinutesUsed) &&
        Objects.equals(this.totalPaidMinutesUsed, actionsBillingUsage.totalPaidMinutesUsed) &&
        Objects.equals(this.includedMinutes, actionsBillingUsage.includedMinutes) &&
        Objects.equals(this.minutesUsedBreakdown, actionsBillingUsage.minutesUsedBreakdown);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalMinutesUsed, totalPaidMinutesUsed, includedMinutes, minutesUsedBreakdown);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActionsBillingUsage {\n");
    
    sb.append("    totalMinutesUsed: ").append(toIndentedString(totalMinutesUsed)).append("\n");
    sb.append("    totalPaidMinutesUsed: ").append(toIndentedString(totalPaidMinutesUsed)).append("\n");
    sb.append("    includedMinutes: ").append(toIndentedString(includedMinutes)).append("\n");
    sb.append("    minutesUsedBreakdown: ").append(toIndentedString(minutesUsedBreakdown)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
