/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.github.api.client.BranchProtection;
import com.github.api.client.BranchwithprotectionLinks;
import com.github.api.client.Commit;

/**
 * Branch With Protection
 */
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class BranchWithProtection {
  @JsonProperty("name")
  private Object name = null;

  @JsonProperty("commit")
  private Commit commit = null;

  @JsonProperty("_links")
  private BranchwithprotectionLinks _links = null;

  @JsonProperty("protected")
  private Object _protected = null;

  @JsonProperty("protection")
  private BranchProtection protection = null;

  @JsonProperty("protection_url")
  private Object protectionUrl = null;

  @JsonProperty("pattern")
  private Object pattern = null;

  @JsonProperty("required_approving_review_count")
  private Object requiredApprovingReviewCount = null;

  public BranchWithProtection name(Object name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public Object getName() {
    return name;
  }

  public void setName(Object name) {
    this.name = name;
  }

  public BranchWithProtection commit(Commit commit) {
    this.commit = commit;
    return this;
  }

   /**
   * Get commit
   * @return commit
  **/
  public Commit getCommit() {
    return commit;
  }

  public void setCommit(Commit commit) {
    this.commit = commit;
  }

  public BranchWithProtection _links(BranchwithprotectionLinks _links) {
    this._links = _links;
    return this;
  }

   /**
   * Get _links
   * @return _links
  **/
  public BranchwithprotectionLinks getLinks() {
    return _links;
  }

  public void setLinks(BranchwithprotectionLinks _links) {
    this._links = _links;
  }

  public BranchWithProtection _protected(Object _protected) {
    this._protected = _protected;
    return this;
  }

   /**
   * Get _protected
   * @return _protected
  **/
  public Object getProtected() {
    return _protected;
  }

  public void setProtected(Object _protected) {
    this._protected = _protected;
  }

  public BranchWithProtection protection(BranchProtection protection) {
    this.protection = protection;
    return this;
  }

   /**
   * Get protection
   * @return protection
  **/
  public BranchProtection getProtection() {
    return protection;
  }

  public void setProtection(BranchProtection protection) {
    this.protection = protection;
  }

  public BranchWithProtection protectionUrl(Object protectionUrl) {
    this.protectionUrl = protectionUrl;
    return this;
  }

   /**
   * Get protectionUrl
   * @return protectionUrl
  **/
  public Object getProtectionUrl() {
    return protectionUrl;
  }

  public void setProtectionUrl(Object protectionUrl) {
    this.protectionUrl = protectionUrl;
  }

  public BranchWithProtection pattern(Object pattern) {
    this.pattern = pattern;
    return this;
  }

   /**
   * Get pattern
   * @return pattern
  **/
  public Object getPattern() {
    return pattern;
  }

  public void setPattern(Object pattern) {
    this.pattern = pattern;
  }

  public BranchWithProtection requiredApprovingReviewCount(Object requiredApprovingReviewCount) {
    this.requiredApprovingReviewCount = requiredApprovingReviewCount;
    return this;
  }

   /**
   * Get requiredApprovingReviewCount
   * @return requiredApprovingReviewCount
  **/
  public Object getRequiredApprovingReviewCount() {
    return requiredApprovingReviewCount;
  }

  public void setRequiredApprovingReviewCount(Object requiredApprovingReviewCount) {
    this.requiredApprovingReviewCount = requiredApprovingReviewCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BranchWithProtection branchWithProtection = (BranchWithProtection) o;
    return Objects.equals(this.name, branchWithProtection.name) &&
        Objects.equals(this.commit, branchWithProtection.commit) &&
        Objects.equals(this._links, branchWithProtection._links) &&
        Objects.equals(this._protected, branchWithProtection._protected) &&
        Objects.equals(this.protection, branchWithProtection.protection) &&
        Objects.equals(this.protectionUrl, branchWithProtection.protectionUrl) &&
        Objects.equals(this.pattern, branchWithProtection.pattern) &&
        Objects.equals(this.requiredApprovingReviewCount, branchWithProtection.requiredApprovingReviewCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, commit, _links, _protected, protection, protectionUrl, pattern, requiredApprovingReviewCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BranchWithProtection {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    commit: ").append(toIndentedString(commit)).append("\n");
    sb.append("    _links: ").append(toIndentedString(_links)).append("\n");
    sb.append("    _protected: ").append(toIndentedString(_protected)).append("\n");
    sb.append("    protection: ").append(toIndentedString(protection)).append("\n");
    sb.append("    protectionUrl: ").append(toIndentedString(protectionUrl)).append("\n");
    sb.append("    pattern: ").append(toIndentedString(pattern)).append("\n");
    sb.append("    requiredApprovingReviewCount: ").append(toIndentedString(requiredApprovingReviewCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
