/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * CardsCardIdBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class CardsCardIdBody {
  @JsonProperty("note")
  private Object note = null;

  @JsonProperty("archived")
  private Object archived = null;

  public CardsCardIdBody note(Object note) {
    this.note = note;
    return this;
  }

   /**
   * The project card&#x27;s note
   * @return note
  **/
  public Object getNote() {
    return note;
  }

  public void setNote(Object note) {
    this.note = note;
  }

  public CardsCardIdBody archived(Object archived) {
    this.archived = archived;
    return this;
  }

   /**
   * Whether or not the card is archived
   * @return archived
  **/
  public Object getArchived() {
    return archived;
  }

  public void setArchived(Object archived) {
    this.archived = archived;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CardsCardIdBody cardsCardIdBody = (CardsCardIdBody) o;
    return Objects.equals(this.note, cardsCardIdBody.note) &&
        Objects.equals(this.archived, cardsCardIdBody.archived);
  }

  @Override
  public int hashCode() {
    return Objects.hash(note, archived);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CardsCardIdBody {\n");
    
    sb.append("    note: ").append(toIndentedString(note)).append("\n");
    sb.append("    archived: ").append(toIndentedString(archived)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
