/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.github.api.client.CodespaceGitStatus;
import com.github.api.client.CodespaceRuntimeConstraints;
import com.github.api.client.MinimalRepository;
import com.github.api.client.SimpleUser;

/**
 * A codespace.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class Codespace {
  @JsonProperty("id")
  private Object id = null;

  @JsonProperty("name")
  private Object name = null;

  @JsonProperty("display_name")
  private Object displayName = null;

  @JsonProperty("environment_id")
  private Object environmentId = null;

  @JsonProperty("owner")
  private SimpleUser owner = null;

  @JsonProperty("billable_owner")
  private SimpleUser billableOwner = null;

  @JsonProperty("repository")
  private MinimalRepository repository = null;

  @JsonProperty("machine")
  private Object machine = null;

  @JsonProperty("devcontainer_path")
  private Object devcontainerPath = null;

  @JsonProperty("prebuild")
  private Object prebuild = null;

  @JsonProperty("created_at")
  private Object createdAt = null;

  @JsonProperty("updated_at")
  private Object updatedAt = null;

  @JsonProperty("last_used_at")
  private Object lastUsedAt = null;

  @JsonProperty("state")
  private Object state = null;

  @JsonProperty("url")
  private Object url = null;

  @JsonProperty("git_status")
  private CodespaceGitStatus gitStatus = null;

  @JsonProperty("location")
  private Object location = null;

  @JsonProperty("idle_timeout_minutes")
  private Object idleTimeoutMinutes = null;

  @JsonProperty("web_url")
  private Object webUrl = null;

  @JsonProperty("machines_url")
  private Object machinesUrl = null;

  @JsonProperty("start_url")
  private Object startUrl = null;

  @JsonProperty("stop_url")
  private Object stopUrl = null;

  @JsonProperty("pulls_url")
  private Object pullsUrl = null;

  @JsonProperty("recent_folders")
  private Object recentFolders = null;

  @JsonProperty("runtime_constraints")
  private CodespaceRuntimeConstraints runtimeConstraints = null;

  @JsonProperty("pending_operation")
  private Object pendingOperation = null;

  @JsonProperty("pending_operation_disabled_reason")
  private Object pendingOperationDisabledReason = null;

  @JsonProperty("idle_timeout_notice")
  private Object idleTimeoutNotice = null;

  @JsonProperty("retention_period_minutes")
  private Object retentionPeriodMinutes = null;

  @JsonProperty("retention_expires_at")
  private Object retentionExpiresAt = null;

  @JsonProperty("last_known_stop_notice")
  private Object lastKnownStopNotice = null;

  public Codespace id(Object id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Object getId() {
    return id;
  }

  public void setId(Object id) {
    this.id = id;
  }

  public Codespace name(Object name) {
    this.name = name;
    return this;
  }

   /**
   * Automatically generated name of this codespace.
   * @return name
  **/
  public Object getName() {
    return name;
  }

  public void setName(Object name) {
    this.name = name;
  }

  public Codespace displayName(Object displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * Display name for this codespace.
   * @return displayName
  **/
  public Object getDisplayName() {
    return displayName;
  }

  public void setDisplayName(Object displayName) {
    this.displayName = displayName;
  }

  public Codespace environmentId(Object environmentId) {
    this.environmentId = environmentId;
    return this;
  }

   /**
   * UUID identifying this codespace&#x27;s environment.
   * @return environmentId
  **/
  public Object getEnvironmentId() {
    return environmentId;
  }

  public void setEnvironmentId(Object environmentId) {
    this.environmentId = environmentId;
  }

  public Codespace owner(SimpleUser owner) {
    this.owner = owner;
    return this;
  }

   /**
   * Get owner
   * @return owner
  **/
  public SimpleUser getOwner() {
    return owner;
  }

  public void setOwner(SimpleUser owner) {
    this.owner = owner;
  }

  public Codespace billableOwner(SimpleUser billableOwner) {
    this.billableOwner = billableOwner;
    return this;
  }

   /**
   * Get billableOwner
   * @return billableOwner
  **/
  public SimpleUser getBillableOwner() {
    return billableOwner;
  }

  public void setBillableOwner(SimpleUser billableOwner) {
    this.billableOwner = billableOwner;
  }

  public Codespace repository(MinimalRepository repository) {
    this.repository = repository;
    return this;
  }

   /**
   * Get repository
   * @return repository
  **/
  public MinimalRepository getRepository() {
    return repository;
  }

  public void setRepository(MinimalRepository repository) {
    this.repository = repository;
  }

  public Codespace machine(Object machine) {
    this.machine = machine;
    return this;
  }

   /**
   * Get machine
   * @return machine
  **/
  public Object getMachine() {
    return machine;
  }

  public void setMachine(Object machine) {
    this.machine = machine;
  }

  public Codespace devcontainerPath(Object devcontainerPath) {
    this.devcontainerPath = devcontainerPath;
    return this;
  }

   /**
   * Path to devcontainer.json from repo root used to create Codespace.
   * @return devcontainerPath
  **/
  public Object getDevcontainerPath() {
    return devcontainerPath;
  }

  public void setDevcontainerPath(Object devcontainerPath) {
    this.devcontainerPath = devcontainerPath;
  }

  public Codespace prebuild(Object prebuild) {
    this.prebuild = prebuild;
    return this;
  }

   /**
   * Whether the codespace was created from a prebuild.
   * @return prebuild
  **/
  public Object getPrebuild() {
    return prebuild;
  }

  public void setPrebuild(Object prebuild) {
    this.prebuild = prebuild;
  }

  public Codespace createdAt(Object createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  public Object getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(Object createdAt) {
    this.createdAt = createdAt;
  }

  public Codespace updatedAt(Object updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  public Object getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(Object updatedAt) {
    this.updatedAt = updatedAt;
  }

  public Codespace lastUsedAt(Object lastUsedAt) {
    this.lastUsedAt = lastUsedAt;
    return this;
  }

   /**
   * Last known time this codespace was started.
   * @return lastUsedAt
  **/
  public Object getLastUsedAt() {
    return lastUsedAt;
  }

  public void setLastUsedAt(Object lastUsedAt) {
    this.lastUsedAt = lastUsedAt;
  }

  public Codespace state(Object state) {
    this.state = state;
    return this;
  }

   /**
   * State of this codespace.
   * @return state
  **/
  public Object getState() {
    return state;
  }

  public void setState(Object state) {
    this.state = state;
  }

  public Codespace url(Object url) {
    this.url = url;
    return this;
  }

   /**
   * API URL for this codespace.
   * @return url
  **/
  public Object getUrl() {
    return url;
  }

  public void setUrl(Object url) {
    this.url = url;
  }

  public Codespace gitStatus(CodespaceGitStatus gitStatus) {
    this.gitStatus = gitStatus;
    return this;
  }

   /**
   * Get gitStatus
   * @return gitStatus
  **/
  public CodespaceGitStatus getGitStatus() {
    return gitStatus;
  }

  public void setGitStatus(CodespaceGitStatus gitStatus) {
    this.gitStatus = gitStatus;
  }

  public Codespace location(Object location) {
    this.location = location;
    return this;
  }

   /**
   * The Azure region where this codespace is located.
   * @return location
  **/
  public Object getLocation() {
    return location;
  }

  public void setLocation(Object location) {
    this.location = location;
  }

  public Codespace idleTimeoutMinutes(Object idleTimeoutMinutes) {
    this.idleTimeoutMinutes = idleTimeoutMinutes;
    return this;
  }

   /**
   * The number of minutes of inactivity after which this codespace will be automatically stopped.
   * @return idleTimeoutMinutes
  **/
  public Object getIdleTimeoutMinutes() {
    return idleTimeoutMinutes;
  }

  public void setIdleTimeoutMinutes(Object idleTimeoutMinutes) {
    this.idleTimeoutMinutes = idleTimeoutMinutes;
  }

  public Codespace webUrl(Object webUrl) {
    this.webUrl = webUrl;
    return this;
  }

   /**
   * URL to access this codespace on the web.
   * @return webUrl
  **/
  public Object getWebUrl() {
    return webUrl;
  }

  public void setWebUrl(Object webUrl) {
    this.webUrl = webUrl;
  }

  public Codespace machinesUrl(Object machinesUrl) {
    this.machinesUrl = machinesUrl;
    return this;
  }

   /**
   * API URL to access available alternate machine types for this codespace.
   * @return machinesUrl
  **/
  public Object getMachinesUrl() {
    return machinesUrl;
  }

  public void setMachinesUrl(Object machinesUrl) {
    this.machinesUrl = machinesUrl;
  }

  public Codespace startUrl(Object startUrl) {
    this.startUrl = startUrl;
    return this;
  }

   /**
   * API URL to start this codespace.
   * @return startUrl
  **/
  public Object getStartUrl() {
    return startUrl;
  }

  public void setStartUrl(Object startUrl) {
    this.startUrl = startUrl;
  }

  public Codespace stopUrl(Object stopUrl) {
    this.stopUrl = stopUrl;
    return this;
  }

   /**
   * API URL to stop this codespace.
   * @return stopUrl
  **/
  public Object getStopUrl() {
    return stopUrl;
  }

  public void setStopUrl(Object stopUrl) {
    this.stopUrl = stopUrl;
  }

  public Codespace pullsUrl(Object pullsUrl) {
    this.pullsUrl = pullsUrl;
    return this;
  }

   /**
   * API URL for the Pull Request associated with this codespace, if any.
   * @return pullsUrl
  **/
  public Object getPullsUrl() {
    return pullsUrl;
  }

  public void setPullsUrl(Object pullsUrl) {
    this.pullsUrl = pullsUrl;
  }

  public Codespace recentFolders(Object recentFolders) {
    this.recentFolders = recentFolders;
    return this;
  }

   /**
   * Get recentFolders
   * @return recentFolders
  **/
  public Object getRecentFolders() {
    return recentFolders;
  }

  public void setRecentFolders(Object recentFolders) {
    this.recentFolders = recentFolders;
  }

  public Codespace runtimeConstraints(CodespaceRuntimeConstraints runtimeConstraints) {
    this.runtimeConstraints = runtimeConstraints;
    return this;
  }

   /**
   * Get runtimeConstraints
   * @return runtimeConstraints
  **/
  public CodespaceRuntimeConstraints getRuntimeConstraints() {
    return runtimeConstraints;
  }

  public void setRuntimeConstraints(CodespaceRuntimeConstraints runtimeConstraints) {
    this.runtimeConstraints = runtimeConstraints;
  }

  public Codespace pendingOperation(Object pendingOperation) {
    this.pendingOperation = pendingOperation;
    return this;
  }

   /**
   * Whether or not a codespace has a pending async operation. This would mean that the codespace is temporarily unavailable. The only thing that you can do with a codespace in this state is delete it.
   * @return pendingOperation
  **/
  public Object getPendingOperation() {
    return pendingOperation;
  }

  public void setPendingOperation(Object pendingOperation) {
    this.pendingOperation = pendingOperation;
  }

  public Codespace pendingOperationDisabledReason(Object pendingOperationDisabledReason) {
    this.pendingOperationDisabledReason = pendingOperationDisabledReason;
    return this;
  }

   /**
   * Text to show user when codespace is disabled by a pending operation
   * @return pendingOperationDisabledReason
  **/
  public Object getPendingOperationDisabledReason() {
    return pendingOperationDisabledReason;
  }

  public void setPendingOperationDisabledReason(Object pendingOperationDisabledReason) {
    this.pendingOperationDisabledReason = pendingOperationDisabledReason;
  }

  public Codespace idleTimeoutNotice(Object idleTimeoutNotice) {
    this.idleTimeoutNotice = idleTimeoutNotice;
    return this;
  }

   /**
   * Text to show user when codespace idle timeout minutes has been overriden by an organization policy
   * @return idleTimeoutNotice
  **/
  public Object getIdleTimeoutNotice() {
    return idleTimeoutNotice;
  }

  public void setIdleTimeoutNotice(Object idleTimeoutNotice) {
    this.idleTimeoutNotice = idleTimeoutNotice;
  }

  public Codespace retentionPeriodMinutes(Object retentionPeriodMinutes) {
    this.retentionPeriodMinutes = retentionPeriodMinutes;
    return this;
  }

   /**
   * Duration in minutes after codespace has gone idle in which it will be deleted. Must be integer minutes between 0 and 43200 (30 days).
   * @return retentionPeriodMinutes
  **/
  public Object getRetentionPeriodMinutes() {
    return retentionPeriodMinutes;
  }

  public void setRetentionPeriodMinutes(Object retentionPeriodMinutes) {
    this.retentionPeriodMinutes = retentionPeriodMinutes;
  }

  public Codespace retentionExpiresAt(Object retentionExpiresAt) {
    this.retentionExpiresAt = retentionExpiresAt;
    return this;
  }

   /**
   * When a codespace will be auto-deleted based on the \&quot;retention_period_minutes\&quot; and \&quot;last_used_at\&quot;
   * @return retentionExpiresAt
  **/
  public Object getRetentionExpiresAt() {
    return retentionExpiresAt;
  }

  public void setRetentionExpiresAt(Object retentionExpiresAt) {
    this.retentionExpiresAt = retentionExpiresAt;
  }

  public Codespace lastKnownStopNotice(Object lastKnownStopNotice) {
    this.lastKnownStopNotice = lastKnownStopNotice;
    return this;
  }

   /**
   * The text to display to a user when a codespace has been stopped for a potentially actionable reason.
   * @return lastKnownStopNotice
  **/
  public Object getLastKnownStopNotice() {
    return lastKnownStopNotice;
  }

  public void setLastKnownStopNotice(Object lastKnownStopNotice) {
    this.lastKnownStopNotice = lastKnownStopNotice;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Codespace codespace = (Codespace) o;
    return Objects.equals(this.id, codespace.id) &&
        Objects.equals(this.name, codespace.name) &&
        Objects.equals(this.displayName, codespace.displayName) &&
        Objects.equals(this.environmentId, codespace.environmentId) &&
        Objects.equals(this.owner, codespace.owner) &&
        Objects.equals(this.billableOwner, codespace.billableOwner) &&
        Objects.equals(this.repository, codespace.repository) &&
        Objects.equals(this.machine, codespace.machine) &&
        Objects.equals(this.devcontainerPath, codespace.devcontainerPath) &&
        Objects.equals(this.prebuild, codespace.prebuild) &&
        Objects.equals(this.createdAt, codespace.createdAt) &&
        Objects.equals(this.updatedAt, codespace.updatedAt) &&
        Objects.equals(this.lastUsedAt, codespace.lastUsedAt) &&
        Objects.equals(this.state, codespace.state) &&
        Objects.equals(this.url, codespace.url) &&
        Objects.equals(this.gitStatus, codespace.gitStatus) &&
        Objects.equals(this.location, codespace.location) &&
        Objects.equals(this.idleTimeoutMinutes, codespace.idleTimeoutMinutes) &&
        Objects.equals(this.webUrl, codespace.webUrl) &&
        Objects.equals(this.machinesUrl, codespace.machinesUrl) &&
        Objects.equals(this.startUrl, codespace.startUrl) &&
        Objects.equals(this.stopUrl, codespace.stopUrl) &&
        Objects.equals(this.pullsUrl, codespace.pullsUrl) &&
        Objects.equals(this.recentFolders, codespace.recentFolders) &&
        Objects.equals(this.runtimeConstraints, codespace.runtimeConstraints) &&
        Objects.equals(this.pendingOperation, codespace.pendingOperation) &&
        Objects.equals(this.pendingOperationDisabledReason, codespace.pendingOperationDisabledReason) &&
        Objects.equals(this.idleTimeoutNotice, codespace.idleTimeoutNotice) &&
        Objects.equals(this.retentionPeriodMinutes, codespace.retentionPeriodMinutes) &&
        Objects.equals(this.retentionExpiresAt, codespace.retentionExpiresAt) &&
        Objects.equals(this.lastKnownStopNotice, codespace.lastKnownStopNotice);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, displayName, environmentId, owner, billableOwner, repository, machine, devcontainerPath, prebuild, createdAt, updatedAt, lastUsedAt, state, url, gitStatus, location, idleTimeoutMinutes, webUrl, machinesUrl, startUrl, stopUrl, pullsUrl, recentFolders, runtimeConstraints, pendingOperation, pendingOperationDisabledReason, idleTimeoutNotice, retentionPeriodMinutes, retentionExpiresAt, lastKnownStopNotice);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Codespace {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    environmentId: ").append(toIndentedString(environmentId)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    billableOwner: ").append(toIndentedString(billableOwner)).append("\n");
    sb.append("    repository: ").append(toIndentedString(repository)).append("\n");
    sb.append("    machine: ").append(toIndentedString(machine)).append("\n");
    sb.append("    devcontainerPath: ").append(toIndentedString(devcontainerPath)).append("\n");
    sb.append("    prebuild: ").append(toIndentedString(prebuild)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    lastUsedAt: ").append(toIndentedString(lastUsedAt)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    gitStatus: ").append(toIndentedString(gitStatus)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    idleTimeoutMinutes: ").append(toIndentedString(idleTimeoutMinutes)).append("\n");
    sb.append("    webUrl: ").append(toIndentedString(webUrl)).append("\n");
    sb.append("    machinesUrl: ").append(toIndentedString(machinesUrl)).append("\n");
    sb.append("    startUrl: ").append(toIndentedString(startUrl)).append("\n");
    sb.append("    stopUrl: ").append(toIndentedString(stopUrl)).append("\n");
    sb.append("    pullsUrl: ").append(toIndentedString(pullsUrl)).append("\n");
    sb.append("    recentFolders: ").append(toIndentedString(recentFolders)).append("\n");
    sb.append("    runtimeConstraints: ").append(toIndentedString(runtimeConstraints)).append("\n");
    sb.append("    pendingOperation: ").append(toIndentedString(pendingOperation)).append("\n");
    sb.append("    pendingOperationDisabledReason: ").append(toIndentedString(pendingOperationDisabledReason)).append("\n");
    sb.append("    idleTimeoutNotice: ").append(toIndentedString(idleTimeoutNotice)).append("\n");
    sb.append("    retentionPeriodMinutes: ").append(toIndentedString(retentionPeriodMinutes)).append("\n");
    sb.append("    retentionExpiresAt: ").append(toIndentedString(retentionExpiresAt)).append("\n");
    sb.append("    lastKnownStopNotice: ").append(toIndentedString(lastKnownStopNotice)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
