/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.github.api.client.MinimalRepository;
import com.github.api.client.SearchResultTextMatches;

/**
 * Code Search Result Item
 */
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class CodeSearchResultItem {
  @JsonProperty("name")
  private Object name = null;

  @JsonProperty("path")
  private Object path = null;

  @JsonProperty("sha")
  private Object sha = null;

  @JsonProperty("url")
  private Object url = null;

  @JsonProperty("git_url")
  private Object gitUrl = null;

  @JsonProperty("html_url")
  private Object htmlUrl = null;

  @JsonProperty("repository")
  private MinimalRepository repository = null;

  @JsonProperty("score")
  private Object score = null;

  @JsonProperty("file_size")
  private Object fileSize = null;

  @JsonProperty("language")
  private Object language = null;

  @JsonProperty("last_modified_at")
  private Object lastModifiedAt = null;

  @JsonProperty("line_numbers")
  private Object lineNumbers = null;

  @JsonProperty("text_matches")
  private SearchResultTextMatches textMatches = null;

  public CodeSearchResultItem name(Object name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public Object getName() {
    return name;
  }

  public void setName(Object name) {
    this.name = name;
  }

  public CodeSearchResultItem path(Object path) {
    this.path = path;
    return this;
  }

   /**
   * Get path
   * @return path
  **/
  public Object getPath() {
    return path;
  }

  public void setPath(Object path) {
    this.path = path;
  }

  public CodeSearchResultItem sha(Object sha) {
    this.sha = sha;
    return this;
  }

   /**
   * Get sha
   * @return sha
  **/
  public Object getSha() {
    return sha;
  }

  public void setSha(Object sha) {
    this.sha = sha;
  }

  public CodeSearchResultItem url(Object url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  public Object getUrl() {
    return url;
  }

  public void setUrl(Object url) {
    this.url = url;
  }

  public CodeSearchResultItem gitUrl(Object gitUrl) {
    this.gitUrl = gitUrl;
    return this;
  }

   /**
   * Get gitUrl
   * @return gitUrl
  **/
  public Object getGitUrl() {
    return gitUrl;
  }

  public void setGitUrl(Object gitUrl) {
    this.gitUrl = gitUrl;
  }

  public CodeSearchResultItem htmlUrl(Object htmlUrl) {
    this.htmlUrl = htmlUrl;
    return this;
  }

   /**
   * Get htmlUrl
   * @return htmlUrl
  **/
  public Object getHtmlUrl() {
    return htmlUrl;
  }

  public void setHtmlUrl(Object htmlUrl) {
    this.htmlUrl = htmlUrl;
  }

  public CodeSearchResultItem repository(MinimalRepository repository) {
    this.repository = repository;
    return this;
  }

   /**
   * Get repository
   * @return repository
  **/
  public MinimalRepository getRepository() {
    return repository;
  }

  public void setRepository(MinimalRepository repository) {
    this.repository = repository;
  }

  public CodeSearchResultItem score(Object score) {
    this.score = score;
    return this;
  }

   /**
   * Get score
   * @return score
  **/
  public Object getScore() {
    return score;
  }

  public void setScore(Object score) {
    this.score = score;
  }

  public CodeSearchResultItem fileSize(Object fileSize) {
    this.fileSize = fileSize;
    return this;
  }

   /**
   * Get fileSize
   * @return fileSize
  **/
  public Object getFileSize() {
    return fileSize;
  }

  public void setFileSize(Object fileSize) {
    this.fileSize = fileSize;
  }

  public CodeSearchResultItem language(Object language) {
    this.language = language;
    return this;
  }

   /**
   * Get language
   * @return language
  **/
  public Object getLanguage() {
    return language;
  }

  public void setLanguage(Object language) {
    this.language = language;
  }

  public CodeSearchResultItem lastModifiedAt(Object lastModifiedAt) {
    this.lastModifiedAt = lastModifiedAt;
    return this;
  }

   /**
   * Get lastModifiedAt
   * @return lastModifiedAt
  **/
  public Object getLastModifiedAt() {
    return lastModifiedAt;
  }

  public void setLastModifiedAt(Object lastModifiedAt) {
    this.lastModifiedAt = lastModifiedAt;
  }

  public CodeSearchResultItem lineNumbers(Object lineNumbers) {
    this.lineNumbers = lineNumbers;
    return this;
  }

   /**
   * Get lineNumbers
   * @return lineNumbers
  **/
  public Object getLineNumbers() {
    return lineNumbers;
  }

  public void setLineNumbers(Object lineNumbers) {
    this.lineNumbers = lineNumbers;
  }

  public CodeSearchResultItem textMatches(SearchResultTextMatches textMatches) {
    this.textMatches = textMatches;
    return this;
  }

   /**
   * Get textMatches
   * @return textMatches
  **/
  public SearchResultTextMatches getTextMatches() {
    return textMatches;
  }

  public void setTextMatches(SearchResultTextMatches textMatches) {
    this.textMatches = textMatches;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CodeSearchResultItem codeSearchResultItem = (CodeSearchResultItem) o;
    return Objects.equals(this.name, codeSearchResultItem.name) &&
        Objects.equals(this.path, codeSearchResultItem.path) &&
        Objects.equals(this.sha, codeSearchResultItem.sha) &&
        Objects.equals(this.url, codeSearchResultItem.url) &&
        Objects.equals(this.gitUrl, codeSearchResultItem.gitUrl) &&
        Objects.equals(this.htmlUrl, codeSearchResultItem.htmlUrl) &&
        Objects.equals(this.repository, codeSearchResultItem.repository) &&
        Objects.equals(this.score, codeSearchResultItem.score) &&
        Objects.equals(this.fileSize, codeSearchResultItem.fileSize) &&
        Objects.equals(this.language, codeSearchResultItem.language) &&
        Objects.equals(this.lastModifiedAt, codeSearchResultItem.lastModifiedAt) &&
        Objects.equals(this.lineNumbers, codeSearchResultItem.lineNumbers) &&
        Objects.equals(this.textMatches, codeSearchResultItem.textMatches);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, path, sha, url, gitUrl, htmlUrl, repository, score, fileSize, language, lastModifiedAt, lineNumbers, textMatches);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CodeSearchResultItem {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    sha: ").append(toIndentedString(sha)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    gitUrl: ").append(toIndentedString(gitUrl)).append("\n");
    sb.append("    htmlUrl: ").append(toIndentedString(htmlUrl)).append("\n");
    sb.append("    repository: ").append(toIndentedString(repository)).append("\n");
    sb.append("    score: ").append(toIndentedString(score)).append("\n");
    sb.append("    fileSize: ").append(toIndentedString(fileSize)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    lastModifiedAt: ").append(toIndentedString(lastModifiedAt)).append("\n");
    sb.append("    lineNumbers: ").append(toIndentedString(lineNumbers)).append("\n");
    sb.append("    textMatches: ").append(toIndentedString(textMatches)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
