/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Metaproperties for Git author/committer information.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class Committer {
  @JsonProperty("date")
  private Object date = null;

  @JsonProperty("email")
  private Object email = null;

  @JsonProperty("name")
  private Object name = null;

  @JsonProperty("username")
  private Object username = null;

  public Committer date(Object date) {
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  public Object getDate() {
    return date;
  }

  public void setDate(Object date) {
    this.date = date;
  }

  public Committer email(Object email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  public Object getEmail() {
    return email;
  }

  public void setEmail(Object email) {
    this.email = email;
  }

  public Committer name(Object name) {
    this.name = name;
    return this;
  }

   /**
   * The git author&#x27;s name.
   * @return name
  **/
  public Object getName() {
    return name;
  }

  public void setName(Object name) {
    this.name = name;
  }

  public Committer username(Object username) {
    this.username = username;
    return this;
  }

   /**
   * Get username
   * @return username
  **/
  public Object getUsername() {
    return username;
  }

  public void setUsername(Object username) {
    this.username = username;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Committer committer = (Committer) o;
    return Objects.equals(this.date, committer.date) &&
        Objects.equals(this.email, committer.email) &&
        Objects.equals(this.name, committer.name) &&
        Objects.equals(this.username, committer.username);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, email, name, username);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Committer {\n");
    
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
