/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.github.api.client.AlertCreatedAt;
import com.github.api.client.AlertDismissedAt;
import com.github.api.client.AlertFixedAt;
import com.github.api.client.AlertHtmlUrl;
import com.github.api.client.AlertNumber;
import com.github.api.client.AlertUpdatedAt;
import com.github.api.client.AlertUrl;
import com.github.api.client.DependabotAlertSecurityAdvisory;
import com.github.api.client.DependabotAlertSecurityVulnerability;
import com.github.api.client.DependabotalertwithrepositoryDependency;
import com.github.api.client.SimpleRepository;

/**
 * A Dependabot alert.
 */
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class DependabotAlertWithRepository {
  @JsonProperty("number")
  private AlertNumber number = null;

  @JsonProperty("state")
  private Object state = null;

  @JsonProperty("dependency")
  private DependabotalertwithrepositoryDependency dependency = null;

  @JsonProperty("security_advisory")
  private DependabotAlertSecurityAdvisory securityAdvisory = null;

  @JsonProperty("security_vulnerability")
  private DependabotAlertSecurityVulnerability securityVulnerability = null;

  @JsonProperty("url")
  private AlertUrl url = null;

  @JsonProperty("html_url")
  private AlertHtmlUrl htmlUrl = null;

  @JsonProperty("created_at")
  private AlertCreatedAt createdAt = null;

  @JsonProperty("updated_at")
  private AlertUpdatedAt updatedAt = null;

  @JsonProperty("dismissed_at")
  private AlertDismissedAt dismissedAt = null;

  @JsonProperty("dismissed_by")
  private Object dismissedBy = null;

  @JsonProperty("dismissed_reason")
  private Object dismissedReason = null;

  @JsonProperty("dismissed_comment")
  private Object dismissedComment = null;

  @JsonProperty("fixed_at")
  private AlertFixedAt fixedAt = null;

  @JsonProperty("repository")
  private SimpleRepository repository = null;

  public DependabotAlertWithRepository number(AlertNumber number) {
    this.number = number;
    return this;
  }

   /**
   * Get number
   * @return number
  **/
  public AlertNumber getNumber() {
    return number;
  }

  public void setNumber(AlertNumber number) {
    this.number = number;
  }

   /**
   * The state of the Dependabot alert.
   * @return state
  **/
  public Object getState() {
    return state;
  }

  public DependabotAlertWithRepository dependency(DependabotalertwithrepositoryDependency dependency) {
    this.dependency = dependency;
    return this;
  }

   /**
   * Get dependency
   * @return dependency
  **/
  public DependabotalertwithrepositoryDependency getDependency() {
    return dependency;
  }

  public void setDependency(DependabotalertwithrepositoryDependency dependency) {
    this.dependency = dependency;
  }

  public DependabotAlertWithRepository securityAdvisory(DependabotAlertSecurityAdvisory securityAdvisory) {
    this.securityAdvisory = securityAdvisory;
    return this;
  }

   /**
   * Get securityAdvisory
   * @return securityAdvisory
  **/
  public DependabotAlertSecurityAdvisory getSecurityAdvisory() {
    return securityAdvisory;
  }

  public void setSecurityAdvisory(DependabotAlertSecurityAdvisory securityAdvisory) {
    this.securityAdvisory = securityAdvisory;
  }

  public DependabotAlertWithRepository securityVulnerability(DependabotAlertSecurityVulnerability securityVulnerability) {
    this.securityVulnerability = securityVulnerability;
    return this;
  }

   /**
   * Get securityVulnerability
   * @return securityVulnerability
  **/
  public DependabotAlertSecurityVulnerability getSecurityVulnerability() {
    return securityVulnerability;
  }

  public void setSecurityVulnerability(DependabotAlertSecurityVulnerability securityVulnerability) {
    this.securityVulnerability = securityVulnerability;
  }

  public DependabotAlertWithRepository url(AlertUrl url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  public AlertUrl getUrl() {
    return url;
  }

  public void setUrl(AlertUrl url) {
    this.url = url;
  }

  public DependabotAlertWithRepository htmlUrl(AlertHtmlUrl htmlUrl) {
    this.htmlUrl = htmlUrl;
    return this;
  }

   /**
   * Get htmlUrl
   * @return htmlUrl
  **/
  public AlertHtmlUrl getHtmlUrl() {
    return htmlUrl;
  }

  public void setHtmlUrl(AlertHtmlUrl htmlUrl) {
    this.htmlUrl = htmlUrl;
  }

  public DependabotAlertWithRepository createdAt(AlertCreatedAt createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  public AlertCreatedAt getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(AlertCreatedAt createdAt) {
    this.createdAt = createdAt;
  }

  public DependabotAlertWithRepository updatedAt(AlertUpdatedAt updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  public AlertUpdatedAt getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(AlertUpdatedAt updatedAt) {
    this.updatedAt = updatedAt;
  }

  public DependabotAlertWithRepository dismissedAt(AlertDismissedAt dismissedAt) {
    this.dismissedAt = dismissedAt;
    return this;
  }

   /**
   * Get dismissedAt
   * @return dismissedAt
  **/
  public AlertDismissedAt getDismissedAt() {
    return dismissedAt;
  }

  public void setDismissedAt(AlertDismissedAt dismissedAt) {
    this.dismissedAt = dismissedAt;
  }

  public DependabotAlertWithRepository dismissedBy(Object dismissedBy) {
    this.dismissedBy = dismissedBy;
    return this;
  }

   /**
   * Get dismissedBy
   * @return dismissedBy
  **/
  public Object getDismissedBy() {
    return dismissedBy;
  }

  public void setDismissedBy(Object dismissedBy) {
    this.dismissedBy = dismissedBy;
  }

  public DependabotAlertWithRepository dismissedReason(Object dismissedReason) {
    this.dismissedReason = dismissedReason;
    return this;
  }

   /**
   * The reason that the alert was dismissed.
   * @return dismissedReason
  **/
  public Object getDismissedReason() {
    return dismissedReason;
  }

  public void setDismissedReason(Object dismissedReason) {
    this.dismissedReason = dismissedReason;
  }

  public DependabotAlertWithRepository dismissedComment(Object dismissedComment) {
    this.dismissedComment = dismissedComment;
    return this;
  }

   /**
   * An optional comment associated with the alert&#x27;s dismissal.
   * @return dismissedComment
  **/
  public Object getDismissedComment() {
    return dismissedComment;
  }

  public void setDismissedComment(Object dismissedComment) {
    this.dismissedComment = dismissedComment;
  }

  public DependabotAlertWithRepository fixedAt(AlertFixedAt fixedAt) {
    this.fixedAt = fixedAt;
    return this;
  }

   /**
   * Get fixedAt
   * @return fixedAt
  **/
  public AlertFixedAt getFixedAt() {
    return fixedAt;
  }

  public void setFixedAt(AlertFixedAt fixedAt) {
    this.fixedAt = fixedAt;
  }

  public DependabotAlertWithRepository repository(SimpleRepository repository) {
    this.repository = repository;
    return this;
  }

   /**
   * Get repository
   * @return repository
  **/
  public SimpleRepository getRepository() {
    return repository;
  }

  public void setRepository(SimpleRepository repository) {
    this.repository = repository;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DependabotAlertWithRepository dependabotAlertWithRepository = (DependabotAlertWithRepository) o;
    return Objects.equals(this.number, dependabotAlertWithRepository.number) &&
        Objects.equals(this.state, dependabotAlertWithRepository.state) &&
        Objects.equals(this.dependency, dependabotAlertWithRepository.dependency) &&
        Objects.equals(this.securityAdvisory, dependabotAlertWithRepository.securityAdvisory) &&
        Objects.equals(this.securityVulnerability, dependabotAlertWithRepository.securityVulnerability) &&
        Objects.equals(this.url, dependabotAlertWithRepository.url) &&
        Objects.equals(this.htmlUrl, dependabotAlertWithRepository.htmlUrl) &&
        Objects.equals(this.createdAt, dependabotAlertWithRepository.createdAt) &&
        Objects.equals(this.updatedAt, dependabotAlertWithRepository.updatedAt) &&
        Objects.equals(this.dismissedAt, dependabotAlertWithRepository.dismissedAt) &&
        Objects.equals(this.dismissedBy, dependabotAlertWithRepository.dismissedBy) &&
        Objects.equals(this.dismissedReason, dependabotAlertWithRepository.dismissedReason) &&
        Objects.equals(this.dismissedComment, dependabotAlertWithRepository.dismissedComment) &&
        Objects.equals(this.fixedAt, dependabotAlertWithRepository.fixedAt) &&
        Objects.equals(this.repository, dependabotAlertWithRepository.repository);
  }

  @Override
  public int hashCode() {
    return Objects.hash(number, state, dependency, securityAdvisory, securityVulnerability, url, htmlUrl, createdAt, updatedAt, dismissedAt, dismissedBy, dismissedReason, dismissedComment, fixedAt, repository);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DependabotAlertWithRepository {\n");
    
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    dependency: ").append(toIndentedString(dependency)).append("\n");
    sb.append("    securityAdvisory: ").append(toIndentedString(securityAdvisory)).append("\n");
    sb.append("    securityVulnerability: ").append(toIndentedString(securityVulnerability)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    htmlUrl: ").append(toIndentedString(htmlUrl)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    dismissedAt: ").append(toIndentedString(dismissedAt)).append("\n");
    sb.append("    dismissedBy: ").append(toIndentedString(dismissedBy)).append("\n");
    sb.append("    dismissedReason: ").append(toIndentedString(dismissedReason)).append("\n");
    sb.append("    dismissedComment: ").append(toIndentedString(dismissedComment)).append("\n");
    sb.append("    fixedAt: ").append(toIndentedString(fixedAt)).append("\n");
    sb.append("    repository: ").append(toIndentedString(repository)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
