/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.github.api.client.LinkWithType;

/**
 * FeedLinks
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class FeedLinks {
  @JsonProperty("timeline")
  private LinkWithType timeline = null;

  @JsonProperty("user")
  private LinkWithType user = null;

  @JsonProperty("security_advisories")
  private LinkWithType securityAdvisories = null;

  @JsonProperty("current_user")
  private LinkWithType currentUser = null;

  @JsonProperty("current_user_public")
  private LinkWithType currentUserPublic = null;

  @JsonProperty("current_user_actor")
  private LinkWithType currentUserActor = null;

  @JsonProperty("current_user_organization")
  private LinkWithType currentUserOrganization = null;

  @JsonProperty("current_user_organizations")
  private Object currentUserOrganizations = null;

  public FeedLinks timeline(LinkWithType timeline) {
    this.timeline = timeline;
    return this;
  }

   /**
   * Get timeline
   * @return timeline
  **/
  public LinkWithType getTimeline() {
    return timeline;
  }

  public void setTimeline(LinkWithType timeline) {
    this.timeline = timeline;
  }

  public FeedLinks user(LinkWithType user) {
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  public LinkWithType getUser() {
    return user;
  }

  public void setUser(LinkWithType user) {
    this.user = user;
  }

  public FeedLinks securityAdvisories(LinkWithType securityAdvisories) {
    this.securityAdvisories = securityAdvisories;
    return this;
  }

   /**
   * Get securityAdvisories
   * @return securityAdvisories
  **/
  public LinkWithType getSecurityAdvisories() {
    return securityAdvisories;
  }

  public void setSecurityAdvisories(LinkWithType securityAdvisories) {
    this.securityAdvisories = securityAdvisories;
  }

  public FeedLinks currentUser(LinkWithType currentUser) {
    this.currentUser = currentUser;
    return this;
  }

   /**
   * Get currentUser
   * @return currentUser
  **/
  public LinkWithType getCurrentUser() {
    return currentUser;
  }

  public void setCurrentUser(LinkWithType currentUser) {
    this.currentUser = currentUser;
  }

  public FeedLinks currentUserPublic(LinkWithType currentUserPublic) {
    this.currentUserPublic = currentUserPublic;
    return this;
  }

   /**
   * Get currentUserPublic
   * @return currentUserPublic
  **/
  public LinkWithType getCurrentUserPublic() {
    return currentUserPublic;
  }

  public void setCurrentUserPublic(LinkWithType currentUserPublic) {
    this.currentUserPublic = currentUserPublic;
  }

  public FeedLinks currentUserActor(LinkWithType currentUserActor) {
    this.currentUserActor = currentUserActor;
    return this;
  }

   /**
   * Get currentUserActor
   * @return currentUserActor
  **/
  public LinkWithType getCurrentUserActor() {
    return currentUserActor;
  }

  public void setCurrentUserActor(LinkWithType currentUserActor) {
    this.currentUserActor = currentUserActor;
  }

  public FeedLinks currentUserOrganization(LinkWithType currentUserOrganization) {
    this.currentUserOrganization = currentUserOrganization;
    return this;
  }

   /**
   * Get currentUserOrganization
   * @return currentUserOrganization
  **/
  public LinkWithType getCurrentUserOrganization() {
    return currentUserOrganization;
  }

  public void setCurrentUserOrganization(LinkWithType currentUserOrganization) {
    this.currentUserOrganization = currentUserOrganization;
  }

  public FeedLinks currentUserOrganizations(Object currentUserOrganizations) {
    this.currentUserOrganizations = currentUserOrganizations;
    return this;
  }

   /**
   * Get currentUserOrganizations
   * @return currentUserOrganizations
  **/
  public Object getCurrentUserOrganizations() {
    return currentUserOrganizations;
  }

  public void setCurrentUserOrganizations(Object currentUserOrganizations) {
    this.currentUserOrganizations = currentUserOrganizations;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FeedLinks feedLinks = (FeedLinks) o;
    return Objects.equals(this.timeline, feedLinks.timeline) &&
        Objects.equals(this.user, feedLinks.user) &&
        Objects.equals(this.securityAdvisories, feedLinks.securityAdvisories) &&
        Objects.equals(this.currentUser, feedLinks.currentUser) &&
        Objects.equals(this.currentUserPublic, feedLinks.currentUserPublic) &&
        Objects.equals(this.currentUserActor, feedLinks.currentUserActor) &&
        Objects.equals(this.currentUserOrganization, feedLinks.currentUserOrganization) &&
        Objects.equals(this.currentUserOrganizations, feedLinks.currentUserOrganizations);
  }

  @Override
  public int hashCode() {
    return Objects.hash(timeline, user, securityAdvisories, currentUser, currentUserPublic, currentUserActor, currentUserOrganization, currentUserOrganizations);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FeedLinks {\n");
    
    sb.append("    timeline: ").append(toIndentedString(timeline)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    securityAdvisories: ").append(toIndentedString(securityAdvisories)).append("\n");
    sb.append("    currentUser: ").append(toIndentedString(currentUser)).append("\n");
    sb.append("    currentUserPublic: ").append(toIndentedString(currentUserPublic)).append("\n");
    sb.append("    currentUserActor: ").append(toIndentedString(currentUserActor)).append("\n");
    sb.append("    currentUserOrganization: ").append(toIndentedString(currentUserOrganization)).append("\n");
    sb.append("    currentUserOrganizations: ").append(toIndentedString(currentUserOrganizations)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
