/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * FilecommitCommitTree
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class FilecommitCommitTree {
  @JsonProperty("url")
  private Object url = null;

  @JsonProperty("sha")
  private Object sha = null;

  public FilecommitCommitTree url(Object url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  public Object getUrl() {
    return url;
  }

  public void setUrl(Object url) {
    this.url = url;
  }

  public FilecommitCommitTree sha(Object sha) {
    this.sha = sha;
    return this;
  }

   /**
   * Get sha
   * @return sha
  **/
  public Object getSha() {
    return sha;
  }

  public void setSha(Object sha) {
    this.sha = sha;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FilecommitCommitTree filecommitCommitTree = (FilecommitCommitTree) o;
    return Objects.equals(this.url, filecommitCommitTree.url) &&
        Objects.equals(this.sha, filecommitCommitTree.sha);
  }

  @Override
  public int hashCode() {
    return Objects.hash(url, sha);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FilecommitCommitTree {\n");
    
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    sha: ").append(toIndentedString(sha)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
