/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * GisthistoryChangeStatus
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class GisthistoryChangeStatus {
  @JsonProperty("total")
  private Object total = null;

  @JsonProperty("additions")
  private Object additions = null;

  @JsonProperty("deletions")
  private Object deletions = null;

  public GisthistoryChangeStatus total(Object total) {
    this.total = total;
    return this;
  }

   /**
   * Get total
   * @return total
  **/
  public Object getTotal() {
    return total;
  }

  public void setTotal(Object total) {
    this.total = total;
  }

  public GisthistoryChangeStatus additions(Object additions) {
    this.additions = additions;
    return this;
  }

   /**
   * Get additions
   * @return additions
  **/
  public Object getAdditions() {
    return additions;
  }

  public void setAdditions(Object additions) {
    this.additions = additions;
  }

  public GisthistoryChangeStatus deletions(Object deletions) {
    this.deletions = deletions;
    return this;
  }

   /**
   * Get deletions
   * @return deletions
  **/
  public Object getDeletions() {
    return deletions;
  }

  public void setDeletions(Object deletions) {
    this.deletions = deletions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GisthistoryChangeStatus gisthistoryChangeStatus = (GisthistoryChangeStatus) o;
    return Objects.equals(this.total, gisthistoryChangeStatus.total) &&
        Objects.equals(this.additions, gisthistoryChangeStatus.additions) &&
        Objects.equals(this.deletions, gisthistoryChangeStatus.deletions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(total, additions, deletions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GisthistoryChangeStatus {\n");
    
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    additions: ").append(toIndentedString(additions)).append("\n");
    sb.append("    deletions: ").append(toIndentedString(deletions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
