/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * The hierarchy between files in a Git repository.
 */
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class GitTree {
  @JsonProperty("sha")
  private Object sha = null;

  @JsonProperty("url")
  private Object url = null;

  @JsonProperty("truncated")
  private Object truncated = null;

  @JsonProperty("tree")
  private Object tree = null;

  public GitTree sha(Object sha) {
    this.sha = sha;
    return this;
  }

   /**
   * Get sha
   * @return sha
  **/
  public Object getSha() {
    return sha;
  }

  public void setSha(Object sha) {
    this.sha = sha;
  }

  public GitTree url(Object url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  public Object getUrl() {
    return url;
  }

  public void setUrl(Object url) {
    this.url = url;
  }

  public GitTree truncated(Object truncated) {
    this.truncated = truncated;
    return this;
  }

   /**
   * Get truncated
   * @return truncated
  **/
  public Object getTruncated() {
    return truncated;
  }

  public void setTruncated(Object truncated) {
    this.truncated = truncated;
  }

  public GitTree tree(Object tree) {
    this.tree = tree;
    return this;
  }

   /**
   * Objects specifying a tree structure
   * @return tree
  **/
  public Object getTree() {
    return tree;
  }

  public void setTree(Object tree) {
    this.tree = tree;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GitTree gitTree = (GitTree) o;
    return Objects.equals(this.sha, gitTree.sha) &&
        Objects.equals(this.url, gitTree.url) &&
        Objects.equals(this.truncated, gitTree.truncated) &&
        Objects.equals(this.tree, gitTree.tree);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sha, url, truncated, tree);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GitTree {\n");
    
    sb.append("    sha: ").append(toIndentedString(sha)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    truncated: ").append(toIndentedString(truncated)).append("\n");
    sb.append("    tree: ").append(toIndentedString(tree)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
