/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * HookdeliveryRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class HookdeliveryRequest {
  @JsonProperty("headers")
  private Object headers = null;

  @JsonProperty("payload")
  private Object payload = null;

  public HookdeliveryRequest headers(Object headers) {
    this.headers = headers;
    return this;
  }

   /**
   * The request headers sent with the webhook delivery.
   * @return headers
  **/
  public Object getHeaders() {
    return headers;
  }

  public void setHeaders(Object headers) {
    this.headers = headers;
  }

  public HookdeliveryRequest payload(Object payload) {
    this.payload = payload;
    return this;
  }

   /**
   * The webhook payload.
   * @return payload
  **/
  public Object getPayload() {
    return payload;
  }

  public void setPayload(Object payload) {
    this.payload = payload;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HookdeliveryRequest hookdeliveryRequest = (HookdeliveryRequest) o;
    return Objects.equals(this.headers, hookdeliveryRequest.headers) &&
        Objects.equals(this.payload, hookdeliveryRequest.payload);
  }

  @Override
  public int hashCode() {
    return Objects.hash(headers, payload);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HookdeliveryRequest {\n");
    
    sb.append("    headers: ").append(toIndentedString(headers)).append("\n");
    sb.append("    payload: ").append(toIndentedString(payload)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
