/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * InlineResponse4031
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class InlineResponse4031 {
  @JsonProperty("message")
  private Object message = null;

  @JsonProperty("documentation_url")
  private Object documentationUrl = null;

  @JsonProperty("errors")
  private Object errors = null;

  public InlineResponse4031 message(Object message) {
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  public Object getMessage() {
    return message;
  }

  public void setMessage(Object message) {
    this.message = message;
  }

  public InlineResponse4031 documentationUrl(Object documentationUrl) {
    this.documentationUrl = documentationUrl;
    return this;
  }

   /**
   * Get documentationUrl
   * @return documentationUrl
  **/
  public Object getDocumentationUrl() {
    return documentationUrl;
  }

  public void setDocumentationUrl(Object documentationUrl) {
    this.documentationUrl = documentationUrl;
  }

  public InlineResponse4031 errors(Object errors) {
    this.errors = errors;
    return this;
  }

   /**
   * Get errors
   * @return errors
  **/
  public Object getErrors() {
    return errors;
  }

  public void setErrors(Object errors) {
    this.errors = errors;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse4031 inlineResponse4031 = (InlineResponse4031) o;
    return Objects.equals(this.message, inlineResponse4031.message) &&
        Objects.equals(this.documentationUrl, inlineResponse4031.documentationUrl) &&
        Objects.equals(this.errors, inlineResponse4031.errors);
  }

  @Override
  public int hashCode() {
    return Objects.hash(message, documentationUrl, errors);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse4031 {\n");
    
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    documentationUrl: ").append(toIndentedString(documentationUrl)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
