/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.github.api.client.AuthorAssociation;
import com.github.api.client.IssueEventDismissedReview;
import com.github.api.client.IssueEventLabel;
import com.github.api.client.IssueEventMilestone;
import com.github.api.client.IssueEventProjectCard;
import com.github.api.client.IssueEventRename;
import com.github.api.client.Team;

/**
 * Issue Event
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class IssueEvent {
  @JsonProperty("id")
  private Object id = null;

  @JsonProperty("node_id")
  private Object nodeId = null;

  @JsonProperty("url")
  private Object url = null;

  @JsonProperty("actor")
  private Object actor = null;

  @JsonProperty("event")
  private Object event = null;

  @JsonProperty("commit_id")
  private Object commitId = null;

  @JsonProperty("commit_url")
  private Object commitUrl = null;

  @JsonProperty("created_at")
  private Object createdAt = null;

  @JsonProperty("issue")
  private Object issue = null;

  @JsonProperty("label")
  private IssueEventLabel label = null;

  @JsonProperty("assignee")
  private Object assignee = null;

  @JsonProperty("assigner")
  private Object assigner = null;

  @JsonProperty("review_requester")
  private Object reviewRequester = null;

  @JsonProperty("requested_reviewer")
  private Object requestedReviewer = null;

  @JsonProperty("requested_team")
  private Team requestedTeam = null;

  @JsonProperty("dismissed_review")
  private IssueEventDismissedReview dismissedReview = null;

  @JsonProperty("milestone")
  private IssueEventMilestone milestone = null;

  @JsonProperty("project_card")
  private IssueEventProjectCard projectCard = null;

  @JsonProperty("rename")
  private IssueEventRename rename = null;

  @JsonProperty("author_association")
  private AuthorAssociation authorAssociation = null;

  @JsonProperty("lock_reason")
  private Object lockReason = null;

  @JsonProperty("performed_via_github_app")
  private Object performedViaGithubApp = null;

  public IssueEvent id(Object id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Object getId() {
    return id;
  }

  public void setId(Object id) {
    this.id = id;
  }

  public IssueEvent nodeId(Object nodeId) {
    this.nodeId = nodeId;
    return this;
  }

   /**
   * Get nodeId
   * @return nodeId
  **/
  public Object getNodeId() {
    return nodeId;
  }

  public void setNodeId(Object nodeId) {
    this.nodeId = nodeId;
  }

  public IssueEvent url(Object url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  public Object getUrl() {
    return url;
  }

  public void setUrl(Object url) {
    this.url = url;
  }

  public IssueEvent actor(Object actor) {
    this.actor = actor;
    return this;
  }

   /**
   * Get actor
   * @return actor
  **/
  public Object getActor() {
    return actor;
  }

  public void setActor(Object actor) {
    this.actor = actor;
  }

  public IssueEvent event(Object event) {
    this.event = event;
    return this;
  }

   /**
   * Get event
   * @return event
  **/
  public Object getEvent() {
    return event;
  }

  public void setEvent(Object event) {
    this.event = event;
  }

  public IssueEvent commitId(Object commitId) {
    this.commitId = commitId;
    return this;
  }

   /**
   * Get commitId
   * @return commitId
  **/
  public Object getCommitId() {
    return commitId;
  }

  public void setCommitId(Object commitId) {
    this.commitId = commitId;
  }

  public IssueEvent commitUrl(Object commitUrl) {
    this.commitUrl = commitUrl;
    return this;
  }

   /**
   * Get commitUrl
   * @return commitUrl
  **/
  public Object getCommitUrl() {
    return commitUrl;
  }

  public void setCommitUrl(Object commitUrl) {
    this.commitUrl = commitUrl;
  }

  public IssueEvent createdAt(Object createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  public Object getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(Object createdAt) {
    this.createdAt = createdAt;
  }

  public IssueEvent issue(Object issue) {
    this.issue = issue;
    return this;
  }

   /**
   * Get issue
   * @return issue
  **/
  public Object getIssue() {
    return issue;
  }

  public void setIssue(Object issue) {
    this.issue = issue;
  }

  public IssueEvent label(IssueEventLabel label) {
    this.label = label;
    return this;
  }

   /**
   * Get label
   * @return label
  **/
  public IssueEventLabel getLabel() {
    return label;
  }

  public void setLabel(IssueEventLabel label) {
    this.label = label;
  }

  public IssueEvent assignee(Object assignee) {
    this.assignee = assignee;
    return this;
  }

   /**
   * Get assignee
   * @return assignee
  **/
  public Object getAssignee() {
    return assignee;
  }

  public void setAssignee(Object assignee) {
    this.assignee = assignee;
  }

  public IssueEvent assigner(Object assigner) {
    this.assigner = assigner;
    return this;
  }

   /**
   * Get assigner
   * @return assigner
  **/
  public Object getAssigner() {
    return assigner;
  }

  public void setAssigner(Object assigner) {
    this.assigner = assigner;
  }

  public IssueEvent reviewRequester(Object reviewRequester) {
    this.reviewRequester = reviewRequester;
    return this;
  }

   /**
   * Get reviewRequester
   * @return reviewRequester
  **/
  public Object getReviewRequester() {
    return reviewRequester;
  }

  public void setReviewRequester(Object reviewRequester) {
    this.reviewRequester = reviewRequester;
  }

  public IssueEvent requestedReviewer(Object requestedReviewer) {
    this.requestedReviewer = requestedReviewer;
    return this;
  }

   /**
   * Get requestedReviewer
   * @return requestedReviewer
  **/
  public Object getRequestedReviewer() {
    return requestedReviewer;
  }

  public void setRequestedReviewer(Object requestedReviewer) {
    this.requestedReviewer = requestedReviewer;
  }

  public IssueEvent requestedTeam(Team requestedTeam) {
    this.requestedTeam = requestedTeam;
    return this;
  }

   /**
   * Get requestedTeam
   * @return requestedTeam
  **/
  public Team getRequestedTeam() {
    return requestedTeam;
  }

  public void setRequestedTeam(Team requestedTeam) {
    this.requestedTeam = requestedTeam;
  }

  public IssueEvent dismissedReview(IssueEventDismissedReview dismissedReview) {
    this.dismissedReview = dismissedReview;
    return this;
  }

   /**
   * Get dismissedReview
   * @return dismissedReview
  **/
  public IssueEventDismissedReview getDismissedReview() {
    return dismissedReview;
  }

  public void setDismissedReview(IssueEventDismissedReview dismissedReview) {
    this.dismissedReview = dismissedReview;
  }

  public IssueEvent milestone(IssueEventMilestone milestone) {
    this.milestone = milestone;
    return this;
  }

   /**
   * Get milestone
   * @return milestone
  **/
  public IssueEventMilestone getMilestone() {
    return milestone;
  }

  public void setMilestone(IssueEventMilestone milestone) {
    this.milestone = milestone;
  }

  public IssueEvent projectCard(IssueEventProjectCard projectCard) {
    this.projectCard = projectCard;
    return this;
  }

   /**
   * Get projectCard
   * @return projectCard
  **/
  public IssueEventProjectCard getProjectCard() {
    return projectCard;
  }

  public void setProjectCard(IssueEventProjectCard projectCard) {
    this.projectCard = projectCard;
  }

  public IssueEvent rename(IssueEventRename rename) {
    this.rename = rename;
    return this;
  }

   /**
   * Get rename
   * @return rename
  **/
  public IssueEventRename getRename() {
    return rename;
  }

  public void setRename(IssueEventRename rename) {
    this.rename = rename;
  }

  public IssueEvent authorAssociation(AuthorAssociation authorAssociation) {
    this.authorAssociation = authorAssociation;
    return this;
  }

   /**
   * Get authorAssociation
   * @return authorAssociation
  **/
  public AuthorAssociation getAuthorAssociation() {
    return authorAssociation;
  }

  public void setAuthorAssociation(AuthorAssociation authorAssociation) {
    this.authorAssociation = authorAssociation;
  }

  public IssueEvent lockReason(Object lockReason) {
    this.lockReason = lockReason;
    return this;
  }

   /**
   * Get lockReason
   * @return lockReason
  **/
  public Object getLockReason() {
    return lockReason;
  }

  public void setLockReason(Object lockReason) {
    this.lockReason = lockReason;
  }

  public IssueEvent performedViaGithubApp(Object performedViaGithubApp) {
    this.performedViaGithubApp = performedViaGithubApp;
    return this;
  }

   /**
   * Get performedViaGithubApp
   * @return performedViaGithubApp
  **/
  public Object getPerformedViaGithubApp() {
    return performedViaGithubApp;
  }

  public void setPerformedViaGithubApp(Object performedViaGithubApp) {
    this.performedViaGithubApp = performedViaGithubApp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IssueEvent issueEvent = (IssueEvent) o;
    return Objects.equals(this.id, issueEvent.id) &&
        Objects.equals(this.nodeId, issueEvent.nodeId) &&
        Objects.equals(this.url, issueEvent.url) &&
        Objects.equals(this.actor, issueEvent.actor) &&
        Objects.equals(this.event, issueEvent.event) &&
        Objects.equals(this.commitId, issueEvent.commitId) &&
        Objects.equals(this.commitUrl, issueEvent.commitUrl) &&
        Objects.equals(this.createdAt, issueEvent.createdAt) &&
        Objects.equals(this.issue, issueEvent.issue) &&
        Objects.equals(this.label, issueEvent.label) &&
        Objects.equals(this.assignee, issueEvent.assignee) &&
        Objects.equals(this.assigner, issueEvent.assigner) &&
        Objects.equals(this.reviewRequester, issueEvent.reviewRequester) &&
        Objects.equals(this.requestedReviewer, issueEvent.requestedReviewer) &&
        Objects.equals(this.requestedTeam, issueEvent.requestedTeam) &&
        Objects.equals(this.dismissedReview, issueEvent.dismissedReview) &&
        Objects.equals(this.milestone, issueEvent.milestone) &&
        Objects.equals(this.projectCard, issueEvent.projectCard) &&
        Objects.equals(this.rename, issueEvent.rename) &&
        Objects.equals(this.authorAssociation, issueEvent.authorAssociation) &&
        Objects.equals(this.lockReason, issueEvent.lockReason) &&
        Objects.equals(this.performedViaGithubApp, issueEvent.performedViaGithubApp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, nodeId, url, actor, event, commitId, commitUrl, createdAt, issue, label, assignee, assigner, reviewRequester, requestedReviewer, requestedTeam, dismissedReview, milestone, projectCard, rename, authorAssociation, lockReason, performedViaGithubApp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IssueEvent {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    nodeId: ").append(toIndentedString(nodeId)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    actor: ").append(toIndentedString(actor)).append("\n");
    sb.append("    event: ").append(toIndentedString(event)).append("\n");
    sb.append("    commitId: ").append(toIndentedString(commitId)).append("\n");
    sb.append("    commitUrl: ").append(toIndentedString(commitUrl)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    issue: ").append(toIndentedString(issue)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    assignee: ").append(toIndentedString(assignee)).append("\n");
    sb.append("    assigner: ").append(toIndentedString(assigner)).append("\n");
    sb.append("    reviewRequester: ").append(toIndentedString(reviewRequester)).append("\n");
    sb.append("    requestedReviewer: ").append(toIndentedString(requestedReviewer)).append("\n");
    sb.append("    requestedTeam: ").append(toIndentedString(requestedTeam)).append("\n");
    sb.append("    dismissedReview: ").append(toIndentedString(dismissedReview)).append("\n");
    sb.append("    milestone: ").append(toIndentedString(milestone)).append("\n");
    sb.append("    projectCard: ").append(toIndentedString(projectCard)).append("\n");
    sb.append("    rename: ").append(toIndentedString(rename)).append("\n");
    sb.append("    authorAssociation: ").append(toIndentedString(authorAssociation)).append("\n");
    sb.append("    lockReason: ").append(toIndentedString(lockReason)).append("\n");
    sb.append("    performedViaGithubApp: ").append(toIndentedString(performedViaGithubApp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
