/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Issue Event Project Card
 */
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class IssueEventProjectCard {
  @JsonProperty("url")
  private Object url = null;

  @JsonProperty("id")
  private Object id = null;

  @JsonProperty("project_url")
  private Object projectUrl = null;

  @JsonProperty("project_id")
  private Object projectId = null;

  @JsonProperty("column_name")
  private Object columnName = null;

  @JsonProperty("previous_column_name")
  private Object previousColumnName = null;

  public IssueEventProjectCard url(Object url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  public Object getUrl() {
    return url;
  }

  public void setUrl(Object url) {
    this.url = url;
  }

  public IssueEventProjectCard id(Object id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Object getId() {
    return id;
  }

  public void setId(Object id) {
    this.id = id;
  }

  public IssueEventProjectCard projectUrl(Object projectUrl) {
    this.projectUrl = projectUrl;
    return this;
  }

   /**
   * Get projectUrl
   * @return projectUrl
  **/
  public Object getProjectUrl() {
    return projectUrl;
  }

  public void setProjectUrl(Object projectUrl) {
    this.projectUrl = projectUrl;
  }

  public IssueEventProjectCard projectId(Object projectId) {
    this.projectId = projectId;
    return this;
  }

   /**
   * Get projectId
   * @return projectId
  **/
  public Object getProjectId() {
    return projectId;
  }

  public void setProjectId(Object projectId) {
    this.projectId = projectId;
  }

  public IssueEventProjectCard columnName(Object columnName) {
    this.columnName = columnName;
    return this;
  }

   /**
   * Get columnName
   * @return columnName
  **/
  public Object getColumnName() {
    return columnName;
  }

  public void setColumnName(Object columnName) {
    this.columnName = columnName;
  }

  public IssueEventProjectCard previousColumnName(Object previousColumnName) {
    this.previousColumnName = previousColumnName;
    return this;
  }

   /**
   * Get previousColumnName
   * @return previousColumnName
  **/
  public Object getPreviousColumnName() {
    return previousColumnName;
  }

  public void setPreviousColumnName(Object previousColumnName) {
    this.previousColumnName = previousColumnName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IssueEventProjectCard issueEventProjectCard = (IssueEventProjectCard) o;
    return Objects.equals(this.url, issueEventProjectCard.url) &&
        Objects.equals(this.id, issueEventProjectCard.id) &&
        Objects.equals(this.projectUrl, issueEventProjectCard.projectUrl) &&
        Objects.equals(this.projectId, issueEventProjectCard.projectId) &&
        Objects.equals(this.columnName, issueEventProjectCard.columnName) &&
        Objects.equals(this.previousColumnName, issueEventProjectCard.previousColumnName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(url, id, projectUrl, projectId, columnName, previousColumnName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IssueEventProjectCard {\n");
    
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    projectUrl: ").append(toIndentedString(projectUrl)).append("\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    columnName: ").append(toIndentedString(columnName)).append("\n");
    sb.append("    previousColumnName: ").append(toIndentedString(previousColumnName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
