/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * MarketplacePurchaseAccount
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class MarketplacePurchaseAccount {
  @JsonProperty("id")
  private Object id = null;

  @JsonProperty("login")
  private Object login = null;

  @JsonProperty("node_id")
  private Object nodeId = null;

  @JsonProperty("organization_billing_email")
  private Object organizationBillingEmail = null;

  @JsonProperty("type")
  private Object type = null;

  public MarketplacePurchaseAccount id(Object id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Object getId() {
    return id;
  }

  public void setId(Object id) {
    this.id = id;
  }

  public MarketplacePurchaseAccount login(Object login) {
    this.login = login;
    return this;
  }

   /**
   * Get login
   * @return login
  **/
  public Object getLogin() {
    return login;
  }

  public void setLogin(Object login) {
    this.login = login;
  }

  public MarketplacePurchaseAccount nodeId(Object nodeId) {
    this.nodeId = nodeId;
    return this;
  }

   /**
   * Get nodeId
   * @return nodeId
  **/
  public Object getNodeId() {
    return nodeId;
  }

  public void setNodeId(Object nodeId) {
    this.nodeId = nodeId;
  }

  public MarketplacePurchaseAccount organizationBillingEmail(Object organizationBillingEmail) {
    this.organizationBillingEmail = organizationBillingEmail;
    return this;
  }

   /**
   * Get organizationBillingEmail
   * @return organizationBillingEmail
  **/
  public Object getOrganizationBillingEmail() {
    return organizationBillingEmail;
  }

  public void setOrganizationBillingEmail(Object organizationBillingEmail) {
    this.organizationBillingEmail = organizationBillingEmail;
  }

  public MarketplacePurchaseAccount type(Object type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  public Object getType() {
    return type;
  }

  public void setType(Object type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MarketplacePurchaseAccount marketplacePurchaseAccount = (MarketplacePurchaseAccount) o;
    return Objects.equals(this.id, marketplacePurchaseAccount.id) &&
        Objects.equals(this.login, marketplacePurchaseAccount.login) &&
        Objects.equals(this.nodeId, marketplacePurchaseAccount.nodeId) &&
        Objects.equals(this.organizationBillingEmail, marketplacePurchaseAccount.organizationBillingEmail) &&
        Objects.equals(this.type, marketplacePurchaseAccount.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, login, nodeId, organizationBillingEmail, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MarketplacePurchaseAccount {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    login: ").append(toIndentedString(login)).append("\n");
    sb.append("    nodeId: ").append(toIndentedString(nodeId)).append("\n");
    sb.append("    organizationBillingEmail: ").append(toIndentedString(organizationBillingEmail)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
