/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Results of a successful merge upstream request
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class MergedUpstream {
  @JsonProperty("message")
  private Object message = null;

  @JsonProperty("merge_type")
  private Object mergeType = null;

  @JsonProperty("base_branch")
  private Object baseBranch = null;

  public MergedUpstream message(Object message) {
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  public Object getMessage() {
    return message;
  }

  public void setMessage(Object message) {
    this.message = message;
  }

  public MergedUpstream mergeType(Object mergeType) {
    this.mergeType = mergeType;
    return this;
  }

   /**
   * Get mergeType
   * @return mergeType
  **/
  public Object getMergeType() {
    return mergeType;
  }

  public void setMergeType(Object mergeType) {
    this.mergeType = mergeType;
  }

  public MergedUpstream baseBranch(Object baseBranch) {
    this.baseBranch = baseBranch;
    return this;
  }

   /**
   * Get baseBranch
   * @return baseBranch
  **/
  public Object getBaseBranch() {
    return baseBranch;
  }

  public void setBaseBranch(Object baseBranch) {
    this.baseBranch = baseBranch;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MergedUpstream mergedUpstream = (MergedUpstream) o;
    return Objects.equals(this.message, mergedUpstream.message) &&
        Objects.equals(this.mergeType, mergedUpstream.mergeType) &&
        Objects.equals(this.baseBranch, mergedUpstream.baseBranch);
  }

  @Override
  public int hashCode() {
    return Objects.hash(message, mergeType, baseBranch);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MergedUpstream {\n");
    
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    mergeType: ").append(toIndentedString(mergeType)).append("\n");
    sb.append("    baseBranch: ").append(toIndentedString(baseBranch)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
