/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Organization Simple
 */
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class OrganizationSimple {
  @JsonProperty("login")
  private Object login = null;

  @JsonProperty("id")
  private Object id = null;

  @JsonProperty("node_id")
  private Object nodeId = null;

  @JsonProperty("url")
  private Object url = null;

  @JsonProperty("repos_url")
  private Object reposUrl = null;

  @JsonProperty("events_url")
  private Object eventsUrl = null;

  @JsonProperty("hooks_url")
  private Object hooksUrl = null;

  @JsonProperty("issues_url")
  private Object issuesUrl = null;

  @JsonProperty("members_url")
  private Object membersUrl = null;

  @JsonProperty("public_members_url")
  private Object publicMembersUrl = null;

  @JsonProperty("avatar_url")
  private Object avatarUrl = null;

  @JsonProperty("description")
  private Object description = null;

  public OrganizationSimple login(Object login) {
    this.login = login;
    return this;
  }

   /**
   * Get login
   * @return login
  **/
  public Object getLogin() {
    return login;
  }

  public void setLogin(Object login) {
    this.login = login;
  }

  public OrganizationSimple id(Object id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Object getId() {
    return id;
  }

  public void setId(Object id) {
    this.id = id;
  }

  public OrganizationSimple nodeId(Object nodeId) {
    this.nodeId = nodeId;
    return this;
  }

   /**
   * Get nodeId
   * @return nodeId
  **/
  public Object getNodeId() {
    return nodeId;
  }

  public void setNodeId(Object nodeId) {
    this.nodeId = nodeId;
  }

  public OrganizationSimple url(Object url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  public Object getUrl() {
    return url;
  }

  public void setUrl(Object url) {
    this.url = url;
  }

  public OrganizationSimple reposUrl(Object reposUrl) {
    this.reposUrl = reposUrl;
    return this;
  }

   /**
   * Get reposUrl
   * @return reposUrl
  **/
  public Object getReposUrl() {
    return reposUrl;
  }

  public void setReposUrl(Object reposUrl) {
    this.reposUrl = reposUrl;
  }

  public OrganizationSimple eventsUrl(Object eventsUrl) {
    this.eventsUrl = eventsUrl;
    return this;
  }

   /**
   * Get eventsUrl
   * @return eventsUrl
  **/
  public Object getEventsUrl() {
    return eventsUrl;
  }

  public void setEventsUrl(Object eventsUrl) {
    this.eventsUrl = eventsUrl;
  }

  public OrganizationSimple hooksUrl(Object hooksUrl) {
    this.hooksUrl = hooksUrl;
    return this;
  }

   /**
   * Get hooksUrl
   * @return hooksUrl
  **/
  public Object getHooksUrl() {
    return hooksUrl;
  }

  public void setHooksUrl(Object hooksUrl) {
    this.hooksUrl = hooksUrl;
  }

  public OrganizationSimple issuesUrl(Object issuesUrl) {
    this.issuesUrl = issuesUrl;
    return this;
  }

   /**
   * Get issuesUrl
   * @return issuesUrl
  **/
  public Object getIssuesUrl() {
    return issuesUrl;
  }

  public void setIssuesUrl(Object issuesUrl) {
    this.issuesUrl = issuesUrl;
  }

  public OrganizationSimple membersUrl(Object membersUrl) {
    this.membersUrl = membersUrl;
    return this;
  }

   /**
   * Get membersUrl
   * @return membersUrl
  **/
  public Object getMembersUrl() {
    return membersUrl;
  }

  public void setMembersUrl(Object membersUrl) {
    this.membersUrl = membersUrl;
  }

  public OrganizationSimple publicMembersUrl(Object publicMembersUrl) {
    this.publicMembersUrl = publicMembersUrl;
    return this;
  }

   /**
   * Get publicMembersUrl
   * @return publicMembersUrl
  **/
  public Object getPublicMembersUrl() {
    return publicMembersUrl;
  }

  public void setPublicMembersUrl(Object publicMembersUrl) {
    this.publicMembersUrl = publicMembersUrl;
  }

  public OrganizationSimple avatarUrl(Object avatarUrl) {
    this.avatarUrl = avatarUrl;
    return this;
  }

   /**
   * Get avatarUrl
   * @return avatarUrl
  **/
  public Object getAvatarUrl() {
    return avatarUrl;
  }

  public void setAvatarUrl(Object avatarUrl) {
    this.avatarUrl = avatarUrl;
  }

  public OrganizationSimple description(Object description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  public Object getDescription() {
    return description;
  }

  public void setDescription(Object description) {
    this.description = description;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrganizationSimple organizationSimple = (OrganizationSimple) o;
    return Objects.equals(this.login, organizationSimple.login) &&
        Objects.equals(this.id, organizationSimple.id) &&
        Objects.equals(this.nodeId, organizationSimple.nodeId) &&
        Objects.equals(this.url, organizationSimple.url) &&
        Objects.equals(this.reposUrl, organizationSimple.reposUrl) &&
        Objects.equals(this.eventsUrl, organizationSimple.eventsUrl) &&
        Objects.equals(this.hooksUrl, organizationSimple.hooksUrl) &&
        Objects.equals(this.issuesUrl, organizationSimple.issuesUrl) &&
        Objects.equals(this.membersUrl, organizationSimple.membersUrl) &&
        Objects.equals(this.publicMembersUrl, organizationSimple.publicMembersUrl) &&
        Objects.equals(this.avatarUrl, organizationSimple.avatarUrl) &&
        Objects.equals(this.description, organizationSimple.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(login, id, nodeId, url, reposUrl, eventsUrl, hooksUrl, issuesUrl, membersUrl, publicMembersUrl, avatarUrl, description);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrganizationSimple {\n");
    
    sb.append("    login: ").append(toIndentedString(login)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    nodeId: ").append(toIndentedString(nodeId)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    reposUrl: ").append(toIndentedString(reposUrl)).append("\n");
    sb.append("    eventsUrl: ").append(toIndentedString(eventsUrl)).append("\n");
    sb.append("    hooksUrl: ").append(toIndentedString(hooksUrl)).append("\n");
    sb.append("    issuesUrl: ").append(toIndentedString(issuesUrl)).append("\n");
    sb.append("    membersUrl: ").append(toIndentedString(membersUrl)).append("\n");
    sb.append("    publicMembersUrl: ").append(toIndentedString(publicMembersUrl)).append("\n");
    sb.append("    avatarUrl: ").append(toIndentedString(avatarUrl)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
