/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * OrgsOrgBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class OrgsOrgBody {
  @JsonProperty("billing_email")
  private Object billingEmail = null;

  @JsonProperty("company")
  private Object company = null;

  @JsonProperty("email")
  private Object email = null;

  @JsonProperty("twitter_username")
  private Object twitterUsername = null;

  @JsonProperty("location")
  private Object location = null;

  @JsonProperty("name")
  private Object name = null;

  @JsonProperty("description")
  private Object description = null;

  @JsonProperty("has_organization_projects")
  private Object hasOrganizationProjects = null;

  @JsonProperty("has_repository_projects")
  private Object hasRepositoryProjects = null;

  @JsonProperty("default_repository_permission")
  private Object defaultRepositoryPermission = read;

  @JsonProperty("members_can_create_repositories")
  private Object membersCanCreateRepositories = true;

  @JsonProperty("members_can_create_internal_repositories")
  private Object membersCanCreateInternalRepositories = null;

  @JsonProperty("members_can_create_private_repositories")
  private Object membersCanCreatePrivateRepositories = null;

  @JsonProperty("members_can_create_public_repositories")
  private Object membersCanCreatePublicRepositories = null;

  @JsonProperty("members_allowed_repository_creation_type")
  private Object membersAllowedRepositoryCreationType = null;

  @JsonProperty("members_can_create_pages")
  private Object membersCanCreatePages = true;

  @JsonProperty("members_can_create_public_pages")
  private Object membersCanCreatePublicPages = true;

  @JsonProperty("members_can_create_private_pages")
  private Object membersCanCreatePrivatePages = true;

  @JsonProperty("members_can_fork_private_repositories")
  private Object membersCanForkPrivateRepositories = false;

  @JsonProperty("web_commit_signoff_required")
  private Object webCommitSignoffRequired = false;

  @JsonProperty("blog")
  private Object blog = null;

  @JsonProperty("advanced_security_enabled_for_new_repositories")
  private Object advancedSecurityEnabledForNewRepositories = null;

  @JsonProperty("dependabot_alerts_enabled_for_new_repositories")
  private Object dependabotAlertsEnabledForNewRepositories = null;

  @JsonProperty("dependabot_security_updates_enabled_for_new_repositories")
  private Object dependabotSecurityUpdatesEnabledForNewRepositories = null;

  @JsonProperty("dependency_graph_enabled_for_new_repositories")
  private Object dependencyGraphEnabledForNewRepositories = null;

  @JsonProperty("secret_scanning_enabled_for_new_repositories")
  private Object secretScanningEnabledForNewRepositories = null;

  @JsonProperty("secret_scanning_push_protection_enabled_for_new_repositories")
  private Object secretScanningPushProtectionEnabledForNewRepositories = null;

  public OrgsOrgBody billingEmail(Object billingEmail) {
    this.billingEmail = billingEmail;
    return this;
  }

   /**
   * Billing email address. This address is not publicized.
   * @return billingEmail
  **/
  public Object getBillingEmail() {
    return billingEmail;
  }

  public void setBillingEmail(Object billingEmail) {
    this.billingEmail = billingEmail;
  }

  public OrgsOrgBody company(Object company) {
    this.company = company;
    return this;
  }

   /**
   * The company name.
   * @return company
  **/
  public Object getCompany() {
    return company;
  }

  public void setCompany(Object company) {
    this.company = company;
  }

  public OrgsOrgBody email(Object email) {
    this.email = email;
    return this;
  }

   /**
   * The publicly visible email address.
   * @return email
  **/
  public Object getEmail() {
    return email;
  }

  public void setEmail(Object email) {
    this.email = email;
  }

  public OrgsOrgBody twitterUsername(Object twitterUsername) {
    this.twitterUsername = twitterUsername;
    return this;
  }

   /**
   * The Twitter username of the company.
   * @return twitterUsername
  **/
  public Object getTwitterUsername() {
    return twitterUsername;
  }

  public void setTwitterUsername(Object twitterUsername) {
    this.twitterUsername = twitterUsername;
  }

  public OrgsOrgBody location(Object location) {
    this.location = location;
    return this;
  }

   /**
   * The location.
   * @return location
  **/
  public Object getLocation() {
    return location;
  }

  public void setLocation(Object location) {
    this.location = location;
  }

  public OrgsOrgBody name(Object name) {
    this.name = name;
    return this;
  }

   /**
   * The shorthand name of the company.
   * @return name
  **/
  public Object getName() {
    return name;
  }

  public void setName(Object name) {
    this.name = name;
  }

  public OrgsOrgBody description(Object description) {
    this.description = description;
    return this;
  }

   /**
   * The description of the company.
   * @return description
  **/
  public Object getDescription() {
    return description;
  }

  public void setDescription(Object description) {
    this.description = description;
  }

  public OrgsOrgBody hasOrganizationProjects(Object hasOrganizationProjects) {
    this.hasOrganizationProjects = hasOrganizationProjects;
    return this;
  }

   /**
   * Whether an organization can use organization projects.
   * @return hasOrganizationProjects
  **/
  public Object getHasOrganizationProjects() {
    return hasOrganizationProjects;
  }

  public void setHasOrganizationProjects(Object hasOrganizationProjects) {
    this.hasOrganizationProjects = hasOrganizationProjects;
  }

  public OrgsOrgBody hasRepositoryProjects(Object hasRepositoryProjects) {
    this.hasRepositoryProjects = hasRepositoryProjects;
    return this;
  }

   /**
   * Whether repositories that belong to the organization can use repository projects.
   * @return hasRepositoryProjects
  **/
  public Object getHasRepositoryProjects() {
    return hasRepositoryProjects;
  }

  public void setHasRepositoryProjects(Object hasRepositoryProjects) {
    this.hasRepositoryProjects = hasRepositoryProjects;
  }

  public OrgsOrgBody defaultRepositoryPermission(Object defaultRepositoryPermission) {
    this.defaultRepositoryPermission = defaultRepositoryPermission;
    return this;
  }

   /**
   * Default permission level members have for organization repositories.
   * @return defaultRepositoryPermission
  **/
  public Object getDefaultRepositoryPermission() {
    return defaultRepositoryPermission;
  }

  public void setDefaultRepositoryPermission(Object defaultRepositoryPermission) {
    this.defaultRepositoryPermission = defaultRepositoryPermission;
  }

  public OrgsOrgBody membersCanCreateRepositories(Object membersCanCreateRepositories) {
    this.membersCanCreateRepositories = membersCanCreateRepositories;
    return this;
  }

   /**
   * Whether of non-admin organization members can create repositories. **Note:** A parameter can override this parameter. See &#x60;members_allowed_repository_creation_type&#x60; in this table for details.
   * @return membersCanCreateRepositories
  **/
  public Object getMembersCanCreateRepositories() {
    return membersCanCreateRepositories;
  }

  public void setMembersCanCreateRepositories(Object membersCanCreateRepositories) {
    this.membersCanCreateRepositories = membersCanCreateRepositories;
  }

  public OrgsOrgBody membersCanCreateInternalRepositories(Object membersCanCreateInternalRepositories) {
    this.membersCanCreateInternalRepositories = membersCanCreateInternalRepositories;
    return this;
  }

   /**
   * Whether organization members can create internal repositories, which are visible to all enterprise members. You can only allow members to create internal repositories if your organization is associated with an enterprise account using GitHub Enterprise Cloud or GitHub Enterprise Server 2.20+. For more information, see \&quot;[Restricting repository creation in your organization](https://docs.github.com/github/setting-up-and-managing-organizations-and-teams/restricting-repository-creation-in-your-organization)\&quot; in the GitHub Help documentation.
   * @return membersCanCreateInternalRepositories
  **/
  public Object getMembersCanCreateInternalRepositories() {
    return membersCanCreateInternalRepositories;
  }

  public void setMembersCanCreateInternalRepositories(Object membersCanCreateInternalRepositories) {
    this.membersCanCreateInternalRepositories = membersCanCreateInternalRepositories;
  }

  public OrgsOrgBody membersCanCreatePrivateRepositories(Object membersCanCreatePrivateRepositories) {
    this.membersCanCreatePrivateRepositories = membersCanCreatePrivateRepositories;
    return this;
  }

   /**
   * Whether organization members can create private repositories, which are visible to organization members with permission. For more information, see \&quot;[Restricting repository creation in your organization](https://docs.github.com/github/setting-up-and-managing-organizations-and-teams/restricting-repository-creation-in-your-organization)\&quot; in the GitHub Help documentation.
   * @return membersCanCreatePrivateRepositories
  **/
  public Object getMembersCanCreatePrivateRepositories() {
    return membersCanCreatePrivateRepositories;
  }

  public void setMembersCanCreatePrivateRepositories(Object membersCanCreatePrivateRepositories) {
    this.membersCanCreatePrivateRepositories = membersCanCreatePrivateRepositories;
  }

  public OrgsOrgBody membersCanCreatePublicRepositories(Object membersCanCreatePublicRepositories) {
    this.membersCanCreatePublicRepositories = membersCanCreatePublicRepositories;
    return this;
  }

   /**
   * Whether organization members can create public repositories, which are visible to anyone. For more information, see \&quot;[Restricting repository creation in your organization](https://docs.github.com/github/setting-up-and-managing-organizations-and-teams/restricting-repository-creation-in-your-organization)\&quot; in the GitHub Help documentation.
   * @return membersCanCreatePublicRepositories
  **/
  public Object getMembersCanCreatePublicRepositories() {
    return membersCanCreatePublicRepositories;
  }

  public void setMembersCanCreatePublicRepositories(Object membersCanCreatePublicRepositories) {
    this.membersCanCreatePublicRepositories = membersCanCreatePublicRepositories;
  }

  public OrgsOrgBody membersAllowedRepositoryCreationType(Object membersAllowedRepositoryCreationType) {
    this.membersAllowedRepositoryCreationType = membersAllowedRepositoryCreationType;
    return this;
  }

   /**
   * Specifies which types of repositories non-admin organization members can create. &#x60;private&#x60; is only available to repositories that are part of an organization on GitHub Enterprise Cloud.  **Note:** This parameter is deprecated and will be removed in the future. Its return value ignores internal repositories. Using this parameter overrides values set in &#x60;members_can_create_repositories&#x60;. See the parameter deprecation notice in the operation description for details.
   * @return membersAllowedRepositoryCreationType
  **/
  public Object getMembersAllowedRepositoryCreationType() {
    return membersAllowedRepositoryCreationType;
  }

  public void setMembersAllowedRepositoryCreationType(Object membersAllowedRepositoryCreationType) {
    this.membersAllowedRepositoryCreationType = membersAllowedRepositoryCreationType;
  }

  public OrgsOrgBody membersCanCreatePages(Object membersCanCreatePages) {
    this.membersCanCreatePages = membersCanCreatePages;
    return this;
  }

   /**
   * Whether organization members can create GitHub Pages sites. Existing published sites will not be impacted.
   * @return membersCanCreatePages
  **/
  public Object getMembersCanCreatePages() {
    return membersCanCreatePages;
  }

  public void setMembersCanCreatePages(Object membersCanCreatePages) {
    this.membersCanCreatePages = membersCanCreatePages;
  }

  public OrgsOrgBody membersCanCreatePublicPages(Object membersCanCreatePublicPages) {
    this.membersCanCreatePublicPages = membersCanCreatePublicPages;
    return this;
  }

   /**
   * Whether organization members can create public GitHub Pages sites. Existing published sites will not be impacted.
   * @return membersCanCreatePublicPages
  **/
  public Object getMembersCanCreatePublicPages() {
    return membersCanCreatePublicPages;
  }

  public void setMembersCanCreatePublicPages(Object membersCanCreatePublicPages) {
    this.membersCanCreatePublicPages = membersCanCreatePublicPages;
  }

  public OrgsOrgBody membersCanCreatePrivatePages(Object membersCanCreatePrivatePages) {
    this.membersCanCreatePrivatePages = membersCanCreatePrivatePages;
    return this;
  }

   /**
   * Whether organization members can create private GitHub Pages sites. Existing published sites will not be impacted.
   * @return membersCanCreatePrivatePages
  **/
  public Object getMembersCanCreatePrivatePages() {
    return membersCanCreatePrivatePages;
  }

  public void setMembersCanCreatePrivatePages(Object membersCanCreatePrivatePages) {
    this.membersCanCreatePrivatePages = membersCanCreatePrivatePages;
  }

  public OrgsOrgBody membersCanForkPrivateRepositories(Object membersCanForkPrivateRepositories) {
    this.membersCanForkPrivateRepositories = membersCanForkPrivateRepositories;
    return this;
  }

   /**
   * Whether organization members can fork private organization repositories.
   * @return membersCanForkPrivateRepositories
  **/
  public Object getMembersCanForkPrivateRepositories() {
    return membersCanForkPrivateRepositories;
  }

  public void setMembersCanForkPrivateRepositories(Object membersCanForkPrivateRepositories) {
    this.membersCanForkPrivateRepositories = membersCanForkPrivateRepositories;
  }

  public OrgsOrgBody webCommitSignoffRequired(Object webCommitSignoffRequired) {
    this.webCommitSignoffRequired = webCommitSignoffRequired;
    return this;
  }

   /**
   * Whether contributors to organization repositories are required to sign off on commits they make through GitHub&#x27;s web interface.
   * @return webCommitSignoffRequired
  **/
  public Object getWebCommitSignoffRequired() {
    return webCommitSignoffRequired;
  }

  public void setWebCommitSignoffRequired(Object webCommitSignoffRequired) {
    this.webCommitSignoffRequired = webCommitSignoffRequired;
  }

  public OrgsOrgBody blog(Object blog) {
    this.blog = blog;
    return this;
  }

   /**
   * Get blog
   * @return blog
  **/
  public Object getBlog() {
    return blog;
  }

  public void setBlog(Object blog) {
    this.blog = blog;
  }

  public OrgsOrgBody advancedSecurityEnabledForNewRepositories(Object advancedSecurityEnabledForNewRepositories) {
    this.advancedSecurityEnabledForNewRepositories = advancedSecurityEnabledForNewRepositories;
    return this;
  }

   /**
   * Whether GitHub Advanced Security is automatically enabled for new repositories.  To use this parameter, you must have admin permissions for the repository or be an owner or security manager for the organization that owns the repository. For more information, see \&quot;[Managing security managers in your organization](https://docs.github.com/organizations/managing-peoples-access-to-your-organization-with-roles/managing-security-managers-in-your-organization).\&quot;  You can check which security and analysis features are currently enabled by using a &#x60;GET /orgs/{org}&#x60; request.
   * @return advancedSecurityEnabledForNewRepositories
  **/
  public Object getAdvancedSecurityEnabledForNewRepositories() {
    return advancedSecurityEnabledForNewRepositories;
  }

  public void setAdvancedSecurityEnabledForNewRepositories(Object advancedSecurityEnabledForNewRepositories) {
    this.advancedSecurityEnabledForNewRepositories = advancedSecurityEnabledForNewRepositories;
  }

  public OrgsOrgBody dependabotAlertsEnabledForNewRepositories(Object dependabotAlertsEnabledForNewRepositories) {
    this.dependabotAlertsEnabledForNewRepositories = dependabotAlertsEnabledForNewRepositories;
    return this;
  }

   /**
   * Whether Dependabot alerts is automatically enabled for new repositories.  To use this parameter, you must have admin permissions for the repository or be an owner or security manager for the organization that owns the repository. For more information, see \&quot;[Managing security managers in your organization](https://docs.github.com/organizations/managing-peoples-access-to-your-organization-with-roles/managing-security-managers-in-your-organization).\&quot;  You can check which security and analysis features are currently enabled by using a &#x60;GET /orgs/{org}&#x60; request.
   * @return dependabotAlertsEnabledForNewRepositories
  **/
  public Object getDependabotAlertsEnabledForNewRepositories() {
    return dependabotAlertsEnabledForNewRepositories;
  }

  public void setDependabotAlertsEnabledForNewRepositories(Object dependabotAlertsEnabledForNewRepositories) {
    this.dependabotAlertsEnabledForNewRepositories = dependabotAlertsEnabledForNewRepositories;
  }

  public OrgsOrgBody dependabotSecurityUpdatesEnabledForNewRepositories(Object dependabotSecurityUpdatesEnabledForNewRepositories) {
    this.dependabotSecurityUpdatesEnabledForNewRepositories = dependabotSecurityUpdatesEnabledForNewRepositories;
    return this;
  }

   /**
   * Whether Dependabot security updates is automatically enabled for new repositories.  To use this parameter, you must have admin permissions for the repository or be an owner or security manager for the organization that owns the repository. For more information, see \&quot;[Managing security managers in your organization](https://docs.github.com/organizations/managing-peoples-access-to-your-organization-with-roles/managing-security-managers-in-your-organization).\&quot;  You can check which security and analysis features are currently enabled by using a &#x60;GET /orgs/{org}&#x60; request.
   * @return dependabotSecurityUpdatesEnabledForNewRepositories
  **/
  public Object getDependabotSecurityUpdatesEnabledForNewRepositories() {
    return dependabotSecurityUpdatesEnabledForNewRepositories;
  }

  public void setDependabotSecurityUpdatesEnabledForNewRepositories(Object dependabotSecurityUpdatesEnabledForNewRepositories) {
    this.dependabotSecurityUpdatesEnabledForNewRepositories = dependabotSecurityUpdatesEnabledForNewRepositories;
  }

  public OrgsOrgBody dependencyGraphEnabledForNewRepositories(Object dependencyGraphEnabledForNewRepositories) {
    this.dependencyGraphEnabledForNewRepositories = dependencyGraphEnabledForNewRepositories;
    return this;
  }

   /**
   * Whether dependency graph is automatically enabled for new repositories.  To use this parameter, you must have admin permissions for the repository or be an owner or security manager for the organization that owns the repository. For more information, see \&quot;[Managing security managers in your organization](https://docs.github.com/organizations/managing-peoples-access-to-your-organization-with-roles/managing-security-managers-in-your-organization).\&quot;  You can check which security and analysis features are currently enabled by using a &#x60;GET /orgs/{org}&#x60; request.
   * @return dependencyGraphEnabledForNewRepositories
  **/
  public Object getDependencyGraphEnabledForNewRepositories() {
    return dependencyGraphEnabledForNewRepositories;
  }

  public void setDependencyGraphEnabledForNewRepositories(Object dependencyGraphEnabledForNewRepositories) {
    this.dependencyGraphEnabledForNewRepositories = dependencyGraphEnabledForNewRepositories;
  }

  public OrgsOrgBody secretScanningEnabledForNewRepositories(Object secretScanningEnabledForNewRepositories) {
    this.secretScanningEnabledForNewRepositories = secretScanningEnabledForNewRepositories;
    return this;
  }

   /**
   * Whether secret scanning is automatically enabled for new repositories.  To use this parameter, you must have admin permissions for the repository or be an owner or security manager for the organization that owns the repository. For more information, see \&quot;[Managing security managers in your organization](https://docs.github.com/organizations/managing-peoples-access-to-your-organization-with-roles/managing-security-managers-in-your-organization).\&quot;  You can check which security and analysis features are currently enabled by using a &#x60;GET /orgs/{org}&#x60; request.
   * @return secretScanningEnabledForNewRepositories
  **/
  public Object getSecretScanningEnabledForNewRepositories() {
    return secretScanningEnabledForNewRepositories;
  }

  public void setSecretScanningEnabledForNewRepositories(Object secretScanningEnabledForNewRepositories) {
    this.secretScanningEnabledForNewRepositories = secretScanningEnabledForNewRepositories;
  }

  public OrgsOrgBody secretScanningPushProtectionEnabledForNewRepositories(Object secretScanningPushProtectionEnabledForNewRepositories) {
    this.secretScanningPushProtectionEnabledForNewRepositories = secretScanningPushProtectionEnabledForNewRepositories;
    return this;
  }

   /**
   * Whether secret scanning push protection is automatically enabled for new repositories.  To use this parameter, you must have admin permissions for the repository or be an owner or security manager for the organization that owns the repository. For more information, see \&quot;[Managing security managers in your organization](https://docs.github.com/organizations/managing-peoples-access-to-your-organization-with-roles/managing-security-managers-in-your-organization).\&quot;  You can check which security and analysis features are currently enabled by using a &#x60;GET /orgs/{org}&#x60; request.
   * @return secretScanningPushProtectionEnabledForNewRepositories
  **/
  public Object getSecretScanningPushProtectionEnabledForNewRepositories() {
    return secretScanningPushProtectionEnabledForNewRepositories;
  }

  public void setSecretScanningPushProtectionEnabledForNewRepositories(Object secretScanningPushProtectionEnabledForNewRepositories) {
    this.secretScanningPushProtectionEnabledForNewRepositories = secretScanningPushProtectionEnabledForNewRepositories;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrgsOrgBody orgsOrgBody = (OrgsOrgBody) o;
    return Objects.equals(this.billingEmail, orgsOrgBody.billingEmail) &&
        Objects.equals(this.company, orgsOrgBody.company) &&
        Objects.equals(this.email, orgsOrgBody.email) &&
        Objects.equals(this.twitterUsername, orgsOrgBody.twitterUsername) &&
        Objects.equals(this.location, orgsOrgBody.location) &&
        Objects.equals(this.name, orgsOrgBody.name) &&
        Objects.equals(this.description, orgsOrgBody.description) &&
        Objects.equals(this.hasOrganizationProjects, orgsOrgBody.hasOrganizationProjects) &&
        Objects.equals(this.hasRepositoryProjects, orgsOrgBody.hasRepositoryProjects) &&
        Objects.equals(this.defaultRepositoryPermission, orgsOrgBody.defaultRepositoryPermission) &&
        Objects.equals(this.membersCanCreateRepositories, orgsOrgBody.membersCanCreateRepositories) &&
        Objects.equals(this.membersCanCreateInternalRepositories, orgsOrgBody.membersCanCreateInternalRepositories) &&
        Objects.equals(this.membersCanCreatePrivateRepositories, orgsOrgBody.membersCanCreatePrivateRepositories) &&
        Objects.equals(this.membersCanCreatePublicRepositories, orgsOrgBody.membersCanCreatePublicRepositories) &&
        Objects.equals(this.membersAllowedRepositoryCreationType, orgsOrgBody.membersAllowedRepositoryCreationType) &&
        Objects.equals(this.membersCanCreatePages, orgsOrgBody.membersCanCreatePages) &&
        Objects.equals(this.membersCanCreatePublicPages, orgsOrgBody.membersCanCreatePublicPages) &&
        Objects.equals(this.membersCanCreatePrivatePages, orgsOrgBody.membersCanCreatePrivatePages) &&
        Objects.equals(this.membersCanForkPrivateRepositories, orgsOrgBody.membersCanForkPrivateRepositories) &&
        Objects.equals(this.webCommitSignoffRequired, orgsOrgBody.webCommitSignoffRequired) &&
        Objects.equals(this.blog, orgsOrgBody.blog) &&
        Objects.equals(this.advancedSecurityEnabledForNewRepositories, orgsOrgBody.advancedSecurityEnabledForNewRepositories) &&
        Objects.equals(this.dependabotAlertsEnabledForNewRepositories, orgsOrgBody.dependabotAlertsEnabledForNewRepositories) &&
        Objects.equals(this.dependabotSecurityUpdatesEnabledForNewRepositories, orgsOrgBody.dependabotSecurityUpdatesEnabledForNewRepositories) &&
        Objects.equals(this.dependencyGraphEnabledForNewRepositories, orgsOrgBody.dependencyGraphEnabledForNewRepositories) &&
        Objects.equals(this.secretScanningEnabledForNewRepositories, orgsOrgBody.secretScanningEnabledForNewRepositories) &&
        Objects.equals(this.secretScanningPushProtectionEnabledForNewRepositories, orgsOrgBody.secretScanningPushProtectionEnabledForNewRepositories);
  }

  @Override
  public int hashCode() {
    return Objects.hash(billingEmail, company, email, twitterUsername, location, name, description, hasOrganizationProjects, hasRepositoryProjects, defaultRepositoryPermission, membersCanCreateRepositories, membersCanCreateInternalRepositories, membersCanCreatePrivateRepositories, membersCanCreatePublicRepositories, membersAllowedRepositoryCreationType, membersCanCreatePages, membersCanCreatePublicPages, membersCanCreatePrivatePages, membersCanForkPrivateRepositories, webCommitSignoffRequired, blog, advancedSecurityEnabledForNewRepositories, dependabotAlertsEnabledForNewRepositories, dependabotSecurityUpdatesEnabledForNewRepositories, dependencyGraphEnabledForNewRepositories, secretScanningEnabledForNewRepositories, secretScanningPushProtectionEnabledForNewRepositories);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrgsOrgBody {\n");
    
    sb.append("    billingEmail: ").append(toIndentedString(billingEmail)).append("\n");
    sb.append("    company: ").append(toIndentedString(company)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    twitterUsername: ").append(toIndentedString(twitterUsername)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    hasOrganizationProjects: ").append(toIndentedString(hasOrganizationProjects)).append("\n");
    sb.append("    hasRepositoryProjects: ").append(toIndentedString(hasRepositoryProjects)).append("\n");
    sb.append("    defaultRepositoryPermission: ").append(toIndentedString(defaultRepositoryPermission)).append("\n");
    sb.append("    membersCanCreateRepositories: ").append(toIndentedString(membersCanCreateRepositories)).append("\n");
    sb.append("    membersCanCreateInternalRepositories: ").append(toIndentedString(membersCanCreateInternalRepositories)).append("\n");
    sb.append("    membersCanCreatePrivateRepositories: ").append(toIndentedString(membersCanCreatePrivateRepositories)).append("\n");
    sb.append("    membersCanCreatePublicRepositories: ").append(toIndentedString(membersCanCreatePublicRepositories)).append("\n");
    sb.append("    membersAllowedRepositoryCreationType: ").append(toIndentedString(membersAllowedRepositoryCreationType)).append("\n");
    sb.append("    membersCanCreatePages: ").append(toIndentedString(membersCanCreatePages)).append("\n");
    sb.append("    membersCanCreatePublicPages: ").append(toIndentedString(membersCanCreatePublicPages)).append("\n");
    sb.append("    membersCanCreatePrivatePages: ").append(toIndentedString(membersCanCreatePrivatePages)).append("\n");
    sb.append("    membersCanForkPrivateRepositories: ").append(toIndentedString(membersCanForkPrivateRepositories)).append("\n");
    sb.append("    webCommitSignoffRequired: ").append(toIndentedString(webCommitSignoffRequired)).append("\n");
    sb.append("    blog: ").append(toIndentedString(blog)).append("\n");
    sb.append("    advancedSecurityEnabledForNewRepositories: ").append(toIndentedString(advancedSecurityEnabledForNewRepositories)).append("\n");
    sb.append("    dependabotAlertsEnabledForNewRepositories: ").append(toIndentedString(dependabotAlertsEnabledForNewRepositories)).append("\n");
    sb.append("    dependabotSecurityUpdatesEnabledForNewRepositories: ").append(toIndentedString(dependabotSecurityUpdatesEnabledForNewRepositories)).append("\n");
    sb.append("    dependencyGraphEnabledForNewRepositories: ").append(toIndentedString(dependencyGraphEnabledForNewRepositories)).append("\n");
    sb.append("    secretScanningEnabledForNewRepositories: ").append(toIndentedString(secretScanningEnabledForNewRepositories)).append("\n");
    sb.append("    secretScanningPushProtectionEnabledForNewRepositories: ").append(toIndentedString(secretScanningPushProtectionEnabledForNewRepositories)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
