/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * OwnerRepoBody2
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class OwnerRepoBody2 {
  @JsonProperty("permission")
  private Object permission = null;

  public OwnerRepoBody2 permission(Object permission) {
    this.permission = permission;
    return this;
  }

   /**
   * The permission to grant the team on this repository. If no permission is specified, the team&#x27;s &#x60;permission&#x60; attribute will be used to determine what permission to grant the team on this repository.
   * @return permission
  **/
  public Object getPermission() {
    return permission;
  }

  public void setPermission(Object permission) {
    this.permission = permission;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OwnerRepoBody2 ownerRepoBody2 = (OwnerRepoBody2) o;
    return Objects.equals(this.permission, ownerRepoBody2.permission);
  }

  @Override
  public int hashCode() {
    return Objects.hash(permission);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OwnerRepoBody2 {\n");
    
    sb.append("    permission: ").append(toIndentedString(permission)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
