/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.github.api.client.PackageVersionMetadata;

/**
 * A version of a software package
 */
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class PackageVersion {
  @JsonProperty("id")
  private Object id = null;

  @JsonProperty("name")
  private Object name = null;

  @JsonProperty("url")
  private Object url = null;

  @JsonProperty("package_html_url")
  private Object packageHtmlUrl = null;

  @JsonProperty("html_url")
  private Object htmlUrl = null;

  @JsonProperty("license")
  private Object license = null;

  @JsonProperty("description")
  private Object description = null;

  @JsonProperty("created_at")
  private Object createdAt = null;

  @JsonProperty("updated_at")
  private Object updatedAt = null;

  @JsonProperty("deleted_at")
  private Object deletedAt = null;

  @JsonProperty("metadata")
  private PackageVersionMetadata metadata = null;

  public PackageVersion id(Object id) {
    this.id = id;
    return this;
  }

   /**
   * Unique identifier of the package version.
   * @return id
  **/
  public Object getId() {
    return id;
  }

  public void setId(Object id) {
    this.id = id;
  }

  public PackageVersion name(Object name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the package version.
   * @return name
  **/
  public Object getName() {
    return name;
  }

  public void setName(Object name) {
    this.name = name;
  }

  public PackageVersion url(Object url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  public Object getUrl() {
    return url;
  }

  public void setUrl(Object url) {
    this.url = url;
  }

  public PackageVersion packageHtmlUrl(Object packageHtmlUrl) {
    this.packageHtmlUrl = packageHtmlUrl;
    return this;
  }

   /**
   * Get packageHtmlUrl
   * @return packageHtmlUrl
  **/
  public Object getPackageHtmlUrl() {
    return packageHtmlUrl;
  }

  public void setPackageHtmlUrl(Object packageHtmlUrl) {
    this.packageHtmlUrl = packageHtmlUrl;
  }

  public PackageVersion htmlUrl(Object htmlUrl) {
    this.htmlUrl = htmlUrl;
    return this;
  }

   /**
   * Get htmlUrl
   * @return htmlUrl
  **/
  public Object getHtmlUrl() {
    return htmlUrl;
  }

  public void setHtmlUrl(Object htmlUrl) {
    this.htmlUrl = htmlUrl;
  }

  public PackageVersion license(Object license) {
    this.license = license;
    return this;
  }

   /**
   * Get license
   * @return license
  **/
  public Object getLicense() {
    return license;
  }

  public void setLicense(Object license) {
    this.license = license;
  }

  public PackageVersion description(Object description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  public Object getDescription() {
    return description;
  }

  public void setDescription(Object description) {
    this.description = description;
  }

  public PackageVersion createdAt(Object createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  public Object getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(Object createdAt) {
    this.createdAt = createdAt;
  }

  public PackageVersion updatedAt(Object updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  public Object getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(Object updatedAt) {
    this.updatedAt = updatedAt;
  }

  public PackageVersion deletedAt(Object deletedAt) {
    this.deletedAt = deletedAt;
    return this;
  }

   /**
   * Get deletedAt
   * @return deletedAt
  **/
  public Object getDeletedAt() {
    return deletedAt;
  }

  public void setDeletedAt(Object deletedAt) {
    this.deletedAt = deletedAt;
  }

  public PackageVersion metadata(PackageVersionMetadata metadata) {
    this.metadata = metadata;
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  public PackageVersionMetadata getMetadata() {
    return metadata;
  }

  public void setMetadata(PackageVersionMetadata metadata) {
    this.metadata = metadata;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PackageVersion packageVersion = (PackageVersion) o;
    return Objects.equals(this.id, packageVersion.id) &&
        Objects.equals(this.name, packageVersion.name) &&
        Objects.equals(this.url, packageVersion.url) &&
        Objects.equals(this.packageHtmlUrl, packageVersion.packageHtmlUrl) &&
        Objects.equals(this.htmlUrl, packageVersion.htmlUrl) &&
        Objects.equals(this.license, packageVersion.license) &&
        Objects.equals(this.description, packageVersion.description) &&
        Objects.equals(this.createdAt, packageVersion.createdAt) &&
        Objects.equals(this.updatedAt, packageVersion.updatedAt) &&
        Objects.equals(this.deletedAt, packageVersion.deletedAt) &&
        Objects.equals(this.metadata, packageVersion.metadata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, url, packageHtmlUrl, htmlUrl, license, description, createdAt, updatedAt, deletedAt, metadata);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PackageVersion {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    packageHtmlUrl: ").append(toIndentedString(packageHtmlUrl)).append("\n");
    sb.append("    htmlUrl: ").append(toIndentedString(htmlUrl)).append("\n");
    sb.append("    license: ").append(toIndentedString(license)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    deletedAt: ").append(toIndentedString(deletedAt)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
