/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * PendingdeploymentEnvironment
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class PendingdeploymentEnvironment {
  @JsonProperty("id")
  private Object id = null;

  @JsonProperty("node_id")
  private Object nodeId = null;

  @JsonProperty("name")
  private Object name = null;

  @JsonProperty("url")
  private Object url = null;

  @JsonProperty("html_url")
  private Object htmlUrl = null;

  public PendingdeploymentEnvironment id(Object id) {
    this.id = id;
    return this;
  }

   /**
   * The id of the environment.
   * @return id
  **/
  public Object getId() {
    return id;
  }

  public void setId(Object id) {
    this.id = id;
  }

  public PendingdeploymentEnvironment nodeId(Object nodeId) {
    this.nodeId = nodeId;
    return this;
  }

   /**
   * Get nodeId
   * @return nodeId
  **/
  public Object getNodeId() {
    return nodeId;
  }

  public void setNodeId(Object nodeId) {
    this.nodeId = nodeId;
  }

  public PendingdeploymentEnvironment name(Object name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the environment.
   * @return name
  **/
  public Object getName() {
    return name;
  }

  public void setName(Object name) {
    this.name = name;
  }

  public PendingdeploymentEnvironment url(Object url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  public Object getUrl() {
    return url;
  }

  public void setUrl(Object url) {
    this.url = url;
  }

  public PendingdeploymentEnvironment htmlUrl(Object htmlUrl) {
    this.htmlUrl = htmlUrl;
    return this;
  }

   /**
   * Get htmlUrl
   * @return htmlUrl
  **/
  public Object getHtmlUrl() {
    return htmlUrl;
  }

  public void setHtmlUrl(Object htmlUrl) {
    this.htmlUrl = htmlUrl;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PendingdeploymentEnvironment pendingdeploymentEnvironment = (PendingdeploymentEnvironment) o;
    return Objects.equals(this.id, pendingdeploymentEnvironment.id) &&
        Objects.equals(this.nodeId, pendingdeploymentEnvironment.nodeId) &&
        Objects.equals(this.name, pendingdeploymentEnvironment.name) &&
        Objects.equals(this.url, pendingdeploymentEnvironment.url) &&
        Objects.equals(this.htmlUrl, pendingdeploymentEnvironment.htmlUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, nodeId, name, url, htmlUrl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PendingdeploymentEnvironment {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    nodeId: ").append(toIndentedString(nodeId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    htmlUrl: ").append(toIndentedString(htmlUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
