/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * The type of content tracked in a project item
 */
public enum ProjectsV2ItemContentType {
  ISSUE("Issue"),
  PULLREQUEST("PullRequest"),
  DRAFTISSUE("DraftIssue");

  private Object value;

  ProjectsV2ItemContentType(Object value) {
    this.value = value;
  }

  @JsonValue
  public Object getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static ProjectsV2ItemContentType fromValue(Object input) {
    for (ProjectsV2ItemContentType b : ProjectsV2ItemContentType.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
