/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.github.api.client.User;

/**
 * Project
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class Project {
  @JsonProperty("body")
  private Object body = null;

  @JsonProperty("columns_url")
  private Object columnsUrl = null;

  @JsonProperty("created_at")
  private Object createdAt = null;

  @JsonProperty("creator")
  private User creator = null;

  @JsonProperty("html_url")
  private Object htmlUrl = null;

  @JsonProperty("id")
  private Object id = null;

  @JsonProperty("name")
  private Object name = null;

  @JsonProperty("node_id")
  private Object nodeId = null;

  @JsonProperty("number")
  private Object number = null;

  @JsonProperty("owner_url")
  private Object ownerUrl = null;

  @JsonProperty("state")
  private Object state = null;

  @JsonProperty("updated_at")
  private Object updatedAt = null;

  @JsonProperty("url")
  private Object url = null;

  public Project body(Object body) {
    this.body = body;
    return this;
  }

   /**
   * Body of the project
   * @return body
  **/
  public Object getBody() {
    return body;
  }

  public void setBody(Object body) {
    this.body = body;
  }

  public Project columnsUrl(Object columnsUrl) {
    this.columnsUrl = columnsUrl;
    return this;
  }

   /**
   * Get columnsUrl
   * @return columnsUrl
  **/
  public Object getColumnsUrl() {
    return columnsUrl;
  }

  public void setColumnsUrl(Object columnsUrl) {
    this.columnsUrl = columnsUrl;
  }

  public Project createdAt(Object createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  public Object getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(Object createdAt) {
    this.createdAt = createdAt;
  }

  public Project creator(User creator) {
    this.creator = creator;
    return this;
  }

   /**
   * Get creator
   * @return creator
  **/
  public User getCreator() {
    return creator;
  }

  public void setCreator(User creator) {
    this.creator = creator;
  }

  public Project htmlUrl(Object htmlUrl) {
    this.htmlUrl = htmlUrl;
    return this;
  }

   /**
   * Get htmlUrl
   * @return htmlUrl
  **/
  public Object getHtmlUrl() {
    return htmlUrl;
  }

  public void setHtmlUrl(Object htmlUrl) {
    this.htmlUrl = htmlUrl;
  }

  public Project id(Object id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Object getId() {
    return id;
  }

  public void setId(Object id) {
    this.id = id;
  }

  public Project name(Object name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the project
   * @return name
  **/
  public Object getName() {
    return name;
  }

  public void setName(Object name) {
    this.name = name;
  }

  public Project nodeId(Object nodeId) {
    this.nodeId = nodeId;
    return this;
  }

   /**
   * Get nodeId
   * @return nodeId
  **/
  public Object getNodeId() {
    return nodeId;
  }

  public void setNodeId(Object nodeId) {
    this.nodeId = nodeId;
  }

  public Project number(Object number) {
    this.number = number;
    return this;
  }

   /**
   * Get number
   * @return number
  **/
  public Object getNumber() {
    return number;
  }

  public void setNumber(Object number) {
    this.number = number;
  }

  public Project ownerUrl(Object ownerUrl) {
    this.ownerUrl = ownerUrl;
    return this;
  }

   /**
   * Get ownerUrl
   * @return ownerUrl
  **/
  public Object getOwnerUrl() {
    return ownerUrl;
  }

  public void setOwnerUrl(Object ownerUrl) {
    this.ownerUrl = ownerUrl;
  }

  public Project state(Object state) {
    this.state = state;
    return this;
  }

   /**
   * State of the project; either &#x27;open&#x27; or &#x27;closed&#x27;
   * @return state
  **/
  public Object getState() {
    return state;
  }

  public void setState(Object state) {
    this.state = state;
  }

  public Project updatedAt(Object updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  public Object getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(Object updatedAt) {
    this.updatedAt = updatedAt;
  }

  public Project url(Object url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  public Object getUrl() {
    return url;
  }

  public void setUrl(Object url) {
    this.url = url;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Project project = (Project) o;
    return Objects.equals(this.body, project.body) &&
        Objects.equals(this.columnsUrl, project.columnsUrl) &&
        Objects.equals(this.createdAt, project.createdAt) &&
        Objects.equals(this.creator, project.creator) &&
        Objects.equals(this.htmlUrl, project.htmlUrl) &&
        Objects.equals(this.id, project.id) &&
        Objects.equals(this.name, project.name) &&
        Objects.equals(this.nodeId, project.nodeId) &&
        Objects.equals(this.number, project.number) &&
        Objects.equals(this.ownerUrl, project.ownerUrl) &&
        Objects.equals(this.state, project.state) &&
        Objects.equals(this.updatedAt, project.updatedAt) &&
        Objects.equals(this.url, project.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(body, columnsUrl, createdAt, creator, htmlUrl, id, name, nodeId, number, ownerUrl, state, updatedAt, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Project {\n");
    
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("    columnsUrl: ").append(toIndentedString(columnsUrl)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    creator: ").append(toIndentedString(creator)).append("\n");
    sb.append("    htmlUrl: ").append(toIndentedString(htmlUrl)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    nodeId: ").append(toIndentedString(nodeId)).append("\n");
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    ownerUrl: ").append(toIndentedString(ownerUrl)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
