/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * ProtectedbranchRequiredPullRequestReviewsDismissalRestrictions
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class ProtectedbranchRequiredPullRequestReviewsDismissalRestrictions {
  @JsonProperty("url")
  private Object url = null;

  @JsonProperty("users_url")
  private Object usersUrl = null;

  @JsonProperty("teams_url")
  private Object teamsUrl = null;

  @JsonProperty("users")
  private Object users = null;

  @JsonProperty("teams")
  private Object teams = null;

  @JsonProperty("apps")
  private Object apps = null;

  public ProtectedbranchRequiredPullRequestReviewsDismissalRestrictions url(Object url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  public Object getUrl() {
    return url;
  }

  public void setUrl(Object url) {
    this.url = url;
  }

  public ProtectedbranchRequiredPullRequestReviewsDismissalRestrictions usersUrl(Object usersUrl) {
    this.usersUrl = usersUrl;
    return this;
  }

   /**
   * Get usersUrl
   * @return usersUrl
  **/
  public Object getUsersUrl() {
    return usersUrl;
  }

  public void setUsersUrl(Object usersUrl) {
    this.usersUrl = usersUrl;
  }

  public ProtectedbranchRequiredPullRequestReviewsDismissalRestrictions teamsUrl(Object teamsUrl) {
    this.teamsUrl = teamsUrl;
    return this;
  }

   /**
   * Get teamsUrl
   * @return teamsUrl
  **/
  public Object getTeamsUrl() {
    return teamsUrl;
  }

  public void setTeamsUrl(Object teamsUrl) {
    this.teamsUrl = teamsUrl;
  }

  public ProtectedbranchRequiredPullRequestReviewsDismissalRestrictions users(Object users) {
    this.users = users;
    return this;
  }

   /**
   * Get users
   * @return users
  **/
  public Object getUsers() {
    return users;
  }

  public void setUsers(Object users) {
    this.users = users;
  }

  public ProtectedbranchRequiredPullRequestReviewsDismissalRestrictions teams(Object teams) {
    this.teams = teams;
    return this;
  }

   /**
   * Get teams
   * @return teams
  **/
  public Object getTeams() {
    return teams;
  }

  public void setTeams(Object teams) {
    this.teams = teams;
  }

  public ProtectedbranchRequiredPullRequestReviewsDismissalRestrictions apps(Object apps) {
    this.apps = apps;
    return this;
  }

   /**
   * Get apps
   * @return apps
  **/
  public Object getApps() {
    return apps;
  }

  public void setApps(Object apps) {
    this.apps = apps;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProtectedbranchRequiredPullRequestReviewsDismissalRestrictions protectedbranchRequiredPullRequestReviewsDismissalRestrictions = (ProtectedbranchRequiredPullRequestReviewsDismissalRestrictions) o;
    return Objects.equals(this.url, protectedbranchRequiredPullRequestReviewsDismissalRestrictions.url) &&
        Objects.equals(this.usersUrl, protectedbranchRequiredPullRequestReviewsDismissalRestrictions.usersUrl) &&
        Objects.equals(this.teamsUrl, protectedbranchRequiredPullRequestReviewsDismissalRestrictions.teamsUrl) &&
        Objects.equals(this.users, protectedbranchRequiredPullRequestReviewsDismissalRestrictions.users) &&
        Objects.equals(this.teams, protectedbranchRequiredPullRequestReviewsDismissalRestrictions.teams) &&
        Objects.equals(this.apps, protectedbranchRequiredPullRequestReviewsDismissalRestrictions.apps);
  }

  @Override
  public int hashCode() {
    return Objects.hash(url, usersUrl, teamsUrl, users, teams, apps);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProtectedbranchRequiredPullRequestReviewsDismissalRestrictions {\n");
    
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    usersUrl: ").append(toIndentedString(usersUrl)).append("\n");
    sb.append("    teamsUrl: ").append(toIndentedString(teamsUrl)).append("\n");
    sb.append("    users: ").append(toIndentedString(users)).append("\n");
    sb.append("    teams: ").append(toIndentedString(teams)).append("\n");
    sb.append("    apps: ").append(toIndentedString(apps)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
