/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Data related to a release.
 */
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class ReleaseAsset {
  @JsonProperty("url")
  private Object url = null;

  @JsonProperty("browser_download_url")
  private Object browserDownloadUrl = null;

  @JsonProperty("id")
  private Object id = null;

  @JsonProperty("node_id")
  private Object nodeId = null;

  @JsonProperty("name")
  private Object name = null;

  @JsonProperty("label")
  private Object label = null;

  @JsonProperty("state")
  private Object state = null;

  @JsonProperty("content_type")
  private Object contentType = null;

  @JsonProperty("size")
  private Object size = null;

  @JsonProperty("download_count")
  private Object downloadCount = null;

  @JsonProperty("created_at")
  private Object createdAt = null;

  @JsonProperty("updated_at")
  private Object updatedAt = null;

  @JsonProperty("uploader")
  private Object uploader = null;

  public ReleaseAsset url(Object url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  public Object getUrl() {
    return url;
  }

  public void setUrl(Object url) {
    this.url = url;
  }

  public ReleaseAsset browserDownloadUrl(Object browserDownloadUrl) {
    this.browserDownloadUrl = browserDownloadUrl;
    return this;
  }

   /**
   * Get browserDownloadUrl
   * @return browserDownloadUrl
  **/
  public Object getBrowserDownloadUrl() {
    return browserDownloadUrl;
  }

  public void setBrowserDownloadUrl(Object browserDownloadUrl) {
    this.browserDownloadUrl = browserDownloadUrl;
  }

  public ReleaseAsset id(Object id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Object getId() {
    return id;
  }

  public void setId(Object id) {
    this.id = id;
  }

  public ReleaseAsset nodeId(Object nodeId) {
    this.nodeId = nodeId;
    return this;
  }

   /**
   * Get nodeId
   * @return nodeId
  **/
  public Object getNodeId() {
    return nodeId;
  }

  public void setNodeId(Object nodeId) {
    this.nodeId = nodeId;
  }

  public ReleaseAsset name(Object name) {
    this.name = name;
    return this;
  }

   /**
   * The file name of the asset.
   * @return name
  **/
  public Object getName() {
    return name;
  }

  public void setName(Object name) {
    this.name = name;
  }

  public ReleaseAsset label(Object label) {
    this.label = label;
    return this;
  }

   /**
   * Get label
   * @return label
  **/
  public Object getLabel() {
    return label;
  }

  public void setLabel(Object label) {
    this.label = label;
  }

  public ReleaseAsset state(Object state) {
    this.state = state;
    return this;
  }

   /**
   * State of the release asset.
   * @return state
  **/
  public Object getState() {
    return state;
  }

  public void setState(Object state) {
    this.state = state;
  }

  public ReleaseAsset contentType(Object contentType) {
    this.contentType = contentType;
    return this;
  }

   /**
   * Get contentType
   * @return contentType
  **/
  public Object getContentType() {
    return contentType;
  }

  public void setContentType(Object contentType) {
    this.contentType = contentType;
  }

  public ReleaseAsset size(Object size) {
    this.size = size;
    return this;
  }

   /**
   * Get size
   * @return size
  **/
  public Object getSize() {
    return size;
  }

  public void setSize(Object size) {
    this.size = size;
  }

  public ReleaseAsset downloadCount(Object downloadCount) {
    this.downloadCount = downloadCount;
    return this;
  }

   /**
   * Get downloadCount
   * @return downloadCount
  **/
  public Object getDownloadCount() {
    return downloadCount;
  }

  public void setDownloadCount(Object downloadCount) {
    this.downloadCount = downloadCount;
  }

  public ReleaseAsset createdAt(Object createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  public Object getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(Object createdAt) {
    this.createdAt = createdAt;
  }

  public ReleaseAsset updatedAt(Object updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  public Object getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(Object updatedAt) {
    this.updatedAt = updatedAt;
  }

  public ReleaseAsset uploader(Object uploader) {
    this.uploader = uploader;
    return this;
  }

   /**
   * Get uploader
   * @return uploader
  **/
  public Object getUploader() {
    return uploader;
  }

  public void setUploader(Object uploader) {
    this.uploader = uploader;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReleaseAsset releaseAsset = (ReleaseAsset) o;
    return Objects.equals(this.url, releaseAsset.url) &&
        Objects.equals(this.browserDownloadUrl, releaseAsset.browserDownloadUrl) &&
        Objects.equals(this.id, releaseAsset.id) &&
        Objects.equals(this.nodeId, releaseAsset.nodeId) &&
        Objects.equals(this.name, releaseAsset.name) &&
        Objects.equals(this.label, releaseAsset.label) &&
        Objects.equals(this.state, releaseAsset.state) &&
        Objects.equals(this.contentType, releaseAsset.contentType) &&
        Objects.equals(this.size, releaseAsset.size) &&
        Objects.equals(this.downloadCount, releaseAsset.downloadCount) &&
        Objects.equals(this.createdAt, releaseAsset.createdAt) &&
        Objects.equals(this.updatedAt, releaseAsset.updatedAt) &&
        Objects.equals(this.uploader, releaseAsset.uploader);
  }

  @Override
  public int hashCode() {
    return Objects.hash(url, browserDownloadUrl, id, nodeId, name, label, state, contentType, size, downloadCount, createdAt, updatedAt, uploader);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReleaseAsset {\n");
    
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    browserDownloadUrl: ").append(toIndentedString(browserDownloadUrl)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    nodeId: ").append(toIndentedString(nodeId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    contentType: ").append(toIndentedString(contentType)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    downloadCount: ").append(toIndentedString(downloadCount)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    uploader: ").append(toIndentedString(uploader)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
