/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * RepoLabelsBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class RepoLabelsBody {
  @JsonProperty("name")
  private Object name = null;

  @JsonProperty("color")
  private Object color = null;

  @JsonProperty("description")
  private Object description = null;

  public RepoLabelsBody name(Object name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the label. Emoji can be added to label names, using either native emoji or colon-style markup. For example, typing &#x60;:strawberry:&#x60; will render the emoji ![:strawberry:](https://github.githubassets.com/images/icons/emoji/unicode/1f353.png \&quot;:strawberry:\&quot;). For a full list of available emoji and codes, see \&quot;[Emoji cheat sheet](https://github.com/ikatyang/emoji-cheat-sheet).\&quot;
   * @return name
  **/
  public Object getName() {
    return name;
  }

  public void setName(Object name) {
    this.name = name;
  }

  public RepoLabelsBody color(Object color) {
    this.color = color;
    return this;
  }

   /**
   * The [hexadecimal color code](http://www.color-hex.com/) for the label, without the leading &#x60;#&#x60;.
   * @return color
  **/
  public Object getColor() {
    return color;
  }

  public void setColor(Object color) {
    this.color = color;
  }

  public RepoLabelsBody description(Object description) {
    this.description = description;
    return this;
  }

   /**
   * A short description of the label. Must be 100 characters or fewer.
   * @return description
  **/
  public Object getDescription() {
    return description;
  }

  public void setDescription(Object description) {
    this.description = description;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RepoLabelsBody repoLabelsBody = (RepoLabelsBody) o;
    return Objects.equals(this.name, repoLabelsBody.name) &&
        Objects.equals(this.color, repoLabelsBody.color) &&
        Objects.equals(this.description, repoLabelsBody.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, color, description);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RepoLabelsBody {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    color: ").append(toIndentedString(color)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
