/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * RepoIssuesBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class RepoIssuesBody {
  @JsonProperty("title")
  private Object title = null;

  @JsonProperty("body")
  private Object body = null;

  @JsonProperty("assignee")
  private Object assignee = null;

  @JsonProperty("milestone")
  private Object milestone = null;

  @JsonProperty("labels")
  private Object labels = null;

  @JsonProperty("assignees")
  private Object assignees = null;

  public RepoIssuesBody title(Object title) {
    this.title = title;
    return this;
  }

   /**
   * The title of the issue.
   * @return title
  **/
  public Object getTitle() {
    return title;
  }

  public void setTitle(Object title) {
    this.title = title;
  }

  public RepoIssuesBody body(Object body) {
    this.body = body;
    return this;
  }

   /**
   * The contents of the issue.
   * @return body
  **/
  public Object getBody() {
    return body;
  }

  public void setBody(Object body) {
    this.body = body;
  }

  public RepoIssuesBody assignee(Object assignee) {
    this.assignee = assignee;
    return this;
  }

   /**
   * Login for the user that this issue should be assigned to. _NOTE: Only users with push access can set the assignee for new issues. The assignee is silently dropped otherwise. **This field is deprecated.**_
   * @return assignee
  **/
  public Object getAssignee() {
    return assignee;
  }

  public void setAssignee(Object assignee) {
    this.assignee = assignee;
  }

  public RepoIssuesBody milestone(Object milestone) {
    this.milestone = milestone;
    return this;
  }

   /**
   * Get milestone
   * @return milestone
  **/
  public Object getMilestone() {
    return milestone;
  }

  public void setMilestone(Object milestone) {
    this.milestone = milestone;
  }

  public RepoIssuesBody labels(Object labels) {
    this.labels = labels;
    return this;
  }

   /**
   * Labels to associate with this issue. _NOTE: Only users with push access can set labels for new issues. Labels are silently dropped otherwise._
   * @return labels
  **/
  public Object getLabels() {
    return labels;
  }

  public void setLabels(Object labels) {
    this.labels = labels;
  }

  public RepoIssuesBody assignees(Object assignees) {
    this.assignees = assignees;
    return this;
  }

   /**
   * Logins for Users to assign to this issue. _NOTE: Only users with push access can set assignees for new issues. Assignees are silently dropped otherwise._
   * @return assignees
  **/
  public Object getAssignees() {
    return assignees;
  }

  public void setAssignees(Object assignees) {
    this.assignees = assignees;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RepoIssuesBody repoIssuesBody = (RepoIssuesBody) o;
    return Objects.equals(this.title, repoIssuesBody.title) &&
        Objects.equals(this.body, repoIssuesBody.body) &&
        Objects.equals(this.assignee, repoIssuesBody.assignee) &&
        Objects.equals(this.milestone, repoIssuesBody.milestone) &&
        Objects.equals(this.labels, repoIssuesBody.labels) &&
        Objects.equals(this.assignees, repoIssuesBody.assignees);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, body, assignee, milestone, labels, assignees);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RepoIssuesBody {\n");
    
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("    assignee: ").append(toIndentedString(assignee)).append("\n");
    sb.append("    milestone: ").append(toIndentedString(milestone)).append("\n");
    sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
    sb.append("    assignees: ").append(toIndentedString(assignees)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
