/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Repository Collaborator Permission
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class RepositoryCollaboratorPermission {
  @JsonProperty("permission")
  private Object permission = null;

  @JsonProperty("role_name")
  private Object roleName = null;

  @JsonProperty("user")
  private Object user = null;

  public RepositoryCollaboratorPermission permission(Object permission) {
    this.permission = permission;
    return this;
  }

   /**
   * Get permission
   * @return permission
  **/
  public Object getPermission() {
    return permission;
  }

  public void setPermission(Object permission) {
    this.permission = permission;
  }

  public RepositoryCollaboratorPermission roleName(Object roleName) {
    this.roleName = roleName;
    return this;
  }

   /**
   * Get roleName
   * @return roleName
  **/
  public Object getRoleName() {
    return roleName;
  }

  public void setRoleName(Object roleName) {
    this.roleName = roleName;
  }

  public RepositoryCollaboratorPermission user(Object user) {
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  public Object getUser() {
    return user;
  }

  public void setUser(Object user) {
    this.user = user;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RepositoryCollaboratorPermission repositoryCollaboratorPermission = (RepositoryCollaboratorPermission) o;
    return Objects.equals(this.permission, repositoryCollaboratorPermission.permission) &&
        Objects.equals(this.roleName, repositoryCollaboratorPermission.roleName) &&
        Objects.equals(this.user, repositoryCollaboratorPermission.user);
  }

  @Override
  public int hashCode() {
    return Objects.hash(permission, roleName, user);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RepositoryCollaboratorPermission {\n");
    
    sb.append("    permission: ").append(toIndentedString(permission)).append("\n");
    sb.append("    roleName: ").append(toIndentedString(roleName)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
