/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Information about the person who is making the commit. By default, &#x60;committer&#x60; will use the information set in &#x60;author&#x60;. See the &#x60;author&#x60; and &#x60;committer&#x60; object below for details.
 */
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class ReposownerrepogitcommitsCommitter {
  @JsonProperty("name")
  private Object name = null;

  @JsonProperty("email")
  private Object email = null;

  @JsonProperty("date")
  private Object date = null;

  public ReposownerrepogitcommitsCommitter name(Object name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the author (or committer) of the commit
   * @return name
  **/
  public Object getName() {
    return name;
  }

  public void setName(Object name) {
    this.name = name;
  }

  public ReposownerrepogitcommitsCommitter email(Object email) {
    this.email = email;
    return this;
  }

   /**
   * The email of the author (or committer) of the commit
   * @return email
  **/
  public Object getEmail() {
    return email;
  }

  public void setEmail(Object email) {
    this.email = email;
  }

  public ReposownerrepogitcommitsCommitter date(Object date) {
    this.date = date;
    return this;
  }

   /**
   * Indicates when this commit was authored (or committed). This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: &#x60;YYYY-MM-DDTHH:MM:SSZ&#x60;.
   * @return date
  **/
  public Object getDate() {
    return date;
  }

  public void setDate(Object date) {
    this.date = date;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReposownerrepogitcommitsCommitter reposownerrepogitcommitsCommitter = (ReposownerrepogitcommitsCommitter) o;
    return Objects.equals(this.name, reposownerrepogitcommitsCommitter.name) &&
        Objects.equals(this.email, reposownerrepogitcommitsCommitter.email) &&
        Objects.equals(this.date, reposownerrepogitcommitsCommitter.date);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, email, date);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReposownerrepogitcommitsCommitter {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
