/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.github.api.client.User;

/**
 * RepositoryLite
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class RepositoryLite {
  @JsonProperty("archive_url")
  private Object archiveUrl = null;

  @JsonProperty("assignees_url")
  private Object assigneesUrl = null;

  @JsonProperty("blobs_url")
  private Object blobsUrl = null;

  @JsonProperty("branches_url")
  private Object branchesUrl = null;

  @JsonProperty("collaborators_url")
  private Object collaboratorsUrl = null;

  @JsonProperty("comments_url")
  private Object commentsUrl = null;

  @JsonProperty("commits_url")
  private Object commitsUrl = null;

  @JsonProperty("compare_url")
  private Object compareUrl = null;

  @JsonProperty("contents_url")
  private Object contentsUrl = null;

  @JsonProperty("contributors_url")
  private Object contributorsUrl = null;

  @JsonProperty("deployments_url")
  private Object deploymentsUrl = null;

  @JsonProperty("description")
  private Object description = null;

  @JsonProperty("downloads_url")
  private Object downloadsUrl = null;

  @JsonProperty("events_url")
  private Object eventsUrl = null;

  @JsonProperty("fork")
  private Object fork = null;

  @JsonProperty("forks_url")
  private Object forksUrl = null;

  @JsonProperty("full_name")
  private Object fullName = null;

  @JsonProperty("git_commits_url")
  private Object gitCommitsUrl = null;

  @JsonProperty("git_refs_url")
  private Object gitRefsUrl = null;

  @JsonProperty("git_tags_url")
  private Object gitTagsUrl = null;

  @JsonProperty("hooks_url")
  private Object hooksUrl = null;

  @JsonProperty("html_url")
  private Object htmlUrl = null;

  @JsonProperty("id")
  private Object id = null;

  @JsonProperty("issue_comment_url")
  private Object issueCommentUrl = null;

  @JsonProperty("issue_events_url")
  private Object issueEventsUrl = null;

  @JsonProperty("issues_url")
  private Object issuesUrl = null;

  @JsonProperty("keys_url")
  private Object keysUrl = null;

  @JsonProperty("labels_url")
  private Object labelsUrl = null;

  @JsonProperty("languages_url")
  private Object languagesUrl = null;

  @JsonProperty("merges_url")
  private Object mergesUrl = null;

  @JsonProperty("milestones_url")
  private Object milestonesUrl = null;

  @JsonProperty("name")
  private Object name = null;

  @JsonProperty("node_id")
  private Object nodeId = null;

  @JsonProperty("notifications_url")
  private Object notificationsUrl = null;

  @JsonProperty("owner")
  private User owner = null;

  @JsonProperty("private")
  private Object _private = null;

  @JsonProperty("pulls_url")
  private Object pullsUrl = null;

  @JsonProperty("releases_url")
  private Object releasesUrl = null;

  @JsonProperty("stargazers_url")
  private Object stargazersUrl = null;

  @JsonProperty("statuses_url")
  private Object statusesUrl = null;

  @JsonProperty("subscribers_url")
  private Object subscribersUrl = null;

  @JsonProperty("subscription_url")
  private Object subscriptionUrl = null;

  @JsonProperty("tags_url")
  private Object tagsUrl = null;

  @JsonProperty("teams_url")
  private Object teamsUrl = null;

  @JsonProperty("trees_url")
  private Object treesUrl = null;

  @JsonProperty("url")
  private Object url = null;

  public RepositoryLite archiveUrl(Object archiveUrl) {
    this.archiveUrl = archiveUrl;
    return this;
  }

   /**
   * Get archiveUrl
   * @return archiveUrl
  **/
  public Object getArchiveUrl() {
    return archiveUrl;
  }

  public void setArchiveUrl(Object archiveUrl) {
    this.archiveUrl = archiveUrl;
  }

  public RepositoryLite assigneesUrl(Object assigneesUrl) {
    this.assigneesUrl = assigneesUrl;
    return this;
  }

   /**
   * Get assigneesUrl
   * @return assigneesUrl
  **/
  public Object getAssigneesUrl() {
    return assigneesUrl;
  }

  public void setAssigneesUrl(Object assigneesUrl) {
    this.assigneesUrl = assigneesUrl;
  }

  public RepositoryLite blobsUrl(Object blobsUrl) {
    this.blobsUrl = blobsUrl;
    return this;
  }

   /**
   * Get blobsUrl
   * @return blobsUrl
  **/
  public Object getBlobsUrl() {
    return blobsUrl;
  }

  public void setBlobsUrl(Object blobsUrl) {
    this.blobsUrl = blobsUrl;
  }

  public RepositoryLite branchesUrl(Object branchesUrl) {
    this.branchesUrl = branchesUrl;
    return this;
  }

   /**
   * Get branchesUrl
   * @return branchesUrl
  **/
  public Object getBranchesUrl() {
    return branchesUrl;
  }

  public void setBranchesUrl(Object branchesUrl) {
    this.branchesUrl = branchesUrl;
  }

  public RepositoryLite collaboratorsUrl(Object collaboratorsUrl) {
    this.collaboratorsUrl = collaboratorsUrl;
    return this;
  }

   /**
   * Get collaboratorsUrl
   * @return collaboratorsUrl
  **/
  public Object getCollaboratorsUrl() {
    return collaboratorsUrl;
  }

  public void setCollaboratorsUrl(Object collaboratorsUrl) {
    this.collaboratorsUrl = collaboratorsUrl;
  }

  public RepositoryLite commentsUrl(Object commentsUrl) {
    this.commentsUrl = commentsUrl;
    return this;
  }

   /**
   * Get commentsUrl
   * @return commentsUrl
  **/
  public Object getCommentsUrl() {
    return commentsUrl;
  }

  public void setCommentsUrl(Object commentsUrl) {
    this.commentsUrl = commentsUrl;
  }

  public RepositoryLite commitsUrl(Object commitsUrl) {
    this.commitsUrl = commitsUrl;
    return this;
  }

   /**
   * Get commitsUrl
   * @return commitsUrl
  **/
  public Object getCommitsUrl() {
    return commitsUrl;
  }

  public void setCommitsUrl(Object commitsUrl) {
    this.commitsUrl = commitsUrl;
  }

  public RepositoryLite compareUrl(Object compareUrl) {
    this.compareUrl = compareUrl;
    return this;
  }

   /**
   * Get compareUrl
   * @return compareUrl
  **/
  public Object getCompareUrl() {
    return compareUrl;
  }

  public void setCompareUrl(Object compareUrl) {
    this.compareUrl = compareUrl;
  }

  public RepositoryLite contentsUrl(Object contentsUrl) {
    this.contentsUrl = contentsUrl;
    return this;
  }

   /**
   * Get contentsUrl
   * @return contentsUrl
  **/
  public Object getContentsUrl() {
    return contentsUrl;
  }

  public void setContentsUrl(Object contentsUrl) {
    this.contentsUrl = contentsUrl;
  }

  public RepositoryLite contributorsUrl(Object contributorsUrl) {
    this.contributorsUrl = contributorsUrl;
    return this;
  }

   /**
   * Get contributorsUrl
   * @return contributorsUrl
  **/
  public Object getContributorsUrl() {
    return contributorsUrl;
  }

  public void setContributorsUrl(Object contributorsUrl) {
    this.contributorsUrl = contributorsUrl;
  }

  public RepositoryLite deploymentsUrl(Object deploymentsUrl) {
    this.deploymentsUrl = deploymentsUrl;
    return this;
  }

   /**
   * Get deploymentsUrl
   * @return deploymentsUrl
  **/
  public Object getDeploymentsUrl() {
    return deploymentsUrl;
  }

  public void setDeploymentsUrl(Object deploymentsUrl) {
    this.deploymentsUrl = deploymentsUrl;
  }

  public RepositoryLite description(Object description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  public Object getDescription() {
    return description;
  }

  public void setDescription(Object description) {
    this.description = description;
  }

  public RepositoryLite downloadsUrl(Object downloadsUrl) {
    this.downloadsUrl = downloadsUrl;
    return this;
  }

   /**
   * Get downloadsUrl
   * @return downloadsUrl
  **/
  public Object getDownloadsUrl() {
    return downloadsUrl;
  }

  public void setDownloadsUrl(Object downloadsUrl) {
    this.downloadsUrl = downloadsUrl;
  }

  public RepositoryLite eventsUrl(Object eventsUrl) {
    this.eventsUrl = eventsUrl;
    return this;
  }

   /**
   * Get eventsUrl
   * @return eventsUrl
  **/
  public Object getEventsUrl() {
    return eventsUrl;
  }

  public void setEventsUrl(Object eventsUrl) {
    this.eventsUrl = eventsUrl;
  }

  public RepositoryLite fork(Object fork) {
    this.fork = fork;
    return this;
  }

   /**
   * Get fork
   * @return fork
  **/
  public Object getFork() {
    return fork;
  }

  public void setFork(Object fork) {
    this.fork = fork;
  }

  public RepositoryLite forksUrl(Object forksUrl) {
    this.forksUrl = forksUrl;
    return this;
  }

   /**
   * Get forksUrl
   * @return forksUrl
  **/
  public Object getForksUrl() {
    return forksUrl;
  }

  public void setForksUrl(Object forksUrl) {
    this.forksUrl = forksUrl;
  }

  public RepositoryLite fullName(Object fullName) {
    this.fullName = fullName;
    return this;
  }

   /**
   * Get fullName
   * @return fullName
  **/
  public Object getFullName() {
    return fullName;
  }

  public void setFullName(Object fullName) {
    this.fullName = fullName;
  }

  public RepositoryLite gitCommitsUrl(Object gitCommitsUrl) {
    this.gitCommitsUrl = gitCommitsUrl;
    return this;
  }

   /**
   * Get gitCommitsUrl
   * @return gitCommitsUrl
  **/
  public Object getGitCommitsUrl() {
    return gitCommitsUrl;
  }

  public void setGitCommitsUrl(Object gitCommitsUrl) {
    this.gitCommitsUrl = gitCommitsUrl;
  }

  public RepositoryLite gitRefsUrl(Object gitRefsUrl) {
    this.gitRefsUrl = gitRefsUrl;
    return this;
  }

   /**
   * Get gitRefsUrl
   * @return gitRefsUrl
  **/
  public Object getGitRefsUrl() {
    return gitRefsUrl;
  }

  public void setGitRefsUrl(Object gitRefsUrl) {
    this.gitRefsUrl = gitRefsUrl;
  }

  public RepositoryLite gitTagsUrl(Object gitTagsUrl) {
    this.gitTagsUrl = gitTagsUrl;
    return this;
  }

   /**
   * Get gitTagsUrl
   * @return gitTagsUrl
  **/
  public Object getGitTagsUrl() {
    return gitTagsUrl;
  }

  public void setGitTagsUrl(Object gitTagsUrl) {
    this.gitTagsUrl = gitTagsUrl;
  }

  public RepositoryLite hooksUrl(Object hooksUrl) {
    this.hooksUrl = hooksUrl;
    return this;
  }

   /**
   * Get hooksUrl
   * @return hooksUrl
  **/
  public Object getHooksUrl() {
    return hooksUrl;
  }

  public void setHooksUrl(Object hooksUrl) {
    this.hooksUrl = hooksUrl;
  }

  public RepositoryLite htmlUrl(Object htmlUrl) {
    this.htmlUrl = htmlUrl;
    return this;
  }

   /**
   * Get htmlUrl
   * @return htmlUrl
  **/
  public Object getHtmlUrl() {
    return htmlUrl;
  }

  public void setHtmlUrl(Object htmlUrl) {
    this.htmlUrl = htmlUrl;
  }

  public RepositoryLite id(Object id) {
    this.id = id;
    return this;
  }

   /**
   * Unique identifier of the repository
   * @return id
  **/
  public Object getId() {
    return id;
  }

  public void setId(Object id) {
    this.id = id;
  }

  public RepositoryLite issueCommentUrl(Object issueCommentUrl) {
    this.issueCommentUrl = issueCommentUrl;
    return this;
  }

   /**
   * Get issueCommentUrl
   * @return issueCommentUrl
  **/
  public Object getIssueCommentUrl() {
    return issueCommentUrl;
  }

  public void setIssueCommentUrl(Object issueCommentUrl) {
    this.issueCommentUrl = issueCommentUrl;
  }

  public RepositoryLite issueEventsUrl(Object issueEventsUrl) {
    this.issueEventsUrl = issueEventsUrl;
    return this;
  }

   /**
   * Get issueEventsUrl
   * @return issueEventsUrl
  **/
  public Object getIssueEventsUrl() {
    return issueEventsUrl;
  }

  public void setIssueEventsUrl(Object issueEventsUrl) {
    this.issueEventsUrl = issueEventsUrl;
  }

  public RepositoryLite issuesUrl(Object issuesUrl) {
    this.issuesUrl = issuesUrl;
    return this;
  }

   /**
   * Get issuesUrl
   * @return issuesUrl
  **/
  public Object getIssuesUrl() {
    return issuesUrl;
  }

  public void setIssuesUrl(Object issuesUrl) {
    this.issuesUrl = issuesUrl;
  }

  public RepositoryLite keysUrl(Object keysUrl) {
    this.keysUrl = keysUrl;
    return this;
  }

   /**
   * Get keysUrl
   * @return keysUrl
  **/
  public Object getKeysUrl() {
    return keysUrl;
  }

  public void setKeysUrl(Object keysUrl) {
    this.keysUrl = keysUrl;
  }

  public RepositoryLite labelsUrl(Object labelsUrl) {
    this.labelsUrl = labelsUrl;
    return this;
  }

   /**
   * Get labelsUrl
   * @return labelsUrl
  **/
  public Object getLabelsUrl() {
    return labelsUrl;
  }

  public void setLabelsUrl(Object labelsUrl) {
    this.labelsUrl = labelsUrl;
  }

  public RepositoryLite languagesUrl(Object languagesUrl) {
    this.languagesUrl = languagesUrl;
    return this;
  }

   /**
   * Get languagesUrl
   * @return languagesUrl
  **/
  public Object getLanguagesUrl() {
    return languagesUrl;
  }

  public void setLanguagesUrl(Object languagesUrl) {
    this.languagesUrl = languagesUrl;
  }

  public RepositoryLite mergesUrl(Object mergesUrl) {
    this.mergesUrl = mergesUrl;
    return this;
  }

   /**
   * Get mergesUrl
   * @return mergesUrl
  **/
  public Object getMergesUrl() {
    return mergesUrl;
  }

  public void setMergesUrl(Object mergesUrl) {
    this.mergesUrl = mergesUrl;
  }

  public RepositoryLite milestonesUrl(Object milestonesUrl) {
    this.milestonesUrl = milestonesUrl;
    return this;
  }

   /**
   * Get milestonesUrl
   * @return milestonesUrl
  **/
  public Object getMilestonesUrl() {
    return milestonesUrl;
  }

  public void setMilestonesUrl(Object milestonesUrl) {
    this.milestonesUrl = milestonesUrl;
  }

  public RepositoryLite name(Object name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the repository.
   * @return name
  **/
  public Object getName() {
    return name;
  }

  public void setName(Object name) {
    this.name = name;
  }

  public RepositoryLite nodeId(Object nodeId) {
    this.nodeId = nodeId;
    return this;
  }

   /**
   * Get nodeId
   * @return nodeId
  **/
  public Object getNodeId() {
    return nodeId;
  }

  public void setNodeId(Object nodeId) {
    this.nodeId = nodeId;
  }

  public RepositoryLite notificationsUrl(Object notificationsUrl) {
    this.notificationsUrl = notificationsUrl;
    return this;
  }

   /**
   * Get notificationsUrl
   * @return notificationsUrl
  **/
  public Object getNotificationsUrl() {
    return notificationsUrl;
  }

  public void setNotificationsUrl(Object notificationsUrl) {
    this.notificationsUrl = notificationsUrl;
  }

  public RepositoryLite owner(User owner) {
    this.owner = owner;
    return this;
  }

   /**
   * Get owner
   * @return owner
  **/
  public User getOwner() {
    return owner;
  }

  public void setOwner(User owner) {
    this.owner = owner;
  }

  public RepositoryLite _private(Object _private) {
    this._private = _private;
    return this;
  }

   /**
   * Whether the repository is private or public.
   * @return _private
  **/
  public Object getPrivate() {
    return _private;
  }

  public void setPrivate(Object _private) {
    this._private = _private;
  }

  public RepositoryLite pullsUrl(Object pullsUrl) {
    this.pullsUrl = pullsUrl;
    return this;
  }

   /**
   * Get pullsUrl
   * @return pullsUrl
  **/
  public Object getPullsUrl() {
    return pullsUrl;
  }

  public void setPullsUrl(Object pullsUrl) {
    this.pullsUrl = pullsUrl;
  }

  public RepositoryLite releasesUrl(Object releasesUrl) {
    this.releasesUrl = releasesUrl;
    return this;
  }

   /**
   * Get releasesUrl
   * @return releasesUrl
  **/
  public Object getReleasesUrl() {
    return releasesUrl;
  }

  public void setReleasesUrl(Object releasesUrl) {
    this.releasesUrl = releasesUrl;
  }

  public RepositoryLite stargazersUrl(Object stargazersUrl) {
    this.stargazersUrl = stargazersUrl;
    return this;
  }

   /**
   * Get stargazersUrl
   * @return stargazersUrl
  **/
  public Object getStargazersUrl() {
    return stargazersUrl;
  }

  public void setStargazersUrl(Object stargazersUrl) {
    this.stargazersUrl = stargazersUrl;
  }

  public RepositoryLite statusesUrl(Object statusesUrl) {
    this.statusesUrl = statusesUrl;
    return this;
  }

   /**
   * Get statusesUrl
   * @return statusesUrl
  **/
  public Object getStatusesUrl() {
    return statusesUrl;
  }

  public void setStatusesUrl(Object statusesUrl) {
    this.statusesUrl = statusesUrl;
  }

  public RepositoryLite subscribersUrl(Object subscribersUrl) {
    this.subscribersUrl = subscribersUrl;
    return this;
  }

   /**
   * Get subscribersUrl
   * @return subscribersUrl
  **/
  public Object getSubscribersUrl() {
    return subscribersUrl;
  }

  public void setSubscribersUrl(Object subscribersUrl) {
    this.subscribersUrl = subscribersUrl;
  }

  public RepositoryLite subscriptionUrl(Object subscriptionUrl) {
    this.subscriptionUrl = subscriptionUrl;
    return this;
  }

   /**
   * Get subscriptionUrl
   * @return subscriptionUrl
  **/
  public Object getSubscriptionUrl() {
    return subscriptionUrl;
  }

  public void setSubscriptionUrl(Object subscriptionUrl) {
    this.subscriptionUrl = subscriptionUrl;
  }

  public RepositoryLite tagsUrl(Object tagsUrl) {
    this.tagsUrl = tagsUrl;
    return this;
  }

   /**
   * Get tagsUrl
   * @return tagsUrl
  **/
  public Object getTagsUrl() {
    return tagsUrl;
  }

  public void setTagsUrl(Object tagsUrl) {
    this.tagsUrl = tagsUrl;
  }

  public RepositoryLite teamsUrl(Object teamsUrl) {
    this.teamsUrl = teamsUrl;
    return this;
  }

   /**
   * Get teamsUrl
   * @return teamsUrl
  **/
  public Object getTeamsUrl() {
    return teamsUrl;
  }

  public void setTeamsUrl(Object teamsUrl) {
    this.teamsUrl = teamsUrl;
  }

  public RepositoryLite treesUrl(Object treesUrl) {
    this.treesUrl = treesUrl;
    return this;
  }

   /**
   * Get treesUrl
   * @return treesUrl
  **/
  public Object getTreesUrl() {
    return treesUrl;
  }

  public void setTreesUrl(Object treesUrl) {
    this.treesUrl = treesUrl;
  }

  public RepositoryLite url(Object url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  public Object getUrl() {
    return url;
  }

  public void setUrl(Object url) {
    this.url = url;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RepositoryLite repositoryLite = (RepositoryLite) o;
    return Objects.equals(this.archiveUrl, repositoryLite.archiveUrl) &&
        Objects.equals(this.assigneesUrl, repositoryLite.assigneesUrl) &&
        Objects.equals(this.blobsUrl, repositoryLite.blobsUrl) &&
        Objects.equals(this.branchesUrl, repositoryLite.branchesUrl) &&
        Objects.equals(this.collaboratorsUrl, repositoryLite.collaboratorsUrl) &&
        Objects.equals(this.commentsUrl, repositoryLite.commentsUrl) &&
        Objects.equals(this.commitsUrl, repositoryLite.commitsUrl) &&
        Objects.equals(this.compareUrl, repositoryLite.compareUrl) &&
        Objects.equals(this.contentsUrl, repositoryLite.contentsUrl) &&
        Objects.equals(this.contributorsUrl, repositoryLite.contributorsUrl) &&
        Objects.equals(this.deploymentsUrl, repositoryLite.deploymentsUrl) &&
        Objects.equals(this.description, repositoryLite.description) &&
        Objects.equals(this.downloadsUrl, repositoryLite.downloadsUrl) &&
        Objects.equals(this.eventsUrl, repositoryLite.eventsUrl) &&
        Objects.equals(this.fork, repositoryLite.fork) &&
        Objects.equals(this.forksUrl, repositoryLite.forksUrl) &&
        Objects.equals(this.fullName, repositoryLite.fullName) &&
        Objects.equals(this.gitCommitsUrl, repositoryLite.gitCommitsUrl) &&
        Objects.equals(this.gitRefsUrl, repositoryLite.gitRefsUrl) &&
        Objects.equals(this.gitTagsUrl, repositoryLite.gitTagsUrl) &&
        Objects.equals(this.hooksUrl, repositoryLite.hooksUrl) &&
        Objects.equals(this.htmlUrl, repositoryLite.htmlUrl) &&
        Objects.equals(this.id, repositoryLite.id) &&
        Objects.equals(this.issueCommentUrl, repositoryLite.issueCommentUrl) &&
        Objects.equals(this.issueEventsUrl, repositoryLite.issueEventsUrl) &&
        Objects.equals(this.issuesUrl, repositoryLite.issuesUrl) &&
        Objects.equals(this.keysUrl, repositoryLite.keysUrl) &&
        Objects.equals(this.labelsUrl, repositoryLite.labelsUrl) &&
        Objects.equals(this.languagesUrl, repositoryLite.languagesUrl) &&
        Objects.equals(this.mergesUrl, repositoryLite.mergesUrl) &&
        Objects.equals(this.milestonesUrl, repositoryLite.milestonesUrl) &&
        Objects.equals(this.name, repositoryLite.name) &&
        Objects.equals(this.nodeId, repositoryLite.nodeId) &&
        Objects.equals(this.notificationsUrl, repositoryLite.notificationsUrl) &&
        Objects.equals(this.owner, repositoryLite.owner) &&
        Objects.equals(this._private, repositoryLite._private) &&
        Objects.equals(this.pullsUrl, repositoryLite.pullsUrl) &&
        Objects.equals(this.releasesUrl, repositoryLite.releasesUrl) &&
        Objects.equals(this.stargazersUrl, repositoryLite.stargazersUrl) &&
        Objects.equals(this.statusesUrl, repositoryLite.statusesUrl) &&
        Objects.equals(this.subscribersUrl, repositoryLite.subscribersUrl) &&
        Objects.equals(this.subscriptionUrl, repositoryLite.subscriptionUrl) &&
        Objects.equals(this.tagsUrl, repositoryLite.tagsUrl) &&
        Objects.equals(this.teamsUrl, repositoryLite.teamsUrl) &&
        Objects.equals(this.treesUrl, repositoryLite.treesUrl) &&
        Objects.equals(this.url, repositoryLite.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(archiveUrl, assigneesUrl, blobsUrl, branchesUrl, collaboratorsUrl, commentsUrl, commitsUrl, compareUrl, contentsUrl, contributorsUrl, deploymentsUrl, description, downloadsUrl, eventsUrl, fork, forksUrl, fullName, gitCommitsUrl, gitRefsUrl, gitTagsUrl, hooksUrl, htmlUrl, id, issueCommentUrl, issueEventsUrl, issuesUrl, keysUrl, labelsUrl, languagesUrl, mergesUrl, milestonesUrl, name, nodeId, notificationsUrl, owner, _private, pullsUrl, releasesUrl, stargazersUrl, statusesUrl, subscribersUrl, subscriptionUrl, tagsUrl, teamsUrl, treesUrl, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RepositoryLite {\n");
    
    sb.append("    archiveUrl: ").append(toIndentedString(archiveUrl)).append("\n");
    sb.append("    assigneesUrl: ").append(toIndentedString(assigneesUrl)).append("\n");
    sb.append("    blobsUrl: ").append(toIndentedString(blobsUrl)).append("\n");
    sb.append("    branchesUrl: ").append(toIndentedString(branchesUrl)).append("\n");
    sb.append("    collaboratorsUrl: ").append(toIndentedString(collaboratorsUrl)).append("\n");
    sb.append("    commentsUrl: ").append(toIndentedString(commentsUrl)).append("\n");
    sb.append("    commitsUrl: ").append(toIndentedString(commitsUrl)).append("\n");
    sb.append("    compareUrl: ").append(toIndentedString(compareUrl)).append("\n");
    sb.append("    contentsUrl: ").append(toIndentedString(contentsUrl)).append("\n");
    sb.append("    contributorsUrl: ").append(toIndentedString(contributorsUrl)).append("\n");
    sb.append("    deploymentsUrl: ").append(toIndentedString(deploymentsUrl)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    downloadsUrl: ").append(toIndentedString(downloadsUrl)).append("\n");
    sb.append("    eventsUrl: ").append(toIndentedString(eventsUrl)).append("\n");
    sb.append("    fork: ").append(toIndentedString(fork)).append("\n");
    sb.append("    forksUrl: ").append(toIndentedString(forksUrl)).append("\n");
    sb.append("    fullName: ").append(toIndentedString(fullName)).append("\n");
    sb.append("    gitCommitsUrl: ").append(toIndentedString(gitCommitsUrl)).append("\n");
    sb.append("    gitRefsUrl: ").append(toIndentedString(gitRefsUrl)).append("\n");
    sb.append("    gitTagsUrl: ").append(toIndentedString(gitTagsUrl)).append("\n");
    sb.append("    hooksUrl: ").append(toIndentedString(hooksUrl)).append("\n");
    sb.append("    htmlUrl: ").append(toIndentedString(htmlUrl)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    issueCommentUrl: ").append(toIndentedString(issueCommentUrl)).append("\n");
    sb.append("    issueEventsUrl: ").append(toIndentedString(issueEventsUrl)).append("\n");
    sb.append("    issuesUrl: ").append(toIndentedString(issuesUrl)).append("\n");
    sb.append("    keysUrl: ").append(toIndentedString(keysUrl)).append("\n");
    sb.append("    labelsUrl: ").append(toIndentedString(labelsUrl)).append("\n");
    sb.append("    languagesUrl: ").append(toIndentedString(languagesUrl)).append("\n");
    sb.append("    mergesUrl: ").append(toIndentedString(mergesUrl)).append("\n");
    sb.append("    milestonesUrl: ").append(toIndentedString(milestonesUrl)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    nodeId: ").append(toIndentedString(nodeId)).append("\n");
    sb.append("    notificationsUrl: ").append(toIndentedString(notificationsUrl)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    _private: ").append(toIndentedString(_private)).append("\n");
    sb.append("    pullsUrl: ").append(toIndentedString(pullsUrl)).append("\n");
    sb.append("    releasesUrl: ").append(toIndentedString(releasesUrl)).append("\n");
    sb.append("    stargazersUrl: ").append(toIndentedString(stargazersUrl)).append("\n");
    sb.append("    statusesUrl: ").append(toIndentedString(statusesUrl)).append("\n");
    sb.append("    subscribersUrl: ").append(toIndentedString(subscribersUrl)).append("\n");
    sb.append("    subscriptionUrl: ").append(toIndentedString(subscriptionUrl)).append("\n");
    sb.append("    tagsUrl: ").append(toIndentedString(tagsUrl)).append("\n");
    sb.append("    teamsUrl: ").append(toIndentedString(teamsUrl)).append("\n");
    sb.append("    treesUrl: ").append(toIndentedString(treesUrl)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
