/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Repository invitations let you manage who you collaborate with.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class RepositorySubscription {
  @JsonProperty("subscribed")
  private Object subscribed = null;

  @JsonProperty("ignored")
  private Object ignored = null;

  @JsonProperty("reason")
  private Object reason = null;

  @JsonProperty("created_at")
  private Object createdAt = null;

  @JsonProperty("url")
  private Object url = null;

  @JsonProperty("repository_url")
  private Object repositoryUrl = null;

  public RepositorySubscription subscribed(Object subscribed) {
    this.subscribed = subscribed;
    return this;
  }

   /**
   * Determines if notifications should be received from this repository.
   * @return subscribed
  **/
  public Object getSubscribed() {
    return subscribed;
  }

  public void setSubscribed(Object subscribed) {
    this.subscribed = subscribed;
  }

  public RepositorySubscription ignored(Object ignored) {
    this.ignored = ignored;
    return this;
  }

   /**
   * Determines if all notifications should be blocked from this repository.
   * @return ignored
  **/
  public Object getIgnored() {
    return ignored;
  }

  public void setIgnored(Object ignored) {
    this.ignored = ignored;
  }

  public RepositorySubscription reason(Object reason) {
    this.reason = reason;
    return this;
  }

   /**
   * Get reason
   * @return reason
  **/
  public Object getReason() {
    return reason;
  }

  public void setReason(Object reason) {
    this.reason = reason;
  }

  public RepositorySubscription createdAt(Object createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  public Object getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(Object createdAt) {
    this.createdAt = createdAt;
  }

  public RepositorySubscription url(Object url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  public Object getUrl() {
    return url;
  }

  public void setUrl(Object url) {
    this.url = url;
  }

  public RepositorySubscription repositoryUrl(Object repositoryUrl) {
    this.repositoryUrl = repositoryUrl;
    return this;
  }

   /**
   * Get repositoryUrl
   * @return repositoryUrl
  **/
  public Object getRepositoryUrl() {
    return repositoryUrl;
  }

  public void setRepositoryUrl(Object repositoryUrl) {
    this.repositoryUrl = repositoryUrl;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RepositorySubscription repositorySubscription = (RepositorySubscription) o;
    return Objects.equals(this.subscribed, repositorySubscription.subscribed) &&
        Objects.equals(this.ignored, repositorySubscription.ignored) &&
        Objects.equals(this.reason, repositorySubscription.reason) &&
        Objects.equals(this.createdAt, repositorySubscription.createdAt) &&
        Objects.equals(this.url, repositorySubscription.url) &&
        Objects.equals(this.repositoryUrl, repositorySubscription.repositoryUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(subscribed, ignored, reason, createdAt, url, repositoryUrl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RepositorySubscription {\n");
    
    sb.append("    subscribed: ").append(toIndentedString(subscribed)).append("\n");
    sb.append("    ignored: ").append(toIndentedString(ignored)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    repositoryUrl: ").append(toIndentedString(repositoryUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
