/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.github.api.client.ReposownerrepobranchesbranchprotectionRequiredPullRequestReviewsBypassPullRequestAllowances;
import com.github.api.client.ReposownerrepobranchesbranchprotectionRequiredPullRequestReviewsDismissalRestrictions;

/**
 * Require at least one approving review on a pull request, before merging. Set to &#x60;null&#x60; to disable.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class ReposownerrepobranchesbranchprotectionRequiredPullRequestReviews {
  @JsonProperty("dismissal_restrictions")
  private ReposownerrepobranchesbranchprotectionRequiredPullRequestReviewsDismissalRestrictions dismissalRestrictions = null;

  @JsonProperty("dismiss_stale_reviews")
  private Object dismissStaleReviews = null;

  @JsonProperty("require_code_owner_reviews")
  private Object requireCodeOwnerReviews = null;

  @JsonProperty("required_approving_review_count")
  private Object requiredApprovingReviewCount = null;

  @JsonProperty("require_last_push_approval")
  private Object requireLastPushApproval = false;

  @JsonProperty("bypass_pull_request_allowances")
  private ReposownerrepobranchesbranchprotectionRequiredPullRequestReviewsBypassPullRequestAllowances bypassPullRequestAllowances = null;

  public ReposownerrepobranchesbranchprotectionRequiredPullRequestReviews dismissalRestrictions(ReposownerrepobranchesbranchprotectionRequiredPullRequestReviewsDismissalRestrictions dismissalRestrictions) {
    this.dismissalRestrictions = dismissalRestrictions;
    return this;
  }

   /**
   * Get dismissalRestrictions
   * @return dismissalRestrictions
  **/
  public ReposownerrepobranchesbranchprotectionRequiredPullRequestReviewsDismissalRestrictions getDismissalRestrictions() {
    return dismissalRestrictions;
  }

  public void setDismissalRestrictions(ReposownerrepobranchesbranchprotectionRequiredPullRequestReviewsDismissalRestrictions dismissalRestrictions) {
    this.dismissalRestrictions = dismissalRestrictions;
  }

  public ReposownerrepobranchesbranchprotectionRequiredPullRequestReviews dismissStaleReviews(Object dismissStaleReviews) {
    this.dismissStaleReviews = dismissStaleReviews;
    return this;
  }

   /**
   * Set to &#x60;true&#x60; if you want to automatically dismiss approving reviews when someone pushes a new commit.
   * @return dismissStaleReviews
  **/
  public Object getDismissStaleReviews() {
    return dismissStaleReviews;
  }

  public void setDismissStaleReviews(Object dismissStaleReviews) {
    this.dismissStaleReviews = dismissStaleReviews;
  }

  public ReposownerrepobranchesbranchprotectionRequiredPullRequestReviews requireCodeOwnerReviews(Object requireCodeOwnerReviews) {
    this.requireCodeOwnerReviews = requireCodeOwnerReviews;
    return this;
  }

   /**
   * Blocks merging pull requests until [code owners](https://docs.github.com/articles/about-code-owners/) review them.
   * @return requireCodeOwnerReviews
  **/
  public Object getRequireCodeOwnerReviews() {
    return requireCodeOwnerReviews;
  }

  public void setRequireCodeOwnerReviews(Object requireCodeOwnerReviews) {
    this.requireCodeOwnerReviews = requireCodeOwnerReviews;
  }

  public ReposownerrepobranchesbranchprotectionRequiredPullRequestReviews requiredApprovingReviewCount(Object requiredApprovingReviewCount) {
    this.requiredApprovingReviewCount = requiredApprovingReviewCount;
    return this;
  }

   /**
   * Specify the number of reviewers required to approve pull requests. Use a number between 1 and 6 or 0 to not require reviewers.
   * @return requiredApprovingReviewCount
  **/
  public Object getRequiredApprovingReviewCount() {
    return requiredApprovingReviewCount;
  }

  public void setRequiredApprovingReviewCount(Object requiredApprovingReviewCount) {
    this.requiredApprovingReviewCount = requiredApprovingReviewCount;
  }

  public ReposownerrepobranchesbranchprotectionRequiredPullRequestReviews requireLastPushApproval(Object requireLastPushApproval) {
    this.requireLastPushApproval = requireLastPushApproval;
    return this;
  }

   /**
   * Whether someone other than the person who last pushed to the branch must approve this pull request. Default: &#x60;false&#x60;.
   * @return requireLastPushApproval
  **/
  public Object getRequireLastPushApproval() {
    return requireLastPushApproval;
  }

  public void setRequireLastPushApproval(Object requireLastPushApproval) {
    this.requireLastPushApproval = requireLastPushApproval;
  }

  public ReposownerrepobranchesbranchprotectionRequiredPullRequestReviews bypassPullRequestAllowances(ReposownerrepobranchesbranchprotectionRequiredPullRequestReviewsBypassPullRequestAllowances bypassPullRequestAllowances) {
    this.bypassPullRequestAllowances = bypassPullRequestAllowances;
    return this;
  }

   /**
   * Get bypassPullRequestAllowances
   * @return bypassPullRequestAllowances
  **/
  public ReposownerrepobranchesbranchprotectionRequiredPullRequestReviewsBypassPullRequestAllowances getBypassPullRequestAllowances() {
    return bypassPullRequestAllowances;
  }

  public void setBypassPullRequestAllowances(ReposownerrepobranchesbranchprotectionRequiredPullRequestReviewsBypassPullRequestAllowances bypassPullRequestAllowances) {
    this.bypassPullRequestAllowances = bypassPullRequestAllowances;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReposownerrepobranchesbranchprotectionRequiredPullRequestReviews reposownerrepobranchesbranchprotectionRequiredPullRequestReviews = (ReposownerrepobranchesbranchprotectionRequiredPullRequestReviews) o;
    return Objects.equals(this.dismissalRestrictions, reposownerrepobranchesbranchprotectionRequiredPullRequestReviews.dismissalRestrictions) &&
        Objects.equals(this.dismissStaleReviews, reposownerrepobranchesbranchprotectionRequiredPullRequestReviews.dismissStaleReviews) &&
        Objects.equals(this.requireCodeOwnerReviews, reposownerrepobranchesbranchprotectionRequiredPullRequestReviews.requireCodeOwnerReviews) &&
        Objects.equals(this.requiredApprovingReviewCount, reposownerrepobranchesbranchprotectionRequiredPullRequestReviews.requiredApprovingReviewCount) &&
        Objects.equals(this.requireLastPushApproval, reposownerrepobranchesbranchprotectionRequiredPullRequestReviews.requireLastPushApproval) &&
        Objects.equals(this.bypassPullRequestAllowances, reposownerrepobranchesbranchprotectionRequiredPullRequestReviews.bypassPullRequestAllowances);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dismissalRestrictions, dismissStaleReviews, requireCodeOwnerReviews, requiredApprovingReviewCount, requireLastPushApproval, bypassPullRequestAllowances);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReposownerrepobranchesbranchprotectionRequiredPullRequestReviews {\n");
    
    sb.append("    dismissalRestrictions: ").append(toIndentedString(dismissalRestrictions)).append("\n");
    sb.append("    dismissStaleReviews: ").append(toIndentedString(dismissStaleReviews)).append("\n");
    sb.append("    requireCodeOwnerReviews: ").append(toIndentedString(requireCodeOwnerReviews)).append("\n");
    sb.append("    requiredApprovingReviewCount: ").append(toIndentedString(requiredApprovingReviewCount)).append("\n");
    sb.append("    requireLastPushApproval: ").append(toIndentedString(requireLastPushApproval)).append("\n");
    sb.append("    bypassPullRequestAllowances: ").append(toIndentedString(bypassPullRequestAllowances)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
