/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.github.api.client.AuthorAssociation;
import com.github.api.client.ReactionRollup;
import com.github.api.client.ReviewcommentLinks;

/**
 * Legacy Review Comment
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class ReviewComment {
  @JsonProperty("url")
  private Object url = null;

  @JsonProperty("pull_request_review_id")
  private Object pullRequestReviewId = null;

  @JsonProperty("id")
  private Object id = null;

  @JsonProperty("node_id")
  private Object nodeId = null;

  @JsonProperty("diff_hunk")
  private Object diffHunk = null;

  @JsonProperty("path")
  private Object path = null;

  @JsonProperty("position")
  private Object position = null;

  @JsonProperty("original_position")
  private Object originalPosition = null;

  @JsonProperty("commit_id")
  private Object commitId = null;

  @JsonProperty("original_commit_id")
  private Object originalCommitId = null;

  @JsonProperty("in_reply_to_id")
  private Object inReplyToId = null;

  @JsonProperty("user")
  private Object user = null;

  @JsonProperty("body")
  private Object body = null;

  @JsonProperty("created_at")
  private Object createdAt = null;

  @JsonProperty("updated_at")
  private Object updatedAt = null;

  @JsonProperty("html_url")
  private Object htmlUrl = null;

  @JsonProperty("pull_request_url")
  private Object pullRequestUrl = null;

  @JsonProperty("author_association")
  private AuthorAssociation authorAssociation = null;

  @JsonProperty("_links")
  private ReviewcommentLinks _links = null;

  @JsonProperty("body_text")
  private Object bodyText = null;

  @JsonProperty("body_html")
  private Object bodyHtml = null;

  @JsonProperty("reactions")
  private ReactionRollup reactions = null;

  @JsonProperty("side")
  private Object side = RIGHT;

  @JsonProperty("start_side")
  private Object startSide = RIGHT;

  @JsonProperty("line")
  private Object line = null;

  @JsonProperty("original_line")
  private Object originalLine = null;

  @JsonProperty("start_line")
  private Object startLine = null;

  @JsonProperty("original_start_line")
  private Object originalStartLine = null;

  public ReviewComment url(Object url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  public Object getUrl() {
    return url;
  }

  public void setUrl(Object url) {
    this.url = url;
  }

  public ReviewComment pullRequestReviewId(Object pullRequestReviewId) {
    this.pullRequestReviewId = pullRequestReviewId;
    return this;
  }

   /**
   * Get pullRequestReviewId
   * @return pullRequestReviewId
  **/
  public Object getPullRequestReviewId() {
    return pullRequestReviewId;
  }

  public void setPullRequestReviewId(Object pullRequestReviewId) {
    this.pullRequestReviewId = pullRequestReviewId;
  }

  public ReviewComment id(Object id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Object getId() {
    return id;
  }

  public void setId(Object id) {
    this.id = id;
  }

  public ReviewComment nodeId(Object nodeId) {
    this.nodeId = nodeId;
    return this;
  }

   /**
   * Get nodeId
   * @return nodeId
  **/
  public Object getNodeId() {
    return nodeId;
  }

  public void setNodeId(Object nodeId) {
    this.nodeId = nodeId;
  }

  public ReviewComment diffHunk(Object diffHunk) {
    this.diffHunk = diffHunk;
    return this;
  }

   /**
   * Get diffHunk
   * @return diffHunk
  **/
  public Object getDiffHunk() {
    return diffHunk;
  }

  public void setDiffHunk(Object diffHunk) {
    this.diffHunk = diffHunk;
  }

  public ReviewComment path(Object path) {
    this.path = path;
    return this;
  }

   /**
   * Get path
   * @return path
  **/
  public Object getPath() {
    return path;
  }

  public void setPath(Object path) {
    this.path = path;
  }

  public ReviewComment position(Object position) {
    this.position = position;
    return this;
  }

   /**
   * Get position
   * @return position
  **/
  public Object getPosition() {
    return position;
  }

  public void setPosition(Object position) {
    this.position = position;
  }

  public ReviewComment originalPosition(Object originalPosition) {
    this.originalPosition = originalPosition;
    return this;
  }

   /**
   * Get originalPosition
   * @return originalPosition
  **/
  public Object getOriginalPosition() {
    return originalPosition;
  }

  public void setOriginalPosition(Object originalPosition) {
    this.originalPosition = originalPosition;
  }

  public ReviewComment commitId(Object commitId) {
    this.commitId = commitId;
    return this;
  }

   /**
   * Get commitId
   * @return commitId
  **/
  public Object getCommitId() {
    return commitId;
  }

  public void setCommitId(Object commitId) {
    this.commitId = commitId;
  }

  public ReviewComment originalCommitId(Object originalCommitId) {
    this.originalCommitId = originalCommitId;
    return this;
  }

   /**
   * Get originalCommitId
   * @return originalCommitId
  **/
  public Object getOriginalCommitId() {
    return originalCommitId;
  }

  public void setOriginalCommitId(Object originalCommitId) {
    this.originalCommitId = originalCommitId;
  }

  public ReviewComment inReplyToId(Object inReplyToId) {
    this.inReplyToId = inReplyToId;
    return this;
  }

   /**
   * Get inReplyToId
   * @return inReplyToId
  **/
  public Object getInReplyToId() {
    return inReplyToId;
  }

  public void setInReplyToId(Object inReplyToId) {
    this.inReplyToId = inReplyToId;
  }

  public ReviewComment user(Object user) {
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  public Object getUser() {
    return user;
  }

  public void setUser(Object user) {
    this.user = user;
  }

  public ReviewComment body(Object body) {
    this.body = body;
    return this;
  }

   /**
   * Get body
   * @return body
  **/
  public Object getBody() {
    return body;
  }

  public void setBody(Object body) {
    this.body = body;
  }

  public ReviewComment createdAt(Object createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  public Object getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(Object createdAt) {
    this.createdAt = createdAt;
  }

  public ReviewComment updatedAt(Object updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  public Object getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(Object updatedAt) {
    this.updatedAt = updatedAt;
  }

  public ReviewComment htmlUrl(Object htmlUrl) {
    this.htmlUrl = htmlUrl;
    return this;
  }

   /**
   * Get htmlUrl
   * @return htmlUrl
  **/
  public Object getHtmlUrl() {
    return htmlUrl;
  }

  public void setHtmlUrl(Object htmlUrl) {
    this.htmlUrl = htmlUrl;
  }

  public ReviewComment pullRequestUrl(Object pullRequestUrl) {
    this.pullRequestUrl = pullRequestUrl;
    return this;
  }

   /**
   * Get pullRequestUrl
   * @return pullRequestUrl
  **/
  public Object getPullRequestUrl() {
    return pullRequestUrl;
  }

  public void setPullRequestUrl(Object pullRequestUrl) {
    this.pullRequestUrl = pullRequestUrl;
  }

  public ReviewComment authorAssociation(AuthorAssociation authorAssociation) {
    this.authorAssociation = authorAssociation;
    return this;
  }

   /**
   * Get authorAssociation
   * @return authorAssociation
  **/
  public AuthorAssociation getAuthorAssociation() {
    return authorAssociation;
  }

  public void setAuthorAssociation(AuthorAssociation authorAssociation) {
    this.authorAssociation = authorAssociation;
  }

  public ReviewComment _links(ReviewcommentLinks _links) {
    this._links = _links;
    return this;
  }

   /**
   * Get _links
   * @return _links
  **/
  public ReviewcommentLinks getLinks() {
    return _links;
  }

  public void setLinks(ReviewcommentLinks _links) {
    this._links = _links;
  }

  public ReviewComment bodyText(Object bodyText) {
    this.bodyText = bodyText;
    return this;
  }

   /**
   * Get bodyText
   * @return bodyText
  **/
  public Object getBodyText() {
    return bodyText;
  }

  public void setBodyText(Object bodyText) {
    this.bodyText = bodyText;
  }

  public ReviewComment bodyHtml(Object bodyHtml) {
    this.bodyHtml = bodyHtml;
    return this;
  }

   /**
   * Get bodyHtml
   * @return bodyHtml
  **/
  public Object getBodyHtml() {
    return bodyHtml;
  }

  public void setBodyHtml(Object bodyHtml) {
    this.bodyHtml = bodyHtml;
  }

  public ReviewComment reactions(ReactionRollup reactions) {
    this.reactions = reactions;
    return this;
  }

   /**
   * Get reactions
   * @return reactions
  **/
  public ReactionRollup getReactions() {
    return reactions;
  }

  public void setReactions(ReactionRollup reactions) {
    this.reactions = reactions;
  }

  public ReviewComment side(Object side) {
    this.side = side;
    return this;
  }

   /**
   * The side of the first line of the range for a multi-line comment.
   * @return side
  **/
  public Object getSide() {
    return side;
  }

  public void setSide(Object side) {
    this.side = side;
  }

  public ReviewComment startSide(Object startSide) {
    this.startSide = startSide;
    return this;
  }

   /**
   * The side of the first line of the range for a multi-line comment.
   * @return startSide
  **/
  public Object getStartSide() {
    return startSide;
  }

  public void setStartSide(Object startSide) {
    this.startSide = startSide;
  }

  public ReviewComment line(Object line) {
    this.line = line;
    return this;
  }

   /**
   * The line of the blob to which the comment applies. The last line of the range for a multi-line comment
   * @return line
  **/
  public Object getLine() {
    return line;
  }

  public void setLine(Object line) {
    this.line = line;
  }

  public ReviewComment originalLine(Object originalLine) {
    this.originalLine = originalLine;
    return this;
  }

   /**
   * The original line of the blob to which the comment applies. The last line of the range for a multi-line comment
   * @return originalLine
  **/
  public Object getOriginalLine() {
    return originalLine;
  }

  public void setOriginalLine(Object originalLine) {
    this.originalLine = originalLine;
  }

  public ReviewComment startLine(Object startLine) {
    this.startLine = startLine;
    return this;
  }

   /**
   * The first line of the range for a multi-line comment.
   * @return startLine
  **/
  public Object getStartLine() {
    return startLine;
  }

  public void setStartLine(Object startLine) {
    this.startLine = startLine;
  }

  public ReviewComment originalStartLine(Object originalStartLine) {
    this.originalStartLine = originalStartLine;
    return this;
  }

   /**
   * The original first line of the range for a multi-line comment.
   * @return originalStartLine
  **/
  public Object getOriginalStartLine() {
    return originalStartLine;
  }

  public void setOriginalStartLine(Object originalStartLine) {
    this.originalStartLine = originalStartLine;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReviewComment reviewComment = (ReviewComment) o;
    return Objects.equals(this.url, reviewComment.url) &&
        Objects.equals(this.pullRequestReviewId, reviewComment.pullRequestReviewId) &&
        Objects.equals(this.id, reviewComment.id) &&
        Objects.equals(this.nodeId, reviewComment.nodeId) &&
        Objects.equals(this.diffHunk, reviewComment.diffHunk) &&
        Objects.equals(this.path, reviewComment.path) &&
        Objects.equals(this.position, reviewComment.position) &&
        Objects.equals(this.originalPosition, reviewComment.originalPosition) &&
        Objects.equals(this.commitId, reviewComment.commitId) &&
        Objects.equals(this.originalCommitId, reviewComment.originalCommitId) &&
        Objects.equals(this.inReplyToId, reviewComment.inReplyToId) &&
        Objects.equals(this.user, reviewComment.user) &&
        Objects.equals(this.body, reviewComment.body) &&
        Objects.equals(this.createdAt, reviewComment.createdAt) &&
        Objects.equals(this.updatedAt, reviewComment.updatedAt) &&
        Objects.equals(this.htmlUrl, reviewComment.htmlUrl) &&
        Objects.equals(this.pullRequestUrl, reviewComment.pullRequestUrl) &&
        Objects.equals(this.authorAssociation, reviewComment.authorAssociation) &&
        Objects.equals(this._links, reviewComment._links) &&
        Objects.equals(this.bodyText, reviewComment.bodyText) &&
        Objects.equals(this.bodyHtml, reviewComment.bodyHtml) &&
        Objects.equals(this.reactions, reviewComment.reactions) &&
        Objects.equals(this.side, reviewComment.side) &&
        Objects.equals(this.startSide, reviewComment.startSide) &&
        Objects.equals(this.line, reviewComment.line) &&
        Objects.equals(this.originalLine, reviewComment.originalLine) &&
        Objects.equals(this.startLine, reviewComment.startLine) &&
        Objects.equals(this.originalStartLine, reviewComment.originalStartLine);
  }

  @Override
  public int hashCode() {
    return Objects.hash(url, pullRequestReviewId, id, nodeId, diffHunk, path, position, originalPosition, commitId, originalCommitId, inReplyToId, user, body, createdAt, updatedAt, htmlUrl, pullRequestUrl, authorAssociation, _links, bodyText, bodyHtml, reactions, side, startSide, line, originalLine, startLine, originalStartLine);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReviewComment {\n");
    
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    pullRequestReviewId: ").append(toIndentedString(pullRequestReviewId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    nodeId: ").append(toIndentedString(nodeId)).append("\n");
    sb.append("    diffHunk: ").append(toIndentedString(diffHunk)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    position: ").append(toIndentedString(position)).append("\n");
    sb.append("    originalPosition: ").append(toIndentedString(originalPosition)).append("\n");
    sb.append("    commitId: ").append(toIndentedString(commitId)).append("\n");
    sb.append("    originalCommitId: ").append(toIndentedString(originalCommitId)).append("\n");
    sb.append("    inReplyToId: ").append(toIndentedString(inReplyToId)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    htmlUrl: ").append(toIndentedString(htmlUrl)).append("\n");
    sb.append("    pullRequestUrl: ").append(toIndentedString(pullRequestUrl)).append("\n");
    sb.append("    authorAssociation: ").append(toIndentedString(authorAssociation)).append("\n");
    sb.append("    _links: ").append(toIndentedString(_links)).append("\n");
    sb.append("    bodyText: ").append(toIndentedString(bodyText)).append("\n");
    sb.append("    bodyHtml: ").append(toIndentedString(bodyHtml)).append("\n");
    sb.append("    reactions: ").append(toIndentedString(reactions)).append("\n");
    sb.append("    side: ").append(toIndentedString(side)).append("\n");
    sb.append("    startSide: ").append(toIndentedString(startSide)).append("\n");
    sb.append("    line: ").append(toIndentedString(line)).append("\n");
    sb.append("    originalLine: ").append(toIndentedString(originalLine)).append("\n");
    sb.append("    startLine: ").append(toIndentedString(startLine)).append("\n");
    sb.append("    originalStartLine: ").append(toIndentedString(originalStartLine)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
