/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Represents a &#x27;commit&#x27; secret scanning location type. This location type shows that a secret was detected inside a commit to a repository.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class SecretScanningLocationCommit {
  @JsonProperty("path")
  private Object path = null;

  @JsonProperty("start_line")
  private Object startLine = null;

  @JsonProperty("end_line")
  private Object endLine = null;

  @JsonProperty("start_column")
  private Object startColumn = null;

  @JsonProperty("end_column")
  private Object endColumn = null;

  @JsonProperty("blob_sha")
  private Object blobSha = null;

  @JsonProperty("blob_url")
  private Object blobUrl = null;

  @JsonProperty("commit_sha")
  private Object commitSha = null;

  @JsonProperty("commit_url")
  private Object commitUrl = null;

  public SecretScanningLocationCommit path(Object path) {
    this.path = path;
    return this;
  }

   /**
   * The file path in the repository
   * @return path
  **/
  public Object getPath() {
    return path;
  }

  public void setPath(Object path) {
    this.path = path;
  }

  public SecretScanningLocationCommit startLine(Object startLine) {
    this.startLine = startLine;
    return this;
  }

   /**
   * Line number at which the secret starts in the file
   * @return startLine
  **/
  public Object getStartLine() {
    return startLine;
  }

  public void setStartLine(Object startLine) {
    this.startLine = startLine;
  }

  public SecretScanningLocationCommit endLine(Object endLine) {
    this.endLine = endLine;
    return this;
  }

   /**
   * Line number at which the secret ends in the file
   * @return endLine
  **/
  public Object getEndLine() {
    return endLine;
  }

  public void setEndLine(Object endLine) {
    this.endLine = endLine;
  }

  public SecretScanningLocationCommit startColumn(Object startColumn) {
    this.startColumn = startColumn;
    return this;
  }

   /**
   * The column at which the secret starts within the start line when the file is interpreted as 8BIT ASCII
   * @return startColumn
  **/
  public Object getStartColumn() {
    return startColumn;
  }

  public void setStartColumn(Object startColumn) {
    this.startColumn = startColumn;
  }

  public SecretScanningLocationCommit endColumn(Object endColumn) {
    this.endColumn = endColumn;
    return this;
  }

   /**
   * The column at which the secret ends within the end line when the file is interpreted as 8BIT ASCII
   * @return endColumn
  **/
  public Object getEndColumn() {
    return endColumn;
  }

  public void setEndColumn(Object endColumn) {
    this.endColumn = endColumn;
  }

  public SecretScanningLocationCommit blobSha(Object blobSha) {
    this.blobSha = blobSha;
    return this;
  }

   /**
   * SHA-1 hash ID of the associated blob
   * @return blobSha
  **/
  public Object getBlobSha() {
    return blobSha;
  }

  public void setBlobSha(Object blobSha) {
    this.blobSha = blobSha;
  }

  public SecretScanningLocationCommit blobUrl(Object blobUrl) {
    this.blobUrl = blobUrl;
    return this;
  }

   /**
   * The API URL to get the associated blob resource
   * @return blobUrl
  **/
  public Object getBlobUrl() {
    return blobUrl;
  }

  public void setBlobUrl(Object blobUrl) {
    this.blobUrl = blobUrl;
  }

  public SecretScanningLocationCommit commitSha(Object commitSha) {
    this.commitSha = commitSha;
    return this;
  }

   /**
   * SHA-1 hash ID of the associated commit
   * @return commitSha
  **/
  public Object getCommitSha() {
    return commitSha;
  }

  public void setCommitSha(Object commitSha) {
    this.commitSha = commitSha;
  }

  public SecretScanningLocationCommit commitUrl(Object commitUrl) {
    this.commitUrl = commitUrl;
    return this;
  }

   /**
   * The API URL to get the associated commit resource
   * @return commitUrl
  **/
  public Object getCommitUrl() {
    return commitUrl;
  }

  public void setCommitUrl(Object commitUrl) {
    this.commitUrl = commitUrl;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SecretScanningLocationCommit secretScanningLocationCommit = (SecretScanningLocationCommit) o;
    return Objects.equals(this.path, secretScanningLocationCommit.path) &&
        Objects.equals(this.startLine, secretScanningLocationCommit.startLine) &&
        Objects.equals(this.endLine, secretScanningLocationCommit.endLine) &&
        Objects.equals(this.startColumn, secretScanningLocationCommit.startColumn) &&
        Objects.equals(this.endColumn, secretScanningLocationCommit.endColumn) &&
        Objects.equals(this.blobSha, secretScanningLocationCommit.blobSha) &&
        Objects.equals(this.blobUrl, secretScanningLocationCommit.blobUrl) &&
        Objects.equals(this.commitSha, secretScanningLocationCommit.commitSha) &&
        Objects.equals(this.commitUrl, secretScanningLocationCommit.commitUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(path, startLine, endLine, startColumn, endColumn, blobSha, blobUrl, commitSha, commitUrl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SecretScanningLocationCommit {\n");
    
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    startLine: ").append(toIndentedString(startLine)).append("\n");
    sb.append("    endLine: ").append(toIndentedString(endLine)).append("\n");
    sb.append("    startColumn: ").append(toIndentedString(startColumn)).append("\n");
    sb.append("    endColumn: ").append(toIndentedString(endColumn)).append("\n");
    sb.append("    blobSha: ").append(toIndentedString(blobSha)).append("\n");
    sb.append("    blobUrl: ").append(toIndentedString(blobUrl)).append("\n");
    sb.append("    commitSha: ").append(toIndentedString(commitSha)).append("\n");
    sb.append("    commitUrl: ").append(toIndentedString(commitUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
