/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * SecretNameRepositoriesBody3
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class SecretNameRepositoriesBody3 {
  @JsonProperty("selected_repository_ids")
  private Object selectedRepositoryIds = null;

  public SecretNameRepositoriesBody3 selectedRepositoryIds(Object selectedRepositoryIds) {
    this.selectedRepositoryIds = selectedRepositoryIds;
    return this;
  }

   /**
   * An array of repository ids for which a codespace can access the secret. You can manage the list of selected repositories using the [List selected repositories for a user secret](https://docs.github.com/rest/reference/codespaces#list-selected-repositories-for-a-user-secret), [Add a selected repository to a user secret](https://docs.github.com/rest/reference/codespaces#add-a-selected-repository-to-a-user-secret), and [Remove a selected repository from a user secret](https://docs.github.com/rest/reference/codespaces#remove-a-selected-repository-from-a-user-secret) endpoints.
   * @return selectedRepositoryIds
  **/
  public Object getSelectedRepositoryIds() {
    return selectedRepositoryIds;
  }

  public void setSelectedRepositoryIds(Object selectedRepositoryIds) {
    this.selectedRepositoryIds = selectedRepositoryIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SecretNameRepositoriesBody3 secretNameRepositoriesBody3 = (SecretNameRepositoriesBody3) o;
    return Objects.equals(this.selectedRepositoryIds, secretNameRepositoriesBody3.selectedRepositoryIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(selectedRepositoryIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SecretNameRepositoriesBody3 {\n");
    
    sb.append("    selectedRepositoryIds: ").append(toIndentedString(selectedRepositoryIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
