/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.github.api.client.SimpleUser;
import com.github.api.client.TimelinecrossreferencedeventSource;

/**
 * Timeline Cross Referenced Event
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class TimelineCrossReferencedEvent {
  @JsonProperty("event")
  private Object event = null;

  @JsonProperty("actor")
  private SimpleUser actor = null;

  @JsonProperty("created_at")
  private Object createdAt = null;

  @JsonProperty("updated_at")
  private Object updatedAt = null;

  @JsonProperty("source")
  private TimelinecrossreferencedeventSource source = null;

  public TimelineCrossReferencedEvent event(Object event) {
    this.event = event;
    return this;
  }

   /**
   * Get event
   * @return event
  **/
  public Object getEvent() {
    return event;
  }

  public void setEvent(Object event) {
    this.event = event;
  }

  public TimelineCrossReferencedEvent actor(SimpleUser actor) {
    this.actor = actor;
    return this;
  }

   /**
   * Get actor
   * @return actor
  **/
  public SimpleUser getActor() {
    return actor;
  }

  public void setActor(SimpleUser actor) {
    this.actor = actor;
  }

  public TimelineCrossReferencedEvent createdAt(Object createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  public Object getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(Object createdAt) {
    this.createdAt = createdAt;
  }

  public TimelineCrossReferencedEvent updatedAt(Object updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  public Object getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(Object updatedAt) {
    this.updatedAt = updatedAt;
  }

  public TimelineCrossReferencedEvent source(TimelinecrossreferencedeventSource source) {
    this.source = source;
    return this;
  }

   /**
   * Get source
   * @return source
  **/
  public TimelinecrossreferencedeventSource getSource() {
    return source;
  }

  public void setSource(TimelinecrossreferencedeventSource source) {
    this.source = source;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TimelineCrossReferencedEvent timelineCrossReferencedEvent = (TimelineCrossReferencedEvent) o;
    return Objects.equals(this.event, timelineCrossReferencedEvent.event) &&
        Objects.equals(this.actor, timelineCrossReferencedEvent.actor) &&
        Objects.equals(this.createdAt, timelineCrossReferencedEvent.createdAt) &&
        Objects.equals(this.updatedAt, timelineCrossReferencedEvent.updatedAt) &&
        Objects.equals(this.source, timelineCrossReferencedEvent.source);
  }

  @Override
  public int hashCode() {
    return Objects.hash(event, actor, createdAt, updatedAt, source);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TimelineCrossReferencedEvent {\n");
    
    sb.append("    event: ").append(toIndentedString(event)).append("\n");
    sb.append("    actor: ").append(toIndentedString(actor)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
