/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.github.api.client.LabeledissueeventLabel;
import com.github.api.client.SimpleUser;

/**
 * Unlabeled Issue Event
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class UnlabeledIssueEvent {
  @JsonProperty("id")
  private Object id = null;

  @JsonProperty("node_id")
  private Object nodeId = null;

  @JsonProperty("url")
  private Object url = null;

  @JsonProperty("actor")
  private SimpleUser actor = null;

  @JsonProperty("event")
  private Object event = null;

  @JsonProperty("commit_id")
  private Object commitId = null;

  @JsonProperty("commit_url")
  private Object commitUrl = null;

  @JsonProperty("created_at")
  private Object createdAt = null;

  @JsonProperty("performed_via_github_app")
  private Object performedViaGithubApp = null;

  @JsonProperty("label")
  private LabeledissueeventLabel label = null;

  public UnlabeledIssueEvent id(Object id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Object getId() {
    return id;
  }

  public void setId(Object id) {
    this.id = id;
  }

  public UnlabeledIssueEvent nodeId(Object nodeId) {
    this.nodeId = nodeId;
    return this;
  }

   /**
   * Get nodeId
   * @return nodeId
  **/
  public Object getNodeId() {
    return nodeId;
  }

  public void setNodeId(Object nodeId) {
    this.nodeId = nodeId;
  }

  public UnlabeledIssueEvent url(Object url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  public Object getUrl() {
    return url;
  }

  public void setUrl(Object url) {
    this.url = url;
  }

  public UnlabeledIssueEvent actor(SimpleUser actor) {
    this.actor = actor;
    return this;
  }

   /**
   * Get actor
   * @return actor
  **/
  public SimpleUser getActor() {
    return actor;
  }

  public void setActor(SimpleUser actor) {
    this.actor = actor;
  }

  public UnlabeledIssueEvent event(Object event) {
    this.event = event;
    return this;
  }

   /**
   * Get event
   * @return event
  **/
  public Object getEvent() {
    return event;
  }

  public void setEvent(Object event) {
    this.event = event;
  }

  public UnlabeledIssueEvent commitId(Object commitId) {
    this.commitId = commitId;
    return this;
  }

   /**
   * Get commitId
   * @return commitId
  **/
  public Object getCommitId() {
    return commitId;
  }

  public void setCommitId(Object commitId) {
    this.commitId = commitId;
  }

  public UnlabeledIssueEvent commitUrl(Object commitUrl) {
    this.commitUrl = commitUrl;
    return this;
  }

   /**
   * Get commitUrl
   * @return commitUrl
  **/
  public Object getCommitUrl() {
    return commitUrl;
  }

  public void setCommitUrl(Object commitUrl) {
    this.commitUrl = commitUrl;
  }

  public UnlabeledIssueEvent createdAt(Object createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  public Object getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(Object createdAt) {
    this.createdAt = createdAt;
  }

  public UnlabeledIssueEvent performedViaGithubApp(Object performedViaGithubApp) {
    this.performedViaGithubApp = performedViaGithubApp;
    return this;
  }

   /**
   * Get performedViaGithubApp
   * @return performedViaGithubApp
  **/
  public Object getPerformedViaGithubApp() {
    return performedViaGithubApp;
  }

  public void setPerformedViaGithubApp(Object performedViaGithubApp) {
    this.performedViaGithubApp = performedViaGithubApp;
  }

  public UnlabeledIssueEvent label(LabeledissueeventLabel label) {
    this.label = label;
    return this;
  }

   /**
   * Get label
   * @return label
  **/
  public LabeledissueeventLabel getLabel() {
    return label;
  }

  public void setLabel(LabeledissueeventLabel label) {
    this.label = label;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UnlabeledIssueEvent unlabeledIssueEvent = (UnlabeledIssueEvent) o;
    return Objects.equals(this.id, unlabeledIssueEvent.id) &&
        Objects.equals(this.nodeId, unlabeledIssueEvent.nodeId) &&
        Objects.equals(this.url, unlabeledIssueEvent.url) &&
        Objects.equals(this.actor, unlabeledIssueEvent.actor) &&
        Objects.equals(this.event, unlabeledIssueEvent.event) &&
        Objects.equals(this.commitId, unlabeledIssueEvent.commitId) &&
        Objects.equals(this.commitUrl, unlabeledIssueEvent.commitUrl) &&
        Objects.equals(this.createdAt, unlabeledIssueEvent.createdAt) &&
        Objects.equals(this.performedViaGithubApp, unlabeledIssueEvent.performedViaGithubApp) &&
        Objects.equals(this.label, unlabeledIssueEvent.label);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, nodeId, url, actor, event, commitId, commitUrl, createdAt, performedViaGithubApp, label);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UnlabeledIssueEvent {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    nodeId: ").append(toIndentedString(nodeId)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    actor: ").append(toIndentedString(actor)).append("\n");
    sb.append("    event: ").append(toIndentedString(event)).append("\n");
    sb.append("    commitId: ").append(toIndentedString(commitId)).append("\n");
    sb.append("    commitUrl: ").append(toIndentedString(commitUrl)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    performedViaGithubApp: ").append(toIndentedString(performedViaGithubApp)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
