/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.github.api.client.Enterprise;
import com.github.api.client.Installation;
import com.github.api.client.OrganizationSimple;
import com.github.api.client.Repository;
import com.github.api.client.SimpleUser;

/**
 * WebhookInstallationUnsuspend
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class WebhookInstallationUnsuspend {
  @JsonProperty("action")
  private Object action = null;

  @JsonProperty("enterprise")
  private Enterprise enterprise = null;

  @JsonProperty("installation")
  private Installation installation = null;

  @JsonProperty("organization")
  private OrganizationSimple organization = null;

  @JsonProperty("repositories")
  private Object repositories = null;

  @JsonProperty("repository")
  private Repository repository = null;

  @JsonProperty("requester")
  private Object requester = null;

  @JsonProperty("sender")
  private SimpleUser sender = null;

  public WebhookInstallationUnsuspend action(Object action) {
    this.action = action;
    return this;
  }

   /**
   * Get action
   * @return action
  **/
  public Object getAction() {
    return action;
  }

  public void setAction(Object action) {
    this.action = action;
  }

  public WebhookInstallationUnsuspend enterprise(Enterprise enterprise) {
    this.enterprise = enterprise;
    return this;
  }

   /**
   * Get enterprise
   * @return enterprise
  **/
  public Enterprise getEnterprise() {
    return enterprise;
  }

  public void setEnterprise(Enterprise enterprise) {
    this.enterprise = enterprise;
  }

  public WebhookInstallationUnsuspend installation(Installation installation) {
    this.installation = installation;
    return this;
  }

   /**
   * Get installation
   * @return installation
  **/
  public Installation getInstallation() {
    return installation;
  }

  public void setInstallation(Installation installation) {
    this.installation = installation;
  }

  public WebhookInstallationUnsuspend organization(OrganizationSimple organization) {
    this.organization = organization;
    return this;
  }

   /**
   * Get organization
   * @return organization
  **/
  public OrganizationSimple getOrganization() {
    return organization;
  }

  public void setOrganization(OrganizationSimple organization) {
    this.organization = organization;
  }

  public WebhookInstallationUnsuspend repositories(Object repositories) {
    this.repositories = repositories;
    return this;
  }

   /**
   * An array of repository objects that the installation can access.
   * @return repositories
  **/
  public Object getRepositories() {
    return repositories;
  }

  public void setRepositories(Object repositories) {
    this.repositories = repositories;
  }

  public WebhookInstallationUnsuspend repository(Repository repository) {
    this.repository = repository;
    return this;
  }

   /**
   * Get repository
   * @return repository
  **/
  public Repository getRepository() {
    return repository;
  }

  public void setRepository(Repository repository) {
    this.repository = repository;
  }

  public WebhookInstallationUnsuspend requester(Object requester) {
    this.requester = requester;
    return this;
  }

   /**
   * Get requester
   * @return requester
  **/
  public Object getRequester() {
    return requester;
  }

  public void setRequester(Object requester) {
    this.requester = requester;
  }

  public WebhookInstallationUnsuspend sender(SimpleUser sender) {
    this.sender = sender;
    return this;
  }

   /**
   * Get sender
   * @return sender
  **/
  public SimpleUser getSender() {
    return sender;
  }

  public void setSender(SimpleUser sender) {
    this.sender = sender;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookInstallationUnsuspend webhookInstallationUnsuspend = (WebhookInstallationUnsuspend) o;
    return Objects.equals(this.action, webhookInstallationUnsuspend.action) &&
        Objects.equals(this.enterprise, webhookInstallationUnsuspend.enterprise) &&
        Objects.equals(this.installation, webhookInstallationUnsuspend.installation) &&
        Objects.equals(this.organization, webhookInstallationUnsuspend.organization) &&
        Objects.equals(this.repositories, webhookInstallationUnsuspend.repositories) &&
        Objects.equals(this.repository, webhookInstallationUnsuspend.repository) &&
        Objects.equals(this.requester, webhookInstallationUnsuspend.requester) &&
        Objects.equals(this.sender, webhookInstallationUnsuspend.sender);
  }

  @Override
  public int hashCode() {
    return Objects.hash(action, enterprise, installation, organization, repositories, repository, requester, sender);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebhookInstallationUnsuspend {\n");
    
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    enterprise: ").append(toIndentedString(enterprise)).append("\n");
    sb.append("    installation: ").append(toIndentedString(installation)).append("\n");
    sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
    sb.append("    repositories: ").append(toIndentedString(repositories)).append("\n");
    sb.append("    repository: ").append(toIndentedString(repository)).append("\n");
    sb.append("    requester: ").append(toIndentedString(requester)).append("\n");
    sb.append("    sender: ").append(toIndentedString(sender)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
