/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.github.api.client.WebhookrepositoryrenamedChangesRepository;

/**
 * WebhookrepositoryrenamedChanges
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class WebhookrepositoryrenamedChanges {
  @JsonProperty("repository")
  private WebhookrepositoryrenamedChangesRepository repository = null;

  public WebhookrepositoryrenamedChanges repository(WebhookrepositoryrenamedChangesRepository repository) {
    this.repository = repository;
    return this;
  }

   /**
   * Get repository
   * @return repository
  **/
  public WebhookrepositoryrenamedChangesRepository getRepository() {
    return repository;
  }

  public void setRepository(WebhookrepositoryrenamedChangesRepository repository) {
    this.repository = repository;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookrepositoryrenamedChanges webhookrepositoryrenamedChanges = (WebhookrepositoryrenamedChanges) o;
    return Objects.equals(this.repository, webhookrepositoryrenamedChanges.repository);
  }

  @Override
  public int hashCode() {
    return Objects.hash(repository);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebhookrepositoryrenamedChanges {\n");
    
    sb.append("    repository: ").append(toIndentedString(repository)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
