/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.github.api.client.User;
import com.github.api.client.WebhookpackagepublishedPackageRegistry;
import com.github.api.client.WebhookpackageupdatedPackagePackageVersion;

/**
 * Information about the package.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class WebhookpackageupdatedPackage {
  @JsonProperty("created_at")
  private Object createdAt = null;

  @JsonProperty("description")
  private Object description = null;

  @JsonProperty("ecosystem")
  private Object ecosystem = null;

  @JsonProperty("html_url")
  private Object htmlUrl = null;

  @JsonProperty("id")
  private Object id = null;

  @JsonProperty("name")
  private Object name = null;

  @JsonProperty("namespace")
  private Object namespace = null;

  @JsonProperty("owner")
  private User owner = null;

  @JsonProperty("package_type")
  private Object packageType = null;

  @JsonProperty("package_version")
  private WebhookpackageupdatedPackagePackageVersion packageVersion = null;

  @JsonProperty("registry")
  private WebhookpackagepublishedPackageRegistry registry = null;

  @JsonProperty("updated_at")
  private Object updatedAt = null;

  public WebhookpackageupdatedPackage createdAt(Object createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  public Object getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(Object createdAt) {
    this.createdAt = createdAt;
  }

  public WebhookpackageupdatedPackage description(Object description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  public Object getDescription() {
    return description;
  }

  public void setDescription(Object description) {
    this.description = description;
  }

  public WebhookpackageupdatedPackage ecosystem(Object ecosystem) {
    this.ecosystem = ecosystem;
    return this;
  }

   /**
   * Get ecosystem
   * @return ecosystem
  **/
  public Object getEcosystem() {
    return ecosystem;
  }

  public void setEcosystem(Object ecosystem) {
    this.ecosystem = ecosystem;
  }

  public WebhookpackageupdatedPackage htmlUrl(Object htmlUrl) {
    this.htmlUrl = htmlUrl;
    return this;
  }

   /**
   * Get htmlUrl
   * @return htmlUrl
  **/
  public Object getHtmlUrl() {
    return htmlUrl;
  }

  public void setHtmlUrl(Object htmlUrl) {
    this.htmlUrl = htmlUrl;
  }

  public WebhookpackageupdatedPackage id(Object id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Object getId() {
    return id;
  }

  public void setId(Object id) {
    this.id = id;
  }

  public WebhookpackageupdatedPackage name(Object name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public Object getName() {
    return name;
  }

  public void setName(Object name) {
    this.name = name;
  }

  public WebhookpackageupdatedPackage namespace(Object namespace) {
    this.namespace = namespace;
    return this;
  }

   /**
   * Get namespace
   * @return namespace
  **/
  public Object getNamespace() {
    return namespace;
  }

  public void setNamespace(Object namespace) {
    this.namespace = namespace;
  }

  public WebhookpackageupdatedPackage owner(User owner) {
    this.owner = owner;
    return this;
  }

   /**
   * Get owner
   * @return owner
  **/
  public User getOwner() {
    return owner;
  }

  public void setOwner(User owner) {
    this.owner = owner;
  }

  public WebhookpackageupdatedPackage packageType(Object packageType) {
    this.packageType = packageType;
    return this;
  }

   /**
   * Get packageType
   * @return packageType
  **/
  public Object getPackageType() {
    return packageType;
  }

  public void setPackageType(Object packageType) {
    this.packageType = packageType;
  }

  public WebhookpackageupdatedPackage packageVersion(WebhookpackageupdatedPackagePackageVersion packageVersion) {
    this.packageVersion = packageVersion;
    return this;
  }

   /**
   * Get packageVersion
   * @return packageVersion
  **/
  public WebhookpackageupdatedPackagePackageVersion getPackageVersion() {
    return packageVersion;
  }

  public void setPackageVersion(WebhookpackageupdatedPackagePackageVersion packageVersion) {
    this.packageVersion = packageVersion;
  }

  public WebhookpackageupdatedPackage registry(WebhookpackagepublishedPackageRegistry registry) {
    this.registry = registry;
    return this;
  }

   /**
   * Get registry
   * @return registry
  **/
  public WebhookpackagepublishedPackageRegistry getRegistry() {
    return registry;
  }

  public void setRegistry(WebhookpackagepublishedPackageRegistry registry) {
    this.registry = registry;
  }

  public WebhookpackageupdatedPackage updatedAt(Object updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  public Object getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(Object updatedAt) {
    this.updatedAt = updatedAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookpackageupdatedPackage webhookpackageupdatedPackage = (WebhookpackageupdatedPackage) o;
    return Objects.equals(this.createdAt, webhookpackageupdatedPackage.createdAt) &&
        Objects.equals(this.description, webhookpackageupdatedPackage.description) &&
        Objects.equals(this.ecosystem, webhookpackageupdatedPackage.ecosystem) &&
        Objects.equals(this.htmlUrl, webhookpackageupdatedPackage.htmlUrl) &&
        Objects.equals(this.id, webhookpackageupdatedPackage.id) &&
        Objects.equals(this.name, webhookpackageupdatedPackage.name) &&
        Objects.equals(this.namespace, webhookpackageupdatedPackage.namespace) &&
        Objects.equals(this.owner, webhookpackageupdatedPackage.owner) &&
        Objects.equals(this.packageType, webhookpackageupdatedPackage.packageType) &&
        Objects.equals(this.packageVersion, webhookpackageupdatedPackage.packageVersion) &&
        Objects.equals(this.registry, webhookpackageupdatedPackage.registry) &&
        Objects.equals(this.updatedAt, webhookpackageupdatedPackage.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdAt, description, ecosystem, htmlUrl, id, name, namespace, owner, packageType, packageVersion, registry, updatedAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebhookpackageupdatedPackage {\n");
    
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    ecosystem: ").append(toIndentedString(ecosystem)).append("\n");
    sb.append("    htmlUrl: ").append(toIndentedString(htmlUrl)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    namespace: ").append(toIndentedString(namespace)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    packageType: ").append(toIndentedString(packageType)).append("\n");
    sb.append("    packageVersion: ").append(toIndentedString(packageVersion)).append("\n");
    sb.append("    registry: ").append(toIndentedString(registry)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
