/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.github.api.client.OrganizationSimple;
import com.github.api.client.Repository;
import com.github.api.client.SecretScanningAlert;
import com.github.api.client.SecretScanningLocation;
import com.github.api.client.SimpleInstallation;
import com.github.api.client.SimpleUser;

/**
 * WebhookSecretScanningAlertLocationCreated
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class WebhookSecretScanningAlertLocationCreated {
  @JsonProperty("action")
  private Object action = null;

  @JsonProperty("alert")
  private SecretScanningAlert alert = null;

  @JsonProperty("installation")
  private SimpleInstallation installation = null;

  @JsonProperty("location")
  private SecretScanningLocation location = null;

  @JsonProperty("organization")
  private OrganizationSimple organization = null;

  @JsonProperty("repository")
  private Repository repository = null;

  @JsonProperty("sender")
  private SimpleUser sender = null;

  public WebhookSecretScanningAlertLocationCreated action(Object action) {
    this.action = action;
    return this;
  }

   /**
   * Get action
   * @return action
  **/
  public Object getAction() {
    return action;
  }

  public void setAction(Object action) {
    this.action = action;
  }

  public WebhookSecretScanningAlertLocationCreated alert(SecretScanningAlert alert) {
    this.alert = alert;
    return this;
  }

   /**
   * Get alert
   * @return alert
  **/
  public SecretScanningAlert getAlert() {
    return alert;
  }

  public void setAlert(SecretScanningAlert alert) {
    this.alert = alert;
  }

  public WebhookSecretScanningAlertLocationCreated installation(SimpleInstallation installation) {
    this.installation = installation;
    return this;
  }

   /**
   * Get installation
   * @return installation
  **/
  public SimpleInstallation getInstallation() {
    return installation;
  }

  public void setInstallation(SimpleInstallation installation) {
    this.installation = installation;
  }

  public WebhookSecretScanningAlertLocationCreated location(SecretScanningLocation location) {
    this.location = location;
    return this;
  }

   /**
   * Get location
   * @return location
  **/
  public SecretScanningLocation getLocation() {
    return location;
  }

  public void setLocation(SecretScanningLocation location) {
    this.location = location;
  }

  public WebhookSecretScanningAlertLocationCreated organization(OrganizationSimple organization) {
    this.organization = organization;
    return this;
  }

   /**
   * Get organization
   * @return organization
  **/
  public OrganizationSimple getOrganization() {
    return organization;
  }

  public void setOrganization(OrganizationSimple organization) {
    this.organization = organization;
  }

  public WebhookSecretScanningAlertLocationCreated repository(Repository repository) {
    this.repository = repository;
    return this;
  }

   /**
   * Get repository
   * @return repository
  **/
  public Repository getRepository() {
    return repository;
  }

  public void setRepository(Repository repository) {
    this.repository = repository;
  }

  public WebhookSecretScanningAlertLocationCreated sender(SimpleUser sender) {
    this.sender = sender;
    return this;
  }

   /**
   * Get sender
   * @return sender
  **/
  public SimpleUser getSender() {
    return sender;
  }

  public void setSender(SimpleUser sender) {
    this.sender = sender;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookSecretScanningAlertLocationCreated webhookSecretScanningAlertLocationCreated = (WebhookSecretScanningAlertLocationCreated) o;
    return Objects.equals(this.action, webhookSecretScanningAlertLocationCreated.action) &&
        Objects.equals(this.alert, webhookSecretScanningAlertLocationCreated.alert) &&
        Objects.equals(this.installation, webhookSecretScanningAlertLocationCreated.installation) &&
        Objects.equals(this.location, webhookSecretScanningAlertLocationCreated.location) &&
        Objects.equals(this.organization, webhookSecretScanningAlertLocationCreated.organization) &&
        Objects.equals(this.repository, webhookSecretScanningAlertLocationCreated.repository) &&
        Objects.equals(this.sender, webhookSecretScanningAlertLocationCreated.sender);
  }

  @Override
  public int hashCode() {
    return Objects.hash(action, alert, installation, location, organization, repository, sender);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebhookSecretScanningAlertLocationCreated {\n");
    
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    alert: ").append(toIndentedString(alert)).append("\n");
    sb.append("    installation: ").append(toIndentedString(installation)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
    sb.append("    repository: ").append(toIndentedString(repository)).append("\n");
    sb.append("    sender: ").append(toIndentedString(sender)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
