/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.github.api.client.Enterprise;
import com.github.api.client.OrganizationSimple;
import com.github.api.client.Project;
import com.github.api.client.Repository;
import com.github.api.client.SimpleInstallation;
import com.github.api.client.SimpleUser;
import com.github.api.client.WebhookprojecteditedChanges;

/**
 * WebhookProjectEdited
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class WebhookProjectEdited {
  @JsonProperty("action")
  private Object action = null;

  @JsonProperty("changes")
  private WebhookprojecteditedChanges changes = null;

  @JsonProperty("enterprise")
  private Enterprise enterprise = null;

  @JsonProperty("installation")
  private SimpleInstallation installation = null;

  @JsonProperty("organization")
  private OrganizationSimple organization = null;

  @JsonProperty("project")
  private Project project = null;

  @JsonProperty("repository")
  private Repository repository = null;

  @JsonProperty("sender")
  private SimpleUser sender = null;

  public WebhookProjectEdited action(Object action) {
    this.action = action;
    return this;
  }

   /**
   * Get action
   * @return action
  **/
  public Object getAction() {
    return action;
  }

  public void setAction(Object action) {
    this.action = action;
  }

  public WebhookProjectEdited changes(WebhookprojecteditedChanges changes) {
    this.changes = changes;
    return this;
  }

   /**
   * Get changes
   * @return changes
  **/
  public WebhookprojecteditedChanges getChanges() {
    return changes;
  }

  public void setChanges(WebhookprojecteditedChanges changes) {
    this.changes = changes;
  }

  public WebhookProjectEdited enterprise(Enterprise enterprise) {
    this.enterprise = enterprise;
    return this;
  }

   /**
   * Get enterprise
   * @return enterprise
  **/
  public Enterprise getEnterprise() {
    return enterprise;
  }

  public void setEnterprise(Enterprise enterprise) {
    this.enterprise = enterprise;
  }

  public WebhookProjectEdited installation(SimpleInstallation installation) {
    this.installation = installation;
    return this;
  }

   /**
   * Get installation
   * @return installation
  **/
  public SimpleInstallation getInstallation() {
    return installation;
  }

  public void setInstallation(SimpleInstallation installation) {
    this.installation = installation;
  }

  public WebhookProjectEdited organization(OrganizationSimple organization) {
    this.organization = organization;
    return this;
  }

   /**
   * Get organization
   * @return organization
  **/
  public OrganizationSimple getOrganization() {
    return organization;
  }

  public void setOrganization(OrganizationSimple organization) {
    this.organization = organization;
  }

  public WebhookProjectEdited project(Project project) {
    this.project = project;
    return this;
  }

   /**
   * Get project
   * @return project
  **/
  public Project getProject() {
    return project;
  }

  public void setProject(Project project) {
    this.project = project;
  }

  public WebhookProjectEdited repository(Repository repository) {
    this.repository = repository;
    return this;
  }

   /**
   * Get repository
   * @return repository
  **/
  public Repository getRepository() {
    return repository;
  }

  public void setRepository(Repository repository) {
    this.repository = repository;
  }

  public WebhookProjectEdited sender(SimpleUser sender) {
    this.sender = sender;
    return this;
  }

   /**
   * Get sender
   * @return sender
  **/
  public SimpleUser getSender() {
    return sender;
  }

  public void setSender(SimpleUser sender) {
    this.sender = sender;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookProjectEdited webhookProjectEdited = (WebhookProjectEdited) o;
    return Objects.equals(this.action, webhookProjectEdited.action) &&
        Objects.equals(this.changes, webhookProjectEdited.changes) &&
        Objects.equals(this.enterprise, webhookProjectEdited.enterprise) &&
        Objects.equals(this.installation, webhookProjectEdited.installation) &&
        Objects.equals(this.organization, webhookProjectEdited.organization) &&
        Objects.equals(this.project, webhookProjectEdited.project) &&
        Objects.equals(this.repository, webhookProjectEdited.repository) &&
        Objects.equals(this.sender, webhookProjectEdited.sender);
  }

  @Override
  public int hashCode() {
    return Objects.hash(action, changes, enterprise, installation, organization, project, repository, sender);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebhookProjectEdited {\n");
    
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    changes: ").append(toIndentedString(changes)).append("\n");
    sb.append("    enterprise: ").append(toIndentedString(enterprise)).append("\n");
    sb.append("    installation: ").append(toIndentedString(installation)).append("\n");
    sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
    sb.append("    project: ").append(toIndentedString(project)).append("\n");
    sb.append("    repository: ").append(toIndentedString(repository)).append("\n");
    sb.append("    sender: ").append(toIndentedString(sender)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
