/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.github.api.client.Enterprise;
import com.github.api.client.OrganizationSimple;
import com.github.api.client.Repository;
import com.github.api.client.SimpleInstallation;
import com.github.api.client.SimpleUser;
import com.github.api.client.User;
import com.github.api.client.WebhookorganizationmemberinvitedInvitation;

/**
 * WebhookOrganizationMemberInvited
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class WebhookOrganizationMemberInvited {
  @JsonProperty("action")
  private Object action = null;

  @JsonProperty("enterprise")
  private Enterprise enterprise = null;

  @JsonProperty("installation")
  private SimpleInstallation installation = null;

  @JsonProperty("invitation")
  private WebhookorganizationmemberinvitedInvitation invitation = null;

  @JsonProperty("organization")
  private OrganizationSimple organization = null;

  @JsonProperty("repository")
  private Repository repository = null;

  @JsonProperty("sender")
  private SimpleUser sender = null;

  @JsonProperty("user")
  private User user = null;

  public WebhookOrganizationMemberInvited action(Object action) {
    this.action = action;
    return this;
  }

   /**
   * Get action
   * @return action
  **/
  public Object getAction() {
    return action;
  }

  public void setAction(Object action) {
    this.action = action;
  }

  public WebhookOrganizationMemberInvited enterprise(Enterprise enterprise) {
    this.enterprise = enterprise;
    return this;
  }

   /**
   * Get enterprise
   * @return enterprise
  **/
  public Enterprise getEnterprise() {
    return enterprise;
  }

  public void setEnterprise(Enterprise enterprise) {
    this.enterprise = enterprise;
  }

  public WebhookOrganizationMemberInvited installation(SimpleInstallation installation) {
    this.installation = installation;
    return this;
  }

   /**
   * Get installation
   * @return installation
  **/
  public SimpleInstallation getInstallation() {
    return installation;
  }

  public void setInstallation(SimpleInstallation installation) {
    this.installation = installation;
  }

  public WebhookOrganizationMemberInvited invitation(WebhookorganizationmemberinvitedInvitation invitation) {
    this.invitation = invitation;
    return this;
  }

   /**
   * Get invitation
   * @return invitation
  **/
  public WebhookorganizationmemberinvitedInvitation getInvitation() {
    return invitation;
  }

  public void setInvitation(WebhookorganizationmemberinvitedInvitation invitation) {
    this.invitation = invitation;
  }

  public WebhookOrganizationMemberInvited organization(OrganizationSimple organization) {
    this.organization = organization;
    return this;
  }

   /**
   * Get organization
   * @return organization
  **/
  public OrganizationSimple getOrganization() {
    return organization;
  }

  public void setOrganization(OrganizationSimple organization) {
    this.organization = organization;
  }

  public WebhookOrganizationMemberInvited repository(Repository repository) {
    this.repository = repository;
    return this;
  }

   /**
   * Get repository
   * @return repository
  **/
  public Repository getRepository() {
    return repository;
  }

  public void setRepository(Repository repository) {
    this.repository = repository;
  }

  public WebhookOrganizationMemberInvited sender(SimpleUser sender) {
    this.sender = sender;
    return this;
  }

   /**
   * Get sender
   * @return sender
  **/
  public SimpleUser getSender() {
    return sender;
  }

  public void setSender(SimpleUser sender) {
    this.sender = sender;
  }

  public WebhookOrganizationMemberInvited user(User user) {
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  public User getUser() {
    return user;
  }

  public void setUser(User user) {
    this.user = user;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookOrganizationMemberInvited webhookOrganizationMemberInvited = (WebhookOrganizationMemberInvited) o;
    return Objects.equals(this.action, webhookOrganizationMemberInvited.action) &&
        Objects.equals(this.enterprise, webhookOrganizationMemberInvited.enterprise) &&
        Objects.equals(this.installation, webhookOrganizationMemberInvited.installation) &&
        Objects.equals(this.invitation, webhookOrganizationMemberInvited.invitation) &&
        Objects.equals(this.organization, webhookOrganizationMemberInvited.organization) &&
        Objects.equals(this.repository, webhookOrganizationMemberInvited.repository) &&
        Objects.equals(this.sender, webhookOrganizationMemberInvited.sender) &&
        Objects.equals(this.user, webhookOrganizationMemberInvited.user);
  }

  @Override
  public int hashCode() {
    return Objects.hash(action, enterprise, installation, invitation, organization, repository, sender, user);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebhookOrganizationMemberInvited {\n");
    
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    enterprise: ").append(toIndentedString(enterprise)).append("\n");
    sb.append("    installation: ").append(toIndentedString(installation)).append("\n");
    sb.append("    invitation: ").append(toIndentedString(invitation)).append("\n");
    sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
    sb.append("    repository: ").append(toIndentedString(repository)).append("\n");
    sb.append("    sender: ").append(toIndentedString(sender)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
