/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.github.api.client.Enterprise;
import com.github.api.client.OrganizationSimple;
import com.github.api.client.Repository;
import com.github.api.client.SimpleInstallation;
import com.github.api.client.SimplePullRequest3;
import com.github.api.client.SimpleUser;
import com.github.api.client.WebhookpullrequestreviewthreadresolvedThread;

/**
 * WebhookPullRequestReviewThreadResolved
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class WebhookPullRequestReviewThreadResolved {
  @JsonProperty("action")
  private Object action = null;

  @JsonProperty("enterprise")
  private Enterprise enterprise = null;

  @JsonProperty("installation")
  private SimpleInstallation installation = null;

  @JsonProperty("organization")
  private OrganizationSimple organization = null;

  @JsonProperty("pull_request")
  private SimplePullRequest3 pullRequest = null;

  @JsonProperty("repository")
  private Repository repository = null;

  @JsonProperty("sender")
  private SimpleUser sender = null;

  @JsonProperty("thread")
  private WebhookpullrequestreviewthreadresolvedThread thread = null;

  public WebhookPullRequestReviewThreadResolved action(Object action) {
    this.action = action;
    return this;
  }

   /**
   * Get action
   * @return action
  **/
  public Object getAction() {
    return action;
  }

  public void setAction(Object action) {
    this.action = action;
  }

  public WebhookPullRequestReviewThreadResolved enterprise(Enterprise enterprise) {
    this.enterprise = enterprise;
    return this;
  }

   /**
   * Get enterprise
   * @return enterprise
  **/
  public Enterprise getEnterprise() {
    return enterprise;
  }

  public void setEnterprise(Enterprise enterprise) {
    this.enterprise = enterprise;
  }

  public WebhookPullRequestReviewThreadResolved installation(SimpleInstallation installation) {
    this.installation = installation;
    return this;
  }

   /**
   * Get installation
   * @return installation
  **/
  public SimpleInstallation getInstallation() {
    return installation;
  }

  public void setInstallation(SimpleInstallation installation) {
    this.installation = installation;
  }

  public WebhookPullRequestReviewThreadResolved organization(OrganizationSimple organization) {
    this.organization = organization;
    return this;
  }

   /**
   * Get organization
   * @return organization
  **/
  public OrganizationSimple getOrganization() {
    return organization;
  }

  public void setOrganization(OrganizationSimple organization) {
    this.organization = organization;
  }

  public WebhookPullRequestReviewThreadResolved pullRequest(SimplePullRequest3 pullRequest) {
    this.pullRequest = pullRequest;
    return this;
  }

   /**
   * Get pullRequest
   * @return pullRequest
  **/
  public SimplePullRequest3 getPullRequest() {
    return pullRequest;
  }

  public void setPullRequest(SimplePullRequest3 pullRequest) {
    this.pullRequest = pullRequest;
  }

  public WebhookPullRequestReviewThreadResolved repository(Repository repository) {
    this.repository = repository;
    return this;
  }

   /**
   * Get repository
   * @return repository
  **/
  public Repository getRepository() {
    return repository;
  }

  public void setRepository(Repository repository) {
    this.repository = repository;
  }

  public WebhookPullRequestReviewThreadResolved sender(SimpleUser sender) {
    this.sender = sender;
    return this;
  }

   /**
   * Get sender
   * @return sender
  **/
  public SimpleUser getSender() {
    return sender;
  }

  public void setSender(SimpleUser sender) {
    this.sender = sender;
  }

  public WebhookPullRequestReviewThreadResolved thread(WebhookpullrequestreviewthreadresolvedThread thread) {
    this.thread = thread;
    return this;
  }

   /**
   * Get thread
   * @return thread
  **/
  public WebhookpullrequestreviewthreadresolvedThread getThread() {
    return thread;
  }

  public void setThread(WebhookpullrequestreviewthreadresolvedThread thread) {
    this.thread = thread;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookPullRequestReviewThreadResolved webhookPullRequestReviewThreadResolved = (WebhookPullRequestReviewThreadResolved) o;
    return Objects.equals(this.action, webhookPullRequestReviewThreadResolved.action) &&
        Objects.equals(this.enterprise, webhookPullRequestReviewThreadResolved.enterprise) &&
        Objects.equals(this.installation, webhookPullRequestReviewThreadResolved.installation) &&
        Objects.equals(this.organization, webhookPullRequestReviewThreadResolved.organization) &&
        Objects.equals(this.pullRequest, webhookPullRequestReviewThreadResolved.pullRequest) &&
        Objects.equals(this.repository, webhookPullRequestReviewThreadResolved.repository) &&
        Objects.equals(this.sender, webhookPullRequestReviewThreadResolved.sender) &&
        Objects.equals(this.thread, webhookPullRequestReviewThreadResolved.thread);
  }

  @Override
  public int hashCode() {
    return Objects.hash(action, enterprise, installation, organization, pullRequest, repository, sender, thread);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebhookPullRequestReviewThreadResolved {\n");
    
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    enterprise: ").append(toIndentedString(enterprise)).append("\n");
    sb.append("    installation: ").append(toIndentedString(installation)).append("\n");
    sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
    sb.append("    pullRequest: ").append(toIndentedString(pullRequest)).append("\n");
    sb.append("    repository: ").append(toIndentedString(repository)).append("\n");
    sb.append("    sender: ").append(toIndentedString(sender)).append("\n");
    sb.append("    thread: ").append(toIndentedString(thread)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
