/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.github.api.client.WebhookbranchprotectionruleeditedChangesAdminEnforced;

/**
 * WebhookinstallationtargetrenamedChanges
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class WebhookinstallationtargetrenamedChanges {
  @JsonProperty("login")
  private WebhookbranchprotectionruleeditedChangesAdminEnforced login = null;

  @JsonProperty("slug")
  private WebhookbranchprotectionruleeditedChangesAdminEnforced slug = null;

  public WebhookinstallationtargetrenamedChanges login(WebhookbranchprotectionruleeditedChangesAdminEnforced login) {
    this.login = login;
    return this;
  }

   /**
   * Get login
   * @return login
  **/
  public WebhookbranchprotectionruleeditedChangesAdminEnforced getLogin() {
    return login;
  }

  public void setLogin(WebhookbranchprotectionruleeditedChangesAdminEnforced login) {
    this.login = login;
  }

  public WebhookinstallationtargetrenamedChanges slug(WebhookbranchprotectionruleeditedChangesAdminEnforced slug) {
    this.slug = slug;
    return this;
  }

   /**
   * Get slug
   * @return slug
  **/
  public WebhookbranchprotectionruleeditedChangesAdminEnforced getSlug() {
    return slug;
  }

  public void setSlug(WebhookbranchprotectionruleeditedChangesAdminEnforced slug) {
    this.slug = slug;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookinstallationtargetrenamedChanges webhookinstallationtargetrenamedChanges = (WebhookinstallationtargetrenamedChanges) o;
    return Objects.equals(this.login, webhookinstallationtargetrenamedChanges.login) &&
        Objects.equals(this.slug, webhookinstallationtargetrenamedChanges.slug);
  }

  @Override
  public int hashCode() {
    return Objects.hash(login, slug);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebhookinstallationtargetrenamedChanges {\n");
    
    sb.append("    login: ").append(toIndentedString(login)).append("\n");
    sb.append("    slug: ").append(toIndentedString(slug)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
