/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.github.api.client.Issue4;
import com.github.api.client.Repository;

/**
 * WebhookissuestransferredChanges
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class WebhookissuestransferredChanges {
  @JsonProperty("new_issue")
  private Issue4 newIssue = null;

  @JsonProperty("new_repository")
  private Repository newRepository = null;

  public WebhookissuestransferredChanges newIssue(Issue4 newIssue) {
    this.newIssue = newIssue;
    return this;
  }

   /**
   * Get newIssue
   * @return newIssue
  **/
  public Issue4 getNewIssue() {
    return newIssue;
  }

  public void setNewIssue(Issue4 newIssue) {
    this.newIssue = newIssue;
  }

  public WebhookissuestransferredChanges newRepository(Repository newRepository) {
    this.newRepository = newRepository;
    return this;
  }

   /**
   * Get newRepository
   * @return newRepository
  **/
  public Repository getNewRepository() {
    return newRepository;
  }

  public void setNewRepository(Repository newRepository) {
    this.newRepository = newRepository;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookissuestransferredChanges webhookissuestransferredChanges = (WebhookissuestransferredChanges) o;
    return Objects.equals(this.newIssue, webhookissuestransferredChanges.newIssue) &&
        Objects.equals(this.newRepository, webhookissuestransferredChanges.newRepository);
  }

  @Override
  public int hashCode() {
    return Objects.hash(newIssue, newRepository);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebhookissuestransferredChanges {\n");
    
    sb.append("    newIssue: ").append(toIndentedString(newIssue)).append("\n");
    sb.append("    newRepository: ").append(toIndentedString(newRepository)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
