/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * WebhookworkflowjobqueuedWorkflowJob
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class WebhookworkflowjobqueuedWorkflowJob {
  @JsonProperty("check_run_url")
  private Object checkRunUrl = null;

  @JsonProperty("completed_at")
  private Object completedAt = null;

  @JsonProperty("conclusion")
  private Object conclusion = null;

  @JsonProperty("head_sha")
  private Object headSha = null;

  @JsonProperty("html_url")
  private Object htmlUrl = null;

  @JsonProperty("id")
  private Object id = null;

  @JsonProperty("labels")
  private Object labels = null;

  @JsonProperty("name")
  private Object name = null;

  @JsonProperty("node_id")
  private Object nodeId = null;

  @JsonProperty("run_attempt")
  private Object runAttempt = null;

  @JsonProperty("run_id")
  private Object runId = null;

  @JsonProperty("run_url")
  private Object runUrl = null;

  @JsonProperty("runner_group_id")
  private Object runnerGroupId = null;

  @JsonProperty("runner_group_name")
  private Object runnerGroupName = null;

  @JsonProperty("runner_id")
  private Object runnerId = null;

  @JsonProperty("runner_name")
  private Object runnerName = null;

  @JsonProperty("started_at")
  private Object startedAt = null;

  @JsonProperty("status")
  private Object status = null;

  @JsonProperty("steps")
  private Object steps = null;

  @JsonProperty("url")
  private Object url = null;

  public WebhookworkflowjobqueuedWorkflowJob checkRunUrl(Object checkRunUrl) {
    this.checkRunUrl = checkRunUrl;
    return this;
  }

   /**
   * Get checkRunUrl
   * @return checkRunUrl
  **/
  public Object getCheckRunUrl() {
    return checkRunUrl;
  }

  public void setCheckRunUrl(Object checkRunUrl) {
    this.checkRunUrl = checkRunUrl;
  }

  public WebhookworkflowjobqueuedWorkflowJob completedAt(Object completedAt) {
    this.completedAt = completedAt;
    return this;
  }

   /**
   * Get completedAt
   * @return completedAt
  **/
  public Object getCompletedAt() {
    return completedAt;
  }

  public void setCompletedAt(Object completedAt) {
    this.completedAt = completedAt;
  }

  public WebhookworkflowjobqueuedWorkflowJob conclusion(Object conclusion) {
    this.conclusion = conclusion;
    return this;
  }

   /**
   * Get conclusion
   * @return conclusion
  **/
  public Object getConclusion() {
    return conclusion;
  }

  public void setConclusion(Object conclusion) {
    this.conclusion = conclusion;
  }

  public WebhookworkflowjobqueuedWorkflowJob headSha(Object headSha) {
    this.headSha = headSha;
    return this;
  }

   /**
   * Get headSha
   * @return headSha
  **/
  public Object getHeadSha() {
    return headSha;
  }

  public void setHeadSha(Object headSha) {
    this.headSha = headSha;
  }

  public WebhookworkflowjobqueuedWorkflowJob htmlUrl(Object htmlUrl) {
    this.htmlUrl = htmlUrl;
    return this;
  }

   /**
   * Get htmlUrl
   * @return htmlUrl
  **/
  public Object getHtmlUrl() {
    return htmlUrl;
  }

  public void setHtmlUrl(Object htmlUrl) {
    this.htmlUrl = htmlUrl;
  }

  public WebhookworkflowjobqueuedWorkflowJob id(Object id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Object getId() {
    return id;
  }

  public void setId(Object id) {
    this.id = id;
  }

  public WebhookworkflowjobqueuedWorkflowJob labels(Object labels) {
    this.labels = labels;
    return this;
  }

   /**
   * Get labels
   * @return labels
  **/
  public Object getLabels() {
    return labels;
  }

  public void setLabels(Object labels) {
    this.labels = labels;
  }

  public WebhookworkflowjobqueuedWorkflowJob name(Object name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public Object getName() {
    return name;
  }

  public void setName(Object name) {
    this.name = name;
  }

  public WebhookworkflowjobqueuedWorkflowJob nodeId(Object nodeId) {
    this.nodeId = nodeId;
    return this;
  }

   /**
   * Get nodeId
   * @return nodeId
  **/
  public Object getNodeId() {
    return nodeId;
  }

  public void setNodeId(Object nodeId) {
    this.nodeId = nodeId;
  }

  public WebhookworkflowjobqueuedWorkflowJob runAttempt(Object runAttempt) {
    this.runAttempt = runAttempt;
    return this;
  }

   /**
   * Get runAttempt
   * @return runAttempt
  **/
  public Object getRunAttempt() {
    return runAttempt;
  }

  public void setRunAttempt(Object runAttempt) {
    this.runAttempt = runAttempt;
  }

  public WebhookworkflowjobqueuedWorkflowJob runId(Object runId) {
    this.runId = runId;
    return this;
  }

   /**
   * Get runId
   * @return runId
  **/
  public Object getRunId() {
    return runId;
  }

  public void setRunId(Object runId) {
    this.runId = runId;
  }

  public WebhookworkflowjobqueuedWorkflowJob runUrl(Object runUrl) {
    this.runUrl = runUrl;
    return this;
  }

   /**
   * Get runUrl
   * @return runUrl
  **/
  public Object getRunUrl() {
    return runUrl;
  }

  public void setRunUrl(Object runUrl) {
    this.runUrl = runUrl;
  }

  public WebhookworkflowjobqueuedWorkflowJob runnerGroupId(Object runnerGroupId) {
    this.runnerGroupId = runnerGroupId;
    return this;
  }

   /**
   * Get runnerGroupId
   * @return runnerGroupId
  **/
  public Object getRunnerGroupId() {
    return runnerGroupId;
  }

  public void setRunnerGroupId(Object runnerGroupId) {
    this.runnerGroupId = runnerGroupId;
  }

  public WebhookworkflowjobqueuedWorkflowJob runnerGroupName(Object runnerGroupName) {
    this.runnerGroupName = runnerGroupName;
    return this;
  }

   /**
   * Get runnerGroupName
   * @return runnerGroupName
  **/
  public Object getRunnerGroupName() {
    return runnerGroupName;
  }

  public void setRunnerGroupName(Object runnerGroupName) {
    this.runnerGroupName = runnerGroupName;
  }

  public WebhookworkflowjobqueuedWorkflowJob runnerId(Object runnerId) {
    this.runnerId = runnerId;
    return this;
  }

   /**
   * Get runnerId
   * @return runnerId
  **/
  public Object getRunnerId() {
    return runnerId;
  }

  public void setRunnerId(Object runnerId) {
    this.runnerId = runnerId;
  }

  public WebhookworkflowjobqueuedWorkflowJob runnerName(Object runnerName) {
    this.runnerName = runnerName;
    return this;
  }

   /**
   * Get runnerName
   * @return runnerName
  **/
  public Object getRunnerName() {
    return runnerName;
  }

  public void setRunnerName(Object runnerName) {
    this.runnerName = runnerName;
  }

  public WebhookworkflowjobqueuedWorkflowJob startedAt(Object startedAt) {
    this.startedAt = startedAt;
    return this;
  }

   /**
   * Get startedAt
   * @return startedAt
  **/
  public Object getStartedAt() {
    return startedAt;
  }

  public void setStartedAt(Object startedAt) {
    this.startedAt = startedAt;
  }

  public WebhookworkflowjobqueuedWorkflowJob status(Object status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  public Object getStatus() {
    return status;
  }

  public void setStatus(Object status) {
    this.status = status;
  }

  public WebhookworkflowjobqueuedWorkflowJob steps(Object steps) {
    this.steps = steps;
    return this;
  }

   /**
   * Get steps
   * @return steps
  **/
  public Object getSteps() {
    return steps;
  }

  public void setSteps(Object steps) {
    this.steps = steps;
  }

  public WebhookworkflowjobqueuedWorkflowJob url(Object url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  public Object getUrl() {
    return url;
  }

  public void setUrl(Object url) {
    this.url = url;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookworkflowjobqueuedWorkflowJob webhookworkflowjobqueuedWorkflowJob = (WebhookworkflowjobqueuedWorkflowJob) o;
    return Objects.equals(this.checkRunUrl, webhookworkflowjobqueuedWorkflowJob.checkRunUrl) &&
        Objects.equals(this.completedAt, webhookworkflowjobqueuedWorkflowJob.completedAt) &&
        Objects.equals(this.conclusion, webhookworkflowjobqueuedWorkflowJob.conclusion) &&
        Objects.equals(this.headSha, webhookworkflowjobqueuedWorkflowJob.headSha) &&
        Objects.equals(this.htmlUrl, webhookworkflowjobqueuedWorkflowJob.htmlUrl) &&
        Objects.equals(this.id, webhookworkflowjobqueuedWorkflowJob.id) &&
        Objects.equals(this.labels, webhookworkflowjobqueuedWorkflowJob.labels) &&
        Objects.equals(this.name, webhookworkflowjobqueuedWorkflowJob.name) &&
        Objects.equals(this.nodeId, webhookworkflowjobqueuedWorkflowJob.nodeId) &&
        Objects.equals(this.runAttempt, webhookworkflowjobqueuedWorkflowJob.runAttempt) &&
        Objects.equals(this.runId, webhookworkflowjobqueuedWorkflowJob.runId) &&
        Objects.equals(this.runUrl, webhookworkflowjobqueuedWorkflowJob.runUrl) &&
        Objects.equals(this.runnerGroupId, webhookworkflowjobqueuedWorkflowJob.runnerGroupId) &&
        Objects.equals(this.runnerGroupName, webhookworkflowjobqueuedWorkflowJob.runnerGroupName) &&
        Objects.equals(this.runnerId, webhookworkflowjobqueuedWorkflowJob.runnerId) &&
        Objects.equals(this.runnerName, webhookworkflowjobqueuedWorkflowJob.runnerName) &&
        Objects.equals(this.startedAt, webhookworkflowjobqueuedWorkflowJob.startedAt) &&
        Objects.equals(this.status, webhookworkflowjobqueuedWorkflowJob.status) &&
        Objects.equals(this.steps, webhookworkflowjobqueuedWorkflowJob.steps) &&
        Objects.equals(this.url, webhookworkflowjobqueuedWorkflowJob.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(checkRunUrl, completedAt, conclusion, headSha, htmlUrl, id, labels, name, nodeId, runAttempt, runId, runUrl, runnerGroupId, runnerGroupName, runnerId, runnerName, startedAt, status, steps, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebhookworkflowjobqueuedWorkflowJob {\n");
    
    sb.append("    checkRunUrl: ").append(toIndentedString(checkRunUrl)).append("\n");
    sb.append("    completedAt: ").append(toIndentedString(completedAt)).append("\n");
    sb.append("    conclusion: ").append(toIndentedString(conclusion)).append("\n");
    sb.append("    headSha: ").append(toIndentedString(headSha)).append("\n");
    sb.append("    htmlUrl: ").append(toIndentedString(htmlUrl)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    nodeId: ").append(toIndentedString(nodeId)).append("\n");
    sb.append("    runAttempt: ").append(toIndentedString(runAttempt)).append("\n");
    sb.append("    runId: ").append(toIndentedString(runId)).append("\n");
    sb.append("    runUrl: ").append(toIndentedString(runUrl)).append("\n");
    sb.append("    runnerGroupId: ").append(toIndentedString(runnerGroupId)).append("\n");
    sb.append("    runnerGroupName: ").append(toIndentedString(runnerGroupName)).append("\n");
    sb.append("    runnerId: ").append(toIndentedString(runnerId)).append("\n");
    sb.append("    runnerName: ").append(toIndentedString(runnerName)).append("\n");
    sb.append("    startedAt: ").append(toIndentedString(startedAt)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    steps: ").append(toIndentedString(steps)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
