/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * WebhookpackagepublishedPackagePackageVersionNpmMetadata
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class WebhookpackagepublishedPackagePackageVersionNpmMetadata {
  @JsonProperty("name")
  private Object name = null;

  @JsonProperty("version")
  private Object version = null;

  @JsonProperty("npm_user")
  private Object npmUser = null;

  @JsonProperty("author")
  private Object author = null;

  @JsonProperty("bugs")
  private Object bugs = null;

  @JsonProperty("dependencies")
  private Object dependencies = null;

  @JsonProperty("dev_dependencies")
  private Object devDependencies = null;

  @JsonProperty("peer_dependencies")
  private Object peerDependencies = null;

  @JsonProperty("optional_dependencies")
  private Object optionalDependencies = null;

  @JsonProperty("description")
  private Object description = null;

  @JsonProperty("dist")
  private Object dist = null;

  @JsonProperty("git_head")
  private Object gitHead = null;

  @JsonProperty("homepage")
  private Object homepage = null;

  @JsonProperty("license")
  private Object license = null;

  @JsonProperty("main")
  private Object main = null;

  @JsonProperty("repository")
  private Object repository = null;

  @JsonProperty("scripts")
  private Object scripts = null;

  @JsonProperty("id")
  private Object id = null;

  @JsonProperty("node_version")
  private Object nodeVersion = null;

  @JsonProperty("npm_version")
  private Object npmVersion = null;

  @JsonProperty("has_shrinkwrap")
  private Object hasShrinkwrap = null;

  @JsonProperty("maintainers")
  private Object maintainers = null;

  @JsonProperty("contributors")
  private Object contributors = null;

  @JsonProperty("engines")
  private Object engines = null;

  @JsonProperty("keywords")
  private Object keywords = null;

  @JsonProperty("files")
  private Object files = null;

  @JsonProperty("bin")
  private Object bin = null;

  @JsonProperty("man")
  private Object man = null;

  @JsonProperty("directories")
  private Object directories = null;

  @JsonProperty("os")
  private Object os = null;

  @JsonProperty("cpu")
  private Object cpu = null;

  @JsonProperty("readme")
  private Object readme = null;

  @JsonProperty("installation_command")
  private Object installationCommand = null;

  @JsonProperty("release_id")
  private Object releaseId = null;

  @JsonProperty("commit_oid")
  private Object commitOid = null;

  @JsonProperty("published_via_actions")
  private Object publishedViaActions = null;

  @JsonProperty("deleted_by_id")
  private Object deletedById = null;

  public WebhookpackagepublishedPackagePackageVersionNpmMetadata name(Object name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public Object getName() {
    return name;
  }

  public void setName(Object name) {
    this.name = name;
  }

  public WebhookpackagepublishedPackagePackageVersionNpmMetadata version(Object version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  public Object getVersion() {
    return version;
  }

  public void setVersion(Object version) {
    this.version = version;
  }

  public WebhookpackagepublishedPackagePackageVersionNpmMetadata npmUser(Object npmUser) {
    this.npmUser = npmUser;
    return this;
  }

   /**
   * Get npmUser
   * @return npmUser
  **/
  public Object getNpmUser() {
    return npmUser;
  }

  public void setNpmUser(Object npmUser) {
    this.npmUser = npmUser;
  }

  public WebhookpackagepublishedPackagePackageVersionNpmMetadata author(Object author) {
    this.author = author;
    return this;
  }

   /**
   * Get author
   * @return author
  **/
  public Object getAuthor() {
    return author;
  }

  public void setAuthor(Object author) {
    this.author = author;
  }

  public WebhookpackagepublishedPackagePackageVersionNpmMetadata bugs(Object bugs) {
    this.bugs = bugs;
    return this;
  }

   /**
   * Get bugs
   * @return bugs
  **/
  public Object getBugs() {
    return bugs;
  }

  public void setBugs(Object bugs) {
    this.bugs = bugs;
  }

  public WebhookpackagepublishedPackagePackageVersionNpmMetadata dependencies(Object dependencies) {
    this.dependencies = dependencies;
    return this;
  }

   /**
   * Get dependencies
   * @return dependencies
  **/
  public Object getDependencies() {
    return dependencies;
  }

  public void setDependencies(Object dependencies) {
    this.dependencies = dependencies;
  }

  public WebhookpackagepublishedPackagePackageVersionNpmMetadata devDependencies(Object devDependencies) {
    this.devDependencies = devDependencies;
    return this;
  }

   /**
   * Get devDependencies
   * @return devDependencies
  **/
  public Object getDevDependencies() {
    return devDependencies;
  }

  public void setDevDependencies(Object devDependencies) {
    this.devDependencies = devDependencies;
  }

  public WebhookpackagepublishedPackagePackageVersionNpmMetadata peerDependencies(Object peerDependencies) {
    this.peerDependencies = peerDependencies;
    return this;
  }

   /**
   * Get peerDependencies
   * @return peerDependencies
  **/
  public Object getPeerDependencies() {
    return peerDependencies;
  }

  public void setPeerDependencies(Object peerDependencies) {
    this.peerDependencies = peerDependencies;
  }

  public WebhookpackagepublishedPackagePackageVersionNpmMetadata optionalDependencies(Object optionalDependencies) {
    this.optionalDependencies = optionalDependencies;
    return this;
  }

   /**
   * Get optionalDependencies
   * @return optionalDependencies
  **/
  public Object getOptionalDependencies() {
    return optionalDependencies;
  }

  public void setOptionalDependencies(Object optionalDependencies) {
    this.optionalDependencies = optionalDependencies;
  }

  public WebhookpackagepublishedPackagePackageVersionNpmMetadata description(Object description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  public Object getDescription() {
    return description;
  }

  public void setDescription(Object description) {
    this.description = description;
  }

  public WebhookpackagepublishedPackagePackageVersionNpmMetadata dist(Object dist) {
    this.dist = dist;
    return this;
  }

   /**
   * Get dist
   * @return dist
  **/
  public Object getDist() {
    return dist;
  }

  public void setDist(Object dist) {
    this.dist = dist;
  }

  public WebhookpackagepublishedPackagePackageVersionNpmMetadata gitHead(Object gitHead) {
    this.gitHead = gitHead;
    return this;
  }

   /**
   * Get gitHead
   * @return gitHead
  **/
  public Object getGitHead() {
    return gitHead;
  }

  public void setGitHead(Object gitHead) {
    this.gitHead = gitHead;
  }

  public WebhookpackagepublishedPackagePackageVersionNpmMetadata homepage(Object homepage) {
    this.homepage = homepage;
    return this;
  }

   /**
   * Get homepage
   * @return homepage
  **/
  public Object getHomepage() {
    return homepage;
  }

  public void setHomepage(Object homepage) {
    this.homepage = homepage;
  }

  public WebhookpackagepublishedPackagePackageVersionNpmMetadata license(Object license) {
    this.license = license;
    return this;
  }

   /**
   * Get license
   * @return license
  **/
  public Object getLicense() {
    return license;
  }

  public void setLicense(Object license) {
    this.license = license;
  }

  public WebhookpackagepublishedPackagePackageVersionNpmMetadata main(Object main) {
    this.main = main;
    return this;
  }

   /**
   * Get main
   * @return main
  **/
  public Object getMain() {
    return main;
  }

  public void setMain(Object main) {
    this.main = main;
  }

  public WebhookpackagepublishedPackagePackageVersionNpmMetadata repository(Object repository) {
    this.repository = repository;
    return this;
  }

   /**
   * Get repository
   * @return repository
  **/
  public Object getRepository() {
    return repository;
  }

  public void setRepository(Object repository) {
    this.repository = repository;
  }

  public WebhookpackagepublishedPackagePackageVersionNpmMetadata scripts(Object scripts) {
    this.scripts = scripts;
    return this;
  }

   /**
   * Get scripts
   * @return scripts
  **/
  public Object getScripts() {
    return scripts;
  }

  public void setScripts(Object scripts) {
    this.scripts = scripts;
  }

  public WebhookpackagepublishedPackagePackageVersionNpmMetadata id(Object id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Object getId() {
    return id;
  }

  public void setId(Object id) {
    this.id = id;
  }

  public WebhookpackagepublishedPackagePackageVersionNpmMetadata nodeVersion(Object nodeVersion) {
    this.nodeVersion = nodeVersion;
    return this;
  }

   /**
   * Get nodeVersion
   * @return nodeVersion
  **/
  public Object getNodeVersion() {
    return nodeVersion;
  }

  public void setNodeVersion(Object nodeVersion) {
    this.nodeVersion = nodeVersion;
  }

  public WebhookpackagepublishedPackagePackageVersionNpmMetadata npmVersion(Object npmVersion) {
    this.npmVersion = npmVersion;
    return this;
  }

   /**
   * Get npmVersion
   * @return npmVersion
  **/
  public Object getNpmVersion() {
    return npmVersion;
  }

  public void setNpmVersion(Object npmVersion) {
    this.npmVersion = npmVersion;
  }

  public WebhookpackagepublishedPackagePackageVersionNpmMetadata hasShrinkwrap(Object hasShrinkwrap) {
    this.hasShrinkwrap = hasShrinkwrap;
    return this;
  }

   /**
   * Get hasShrinkwrap
   * @return hasShrinkwrap
  **/
  public Object getHasShrinkwrap() {
    return hasShrinkwrap;
  }

  public void setHasShrinkwrap(Object hasShrinkwrap) {
    this.hasShrinkwrap = hasShrinkwrap;
  }

  public WebhookpackagepublishedPackagePackageVersionNpmMetadata maintainers(Object maintainers) {
    this.maintainers = maintainers;
    return this;
  }

   /**
   * Get maintainers
   * @return maintainers
  **/
  public Object getMaintainers() {
    return maintainers;
  }

  public void setMaintainers(Object maintainers) {
    this.maintainers = maintainers;
  }

  public WebhookpackagepublishedPackagePackageVersionNpmMetadata contributors(Object contributors) {
    this.contributors = contributors;
    return this;
  }

   /**
   * Get contributors
   * @return contributors
  **/
  public Object getContributors() {
    return contributors;
  }

  public void setContributors(Object contributors) {
    this.contributors = contributors;
  }

  public WebhookpackagepublishedPackagePackageVersionNpmMetadata engines(Object engines) {
    this.engines = engines;
    return this;
  }

   /**
   * Get engines
   * @return engines
  **/
  public Object getEngines() {
    return engines;
  }

  public void setEngines(Object engines) {
    this.engines = engines;
  }

  public WebhookpackagepublishedPackagePackageVersionNpmMetadata keywords(Object keywords) {
    this.keywords = keywords;
    return this;
  }

   /**
   * Get keywords
   * @return keywords
  **/
  public Object getKeywords() {
    return keywords;
  }

  public void setKeywords(Object keywords) {
    this.keywords = keywords;
  }

  public WebhookpackagepublishedPackagePackageVersionNpmMetadata files(Object files) {
    this.files = files;
    return this;
  }

   /**
   * Get files
   * @return files
  **/
  public Object getFiles() {
    return files;
  }

  public void setFiles(Object files) {
    this.files = files;
  }

  public WebhookpackagepublishedPackagePackageVersionNpmMetadata bin(Object bin) {
    this.bin = bin;
    return this;
  }

   /**
   * Get bin
   * @return bin
  **/
  public Object getBin() {
    return bin;
  }

  public void setBin(Object bin) {
    this.bin = bin;
  }

  public WebhookpackagepublishedPackagePackageVersionNpmMetadata man(Object man) {
    this.man = man;
    return this;
  }

   /**
   * Get man
   * @return man
  **/
  public Object getMan() {
    return man;
  }

  public void setMan(Object man) {
    this.man = man;
  }

  public WebhookpackagepublishedPackagePackageVersionNpmMetadata directories(Object directories) {
    this.directories = directories;
    return this;
  }

   /**
   * Get directories
   * @return directories
  **/
  public Object getDirectories() {
    return directories;
  }

  public void setDirectories(Object directories) {
    this.directories = directories;
  }

  public WebhookpackagepublishedPackagePackageVersionNpmMetadata os(Object os) {
    this.os = os;
    return this;
  }

   /**
   * Get os
   * @return os
  **/
  public Object getOs() {
    return os;
  }

  public void setOs(Object os) {
    this.os = os;
  }

  public WebhookpackagepublishedPackagePackageVersionNpmMetadata cpu(Object cpu) {
    this.cpu = cpu;
    return this;
  }

   /**
   * Get cpu
   * @return cpu
  **/
  public Object getCpu() {
    return cpu;
  }

  public void setCpu(Object cpu) {
    this.cpu = cpu;
  }

  public WebhookpackagepublishedPackagePackageVersionNpmMetadata readme(Object readme) {
    this.readme = readme;
    return this;
  }

   /**
   * Get readme
   * @return readme
  **/
  public Object getReadme() {
    return readme;
  }

  public void setReadme(Object readme) {
    this.readme = readme;
  }

  public WebhookpackagepublishedPackagePackageVersionNpmMetadata installationCommand(Object installationCommand) {
    this.installationCommand = installationCommand;
    return this;
  }

   /**
   * Get installationCommand
   * @return installationCommand
  **/
  public Object getInstallationCommand() {
    return installationCommand;
  }

  public void setInstallationCommand(Object installationCommand) {
    this.installationCommand = installationCommand;
  }

  public WebhookpackagepublishedPackagePackageVersionNpmMetadata releaseId(Object releaseId) {
    this.releaseId = releaseId;
    return this;
  }

   /**
   * Get releaseId
   * @return releaseId
  **/
  public Object getReleaseId() {
    return releaseId;
  }

  public void setReleaseId(Object releaseId) {
    this.releaseId = releaseId;
  }

  public WebhookpackagepublishedPackagePackageVersionNpmMetadata commitOid(Object commitOid) {
    this.commitOid = commitOid;
    return this;
  }

   /**
   * Get commitOid
   * @return commitOid
  **/
  public Object getCommitOid() {
    return commitOid;
  }

  public void setCommitOid(Object commitOid) {
    this.commitOid = commitOid;
  }

  public WebhookpackagepublishedPackagePackageVersionNpmMetadata publishedViaActions(Object publishedViaActions) {
    this.publishedViaActions = publishedViaActions;
    return this;
  }

   /**
   * Get publishedViaActions
   * @return publishedViaActions
  **/
  public Object getPublishedViaActions() {
    return publishedViaActions;
  }

  public void setPublishedViaActions(Object publishedViaActions) {
    this.publishedViaActions = publishedViaActions;
  }

  public WebhookpackagepublishedPackagePackageVersionNpmMetadata deletedById(Object deletedById) {
    this.deletedById = deletedById;
    return this;
  }

   /**
   * Get deletedById
   * @return deletedById
  **/
  public Object getDeletedById() {
    return deletedById;
  }

  public void setDeletedById(Object deletedById) {
    this.deletedById = deletedById;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookpackagepublishedPackagePackageVersionNpmMetadata webhookpackagepublishedPackagePackageVersionNpmMetadata = (WebhookpackagepublishedPackagePackageVersionNpmMetadata) o;
    return Objects.equals(this.name, webhookpackagepublishedPackagePackageVersionNpmMetadata.name) &&
        Objects.equals(this.version, webhookpackagepublishedPackagePackageVersionNpmMetadata.version) &&
        Objects.equals(this.npmUser, webhookpackagepublishedPackagePackageVersionNpmMetadata.npmUser) &&
        Objects.equals(this.author, webhookpackagepublishedPackagePackageVersionNpmMetadata.author) &&
        Objects.equals(this.bugs, webhookpackagepublishedPackagePackageVersionNpmMetadata.bugs) &&
        Objects.equals(this.dependencies, webhookpackagepublishedPackagePackageVersionNpmMetadata.dependencies) &&
        Objects.equals(this.devDependencies, webhookpackagepublishedPackagePackageVersionNpmMetadata.devDependencies) &&
        Objects.equals(this.peerDependencies, webhookpackagepublishedPackagePackageVersionNpmMetadata.peerDependencies) &&
        Objects.equals(this.optionalDependencies, webhookpackagepublishedPackagePackageVersionNpmMetadata.optionalDependencies) &&
        Objects.equals(this.description, webhookpackagepublishedPackagePackageVersionNpmMetadata.description) &&
        Objects.equals(this.dist, webhookpackagepublishedPackagePackageVersionNpmMetadata.dist) &&
        Objects.equals(this.gitHead, webhookpackagepublishedPackagePackageVersionNpmMetadata.gitHead) &&
        Objects.equals(this.homepage, webhookpackagepublishedPackagePackageVersionNpmMetadata.homepage) &&
        Objects.equals(this.license, webhookpackagepublishedPackagePackageVersionNpmMetadata.license) &&
        Objects.equals(this.main, webhookpackagepublishedPackagePackageVersionNpmMetadata.main) &&
        Objects.equals(this.repository, webhookpackagepublishedPackagePackageVersionNpmMetadata.repository) &&
        Objects.equals(this.scripts, webhookpackagepublishedPackagePackageVersionNpmMetadata.scripts) &&
        Objects.equals(this.id, webhookpackagepublishedPackagePackageVersionNpmMetadata.id) &&
        Objects.equals(this.nodeVersion, webhookpackagepublishedPackagePackageVersionNpmMetadata.nodeVersion) &&
        Objects.equals(this.npmVersion, webhookpackagepublishedPackagePackageVersionNpmMetadata.npmVersion) &&
        Objects.equals(this.hasShrinkwrap, webhookpackagepublishedPackagePackageVersionNpmMetadata.hasShrinkwrap) &&
        Objects.equals(this.maintainers, webhookpackagepublishedPackagePackageVersionNpmMetadata.maintainers) &&
        Objects.equals(this.contributors, webhookpackagepublishedPackagePackageVersionNpmMetadata.contributors) &&
        Objects.equals(this.engines, webhookpackagepublishedPackagePackageVersionNpmMetadata.engines) &&
        Objects.equals(this.keywords, webhookpackagepublishedPackagePackageVersionNpmMetadata.keywords) &&
        Objects.equals(this.files, webhookpackagepublishedPackagePackageVersionNpmMetadata.files) &&
        Objects.equals(this.bin, webhookpackagepublishedPackagePackageVersionNpmMetadata.bin) &&
        Objects.equals(this.man, webhookpackagepublishedPackagePackageVersionNpmMetadata.man) &&
        Objects.equals(this.directories, webhookpackagepublishedPackagePackageVersionNpmMetadata.directories) &&
        Objects.equals(this.os, webhookpackagepublishedPackagePackageVersionNpmMetadata.os) &&
        Objects.equals(this.cpu, webhookpackagepublishedPackagePackageVersionNpmMetadata.cpu) &&
        Objects.equals(this.readme, webhookpackagepublishedPackagePackageVersionNpmMetadata.readme) &&
        Objects.equals(this.installationCommand, webhookpackagepublishedPackagePackageVersionNpmMetadata.installationCommand) &&
        Objects.equals(this.releaseId, webhookpackagepublishedPackagePackageVersionNpmMetadata.releaseId) &&
        Objects.equals(this.commitOid, webhookpackagepublishedPackagePackageVersionNpmMetadata.commitOid) &&
        Objects.equals(this.publishedViaActions, webhookpackagepublishedPackagePackageVersionNpmMetadata.publishedViaActions) &&
        Objects.equals(this.deletedById, webhookpackagepublishedPackagePackageVersionNpmMetadata.deletedById);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, version, npmUser, author, bugs, dependencies, devDependencies, peerDependencies, optionalDependencies, description, dist, gitHead, homepage, license, main, repository, scripts, id, nodeVersion, npmVersion, hasShrinkwrap, maintainers, contributors, engines, keywords, files, bin, man, directories, os, cpu, readme, installationCommand, releaseId, commitOid, publishedViaActions, deletedById);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebhookpackagepublishedPackagePackageVersionNpmMetadata {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    npmUser: ").append(toIndentedString(npmUser)).append("\n");
    sb.append("    author: ").append(toIndentedString(author)).append("\n");
    sb.append("    bugs: ").append(toIndentedString(bugs)).append("\n");
    sb.append("    dependencies: ").append(toIndentedString(dependencies)).append("\n");
    sb.append("    devDependencies: ").append(toIndentedString(devDependencies)).append("\n");
    sb.append("    peerDependencies: ").append(toIndentedString(peerDependencies)).append("\n");
    sb.append("    optionalDependencies: ").append(toIndentedString(optionalDependencies)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    dist: ").append(toIndentedString(dist)).append("\n");
    sb.append("    gitHead: ").append(toIndentedString(gitHead)).append("\n");
    sb.append("    homepage: ").append(toIndentedString(homepage)).append("\n");
    sb.append("    license: ").append(toIndentedString(license)).append("\n");
    sb.append("    main: ").append(toIndentedString(main)).append("\n");
    sb.append("    repository: ").append(toIndentedString(repository)).append("\n");
    sb.append("    scripts: ").append(toIndentedString(scripts)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    nodeVersion: ").append(toIndentedString(nodeVersion)).append("\n");
    sb.append("    npmVersion: ").append(toIndentedString(npmVersion)).append("\n");
    sb.append("    hasShrinkwrap: ").append(toIndentedString(hasShrinkwrap)).append("\n");
    sb.append("    maintainers: ").append(toIndentedString(maintainers)).append("\n");
    sb.append("    contributors: ").append(toIndentedString(contributors)).append("\n");
    sb.append("    engines: ").append(toIndentedString(engines)).append("\n");
    sb.append("    keywords: ").append(toIndentedString(keywords)).append("\n");
    sb.append("    files: ").append(toIndentedString(files)).append("\n");
    sb.append("    bin: ").append(toIndentedString(bin)).append("\n");
    sb.append("    man: ").append(toIndentedString(man)).append("\n");
    sb.append("    directories: ").append(toIndentedString(directories)).append("\n");
    sb.append("    os: ").append(toIndentedString(os)).append("\n");
    sb.append("    cpu: ").append(toIndentedString(cpu)).append("\n");
    sb.append("    readme: ").append(toIndentedString(readme)).append("\n");
    sb.append("    installationCommand: ").append(toIndentedString(installationCommand)).append("\n");
    sb.append("    releaseId: ").append(toIndentedString(releaseId)).append("\n");
    sb.append("    commitOid: ").append(toIndentedString(commitOid)).append("\n");
    sb.append("    publishedViaActions: ").append(toIndentedString(publishedViaActions)).append("\n");
    sb.append("    deletedById: ").append(toIndentedString(deletedById)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
