/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.github.api.client.User1;
import com.github.api.client.WebhookpullrequestreviewdismissedReviewLinks;

/**
 * The review that was affected.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class WebhookpullrequestreviewdismissedReview {
  @JsonProperty("_links")
  private WebhookpullrequestreviewdismissedReviewLinks _links = null;

  @JsonProperty("author_association")
  private Object authorAssociation = null;

  @JsonProperty("body")
  private Object body = null;

  @JsonProperty("commit_id")
  private Object commitId = null;

  @JsonProperty("html_url")
  private Object htmlUrl = null;

  @JsonProperty("id")
  private Object id = null;

  @JsonProperty("node_id")
  private Object nodeId = null;

  @JsonProperty("pull_request_url")
  private Object pullRequestUrl = null;

  @JsonProperty("state")
  private Object state = null;

  @JsonProperty("submitted_at")
  private Object submittedAt = null;

  @JsonProperty("user")
  private User1 user = null;

  public WebhookpullrequestreviewdismissedReview _links(WebhookpullrequestreviewdismissedReviewLinks _links) {
    this._links = _links;
    return this;
  }

   /**
   * Get _links
   * @return _links
  **/
  public WebhookpullrequestreviewdismissedReviewLinks getLinks() {
    return _links;
  }

  public void setLinks(WebhookpullrequestreviewdismissedReviewLinks _links) {
    this._links = _links;
  }

  public WebhookpullrequestreviewdismissedReview authorAssociation(Object authorAssociation) {
    this.authorAssociation = authorAssociation;
    return this;
  }

   /**
   * How the author is associated with the repository.
   * @return authorAssociation
  **/
  public Object getAuthorAssociation() {
    return authorAssociation;
  }

  public void setAuthorAssociation(Object authorAssociation) {
    this.authorAssociation = authorAssociation;
  }

  public WebhookpullrequestreviewdismissedReview body(Object body) {
    this.body = body;
    return this;
  }

   /**
   * The text of the review.
   * @return body
  **/
  public Object getBody() {
    return body;
  }

  public void setBody(Object body) {
    this.body = body;
  }

  public WebhookpullrequestreviewdismissedReview commitId(Object commitId) {
    this.commitId = commitId;
    return this;
  }

   /**
   * A commit SHA for the review.
   * @return commitId
  **/
  public Object getCommitId() {
    return commitId;
  }

  public void setCommitId(Object commitId) {
    this.commitId = commitId;
  }

  public WebhookpullrequestreviewdismissedReview htmlUrl(Object htmlUrl) {
    this.htmlUrl = htmlUrl;
    return this;
  }

   /**
   * Get htmlUrl
   * @return htmlUrl
  **/
  public Object getHtmlUrl() {
    return htmlUrl;
  }

  public void setHtmlUrl(Object htmlUrl) {
    this.htmlUrl = htmlUrl;
  }

  public WebhookpullrequestreviewdismissedReview id(Object id) {
    this.id = id;
    return this;
  }

   /**
   * Unique identifier of the review
   * @return id
  **/
  public Object getId() {
    return id;
  }

  public void setId(Object id) {
    this.id = id;
  }

  public WebhookpullrequestreviewdismissedReview nodeId(Object nodeId) {
    this.nodeId = nodeId;
    return this;
  }

   /**
   * Get nodeId
   * @return nodeId
  **/
  public Object getNodeId() {
    return nodeId;
  }

  public void setNodeId(Object nodeId) {
    this.nodeId = nodeId;
  }

  public WebhookpullrequestreviewdismissedReview pullRequestUrl(Object pullRequestUrl) {
    this.pullRequestUrl = pullRequestUrl;
    return this;
  }

   /**
   * Get pullRequestUrl
   * @return pullRequestUrl
  **/
  public Object getPullRequestUrl() {
    return pullRequestUrl;
  }

  public void setPullRequestUrl(Object pullRequestUrl) {
    this.pullRequestUrl = pullRequestUrl;
  }

  public WebhookpullrequestreviewdismissedReview state(Object state) {
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  public Object getState() {
    return state;
  }

  public void setState(Object state) {
    this.state = state;
  }

  public WebhookpullrequestreviewdismissedReview submittedAt(Object submittedAt) {
    this.submittedAt = submittedAt;
    return this;
  }

   /**
   * Get submittedAt
   * @return submittedAt
  **/
  public Object getSubmittedAt() {
    return submittedAt;
  }

  public void setSubmittedAt(Object submittedAt) {
    this.submittedAt = submittedAt;
  }

  public WebhookpullrequestreviewdismissedReview user(User1 user) {
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  public User1 getUser() {
    return user;
  }

  public void setUser(User1 user) {
    this.user = user;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookpullrequestreviewdismissedReview webhookpullrequestreviewdismissedReview = (WebhookpullrequestreviewdismissedReview) o;
    return Objects.equals(this._links, webhookpullrequestreviewdismissedReview._links) &&
        Objects.equals(this.authorAssociation, webhookpullrequestreviewdismissedReview.authorAssociation) &&
        Objects.equals(this.body, webhookpullrequestreviewdismissedReview.body) &&
        Objects.equals(this.commitId, webhookpullrequestreviewdismissedReview.commitId) &&
        Objects.equals(this.htmlUrl, webhookpullrequestreviewdismissedReview.htmlUrl) &&
        Objects.equals(this.id, webhookpullrequestreviewdismissedReview.id) &&
        Objects.equals(this.nodeId, webhookpullrequestreviewdismissedReview.nodeId) &&
        Objects.equals(this.pullRequestUrl, webhookpullrequestreviewdismissedReview.pullRequestUrl) &&
        Objects.equals(this.state, webhookpullrequestreviewdismissedReview.state) &&
        Objects.equals(this.submittedAt, webhookpullrequestreviewdismissedReview.submittedAt) &&
        Objects.equals(this.user, webhookpullrequestreviewdismissedReview.user);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_links, authorAssociation, body, commitId, htmlUrl, id, nodeId, pullRequestUrl, state, submittedAt, user);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebhookpullrequestreviewdismissedReview {\n");
    
    sb.append("    _links: ").append(toIndentedString(_links)).append("\n");
    sb.append("    authorAssociation: ").append(toIndentedString(authorAssociation)).append("\n");
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("    commitId: ").append(toIndentedString(commitId)).append("\n");
    sb.append("    htmlUrl: ").append(toIndentedString(htmlUrl)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    nodeId: ").append(toIndentedString(nodeId)).append("\n");
    sb.append("    pullRequestUrl: ").append(toIndentedString(pullRequestUrl)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    submittedAt: ").append(toIndentedString(submittedAt)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
