/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Webhookpackagev2createPackagePackageVersionContainerMetadataManifestConfig
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class Webhookpackagev2createPackagePackageVersionContainerMetadataManifestConfig {
  @JsonProperty("digest")
  private Object digest = null;

  @JsonProperty("media_type")
  private Object mediaType = null;

  @JsonProperty("size")
  private Object size = null;

  public Webhookpackagev2createPackagePackageVersionContainerMetadataManifestConfig digest(Object digest) {
    this.digest = digest;
    return this;
  }

   /**
   * Get digest
   * @return digest
  **/
  public Object getDigest() {
    return digest;
  }

  public void setDigest(Object digest) {
    this.digest = digest;
  }

  public Webhookpackagev2createPackagePackageVersionContainerMetadataManifestConfig mediaType(Object mediaType) {
    this.mediaType = mediaType;
    return this;
  }

   /**
   * Get mediaType
   * @return mediaType
  **/
  public Object getMediaType() {
    return mediaType;
  }

  public void setMediaType(Object mediaType) {
    this.mediaType = mediaType;
  }

  public Webhookpackagev2createPackagePackageVersionContainerMetadataManifestConfig size(Object size) {
    this.size = size;
    return this;
  }

   /**
   * Get size
   * @return size
  **/
  public Object getSize() {
    return size;
  }

  public void setSize(Object size) {
    this.size = size;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Webhookpackagev2createPackagePackageVersionContainerMetadataManifestConfig webhookpackagev2createPackagePackageVersionContainerMetadataManifestConfig = (Webhookpackagev2createPackagePackageVersionContainerMetadataManifestConfig) o;
    return Objects.equals(this.digest, webhookpackagev2createPackagePackageVersionContainerMetadataManifestConfig.digest) &&
        Objects.equals(this.mediaType, webhookpackagev2createPackagePackageVersionContainerMetadataManifestConfig.mediaType) &&
        Objects.equals(this.size, webhookpackagev2createPackagePackageVersionContainerMetadataManifestConfig.size);
  }

  @Override
  public int hashCode() {
    return Objects.hash(digest, mediaType, size);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Webhookpackagev2createPackagePackageVersionContainerMetadataManifestConfig {\n");
    
    sb.append("    digest: ").append(toIndentedString(digest)).append("\n");
    sb.append("    mediaType: ").append(toIndentedString(mediaType)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
