/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.github.api.client.WebhooklabeleditedChangesDescription;
import com.github.api.client.WebhookmilestoneeditedChangesDueOn;
import com.github.api.client.WebhookmilestoneeditedChangesTitle;

/**
 * The changes to the milestone if the action was &#x60;edited&#x60;.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class WebhookmilestoneeditedChanges {
  @JsonProperty("description")
  private WebhooklabeleditedChangesDescription description = null;

  @JsonProperty("due_on")
  private WebhookmilestoneeditedChangesDueOn dueOn = null;

  @JsonProperty("title")
  private WebhookmilestoneeditedChangesTitle title = null;

  public WebhookmilestoneeditedChanges description(WebhooklabeleditedChangesDescription description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  public WebhooklabeleditedChangesDescription getDescription() {
    return description;
  }

  public void setDescription(WebhooklabeleditedChangesDescription description) {
    this.description = description;
  }

  public WebhookmilestoneeditedChanges dueOn(WebhookmilestoneeditedChangesDueOn dueOn) {
    this.dueOn = dueOn;
    return this;
  }

   /**
   * Get dueOn
   * @return dueOn
  **/
  public WebhookmilestoneeditedChangesDueOn getDueOn() {
    return dueOn;
  }

  public void setDueOn(WebhookmilestoneeditedChangesDueOn dueOn) {
    this.dueOn = dueOn;
  }

  public WebhookmilestoneeditedChanges title(WebhookmilestoneeditedChangesTitle title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  public WebhookmilestoneeditedChangesTitle getTitle() {
    return title;
  }

  public void setTitle(WebhookmilestoneeditedChangesTitle title) {
    this.title = title;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookmilestoneeditedChanges webhookmilestoneeditedChanges = (WebhookmilestoneeditedChanges) o;
    return Objects.equals(this.description, webhookmilestoneeditedChanges.description) &&
        Objects.equals(this.dueOn, webhookmilestoneeditedChanges.dueOn) &&
        Objects.equals(this.title, webhookmilestoneeditedChanges.title);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, dueOn, title);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebhookmilestoneeditedChanges {\n");
    
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    dueOn: ").append(toIndentedString(dueOn)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
