/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * WebhookregistrypackagepublishedRegistryPackageOwner
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class WebhookregistrypackagepublishedRegistryPackageOwner {
  @JsonProperty("avatar_url")
  private Object avatarUrl = null;

  @JsonProperty("events_url")
  private Object eventsUrl = null;

  @JsonProperty("followers_url")
  private Object followersUrl = null;

  @JsonProperty("following_url")
  private Object followingUrl = null;

  @JsonProperty("gists_url")
  private Object gistsUrl = null;

  @JsonProperty("gravatar_id")
  private Object gravatarId = null;

  @JsonProperty("html_url")
  private Object htmlUrl = null;

  @JsonProperty("id")
  private Object id = null;

  @JsonProperty("login")
  private Object login = null;

  @JsonProperty("node_id")
  private Object nodeId = null;

  @JsonProperty("organizations_url")
  private Object organizationsUrl = null;

  @JsonProperty("received_events_url")
  private Object receivedEventsUrl = null;

  @JsonProperty("repos_url")
  private Object reposUrl = null;

  @JsonProperty("site_admin")
  private Object siteAdmin = null;

  @JsonProperty("starred_url")
  private Object starredUrl = null;

  @JsonProperty("subscriptions_url")
  private Object subscriptionsUrl = null;

  @JsonProperty("type")
  private Object type = null;

  @JsonProperty("url")
  private Object url = null;

  public WebhookregistrypackagepublishedRegistryPackageOwner avatarUrl(Object avatarUrl) {
    this.avatarUrl = avatarUrl;
    return this;
  }

   /**
   * Get avatarUrl
   * @return avatarUrl
  **/
  public Object getAvatarUrl() {
    return avatarUrl;
  }

  public void setAvatarUrl(Object avatarUrl) {
    this.avatarUrl = avatarUrl;
  }

  public WebhookregistrypackagepublishedRegistryPackageOwner eventsUrl(Object eventsUrl) {
    this.eventsUrl = eventsUrl;
    return this;
  }

   /**
   * Get eventsUrl
   * @return eventsUrl
  **/
  public Object getEventsUrl() {
    return eventsUrl;
  }

  public void setEventsUrl(Object eventsUrl) {
    this.eventsUrl = eventsUrl;
  }

  public WebhookregistrypackagepublishedRegistryPackageOwner followersUrl(Object followersUrl) {
    this.followersUrl = followersUrl;
    return this;
  }

   /**
   * Get followersUrl
   * @return followersUrl
  **/
  public Object getFollowersUrl() {
    return followersUrl;
  }

  public void setFollowersUrl(Object followersUrl) {
    this.followersUrl = followersUrl;
  }

  public WebhookregistrypackagepublishedRegistryPackageOwner followingUrl(Object followingUrl) {
    this.followingUrl = followingUrl;
    return this;
  }

   /**
   * Get followingUrl
   * @return followingUrl
  **/
  public Object getFollowingUrl() {
    return followingUrl;
  }

  public void setFollowingUrl(Object followingUrl) {
    this.followingUrl = followingUrl;
  }

  public WebhookregistrypackagepublishedRegistryPackageOwner gistsUrl(Object gistsUrl) {
    this.gistsUrl = gistsUrl;
    return this;
  }

   /**
   * Get gistsUrl
   * @return gistsUrl
  **/
  public Object getGistsUrl() {
    return gistsUrl;
  }

  public void setGistsUrl(Object gistsUrl) {
    this.gistsUrl = gistsUrl;
  }

  public WebhookregistrypackagepublishedRegistryPackageOwner gravatarId(Object gravatarId) {
    this.gravatarId = gravatarId;
    return this;
  }

   /**
   * Get gravatarId
   * @return gravatarId
  **/
  public Object getGravatarId() {
    return gravatarId;
  }

  public void setGravatarId(Object gravatarId) {
    this.gravatarId = gravatarId;
  }

  public WebhookregistrypackagepublishedRegistryPackageOwner htmlUrl(Object htmlUrl) {
    this.htmlUrl = htmlUrl;
    return this;
  }

   /**
   * Get htmlUrl
   * @return htmlUrl
  **/
  public Object getHtmlUrl() {
    return htmlUrl;
  }

  public void setHtmlUrl(Object htmlUrl) {
    this.htmlUrl = htmlUrl;
  }

  public WebhookregistrypackagepublishedRegistryPackageOwner id(Object id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Object getId() {
    return id;
  }

  public void setId(Object id) {
    this.id = id;
  }

  public WebhookregistrypackagepublishedRegistryPackageOwner login(Object login) {
    this.login = login;
    return this;
  }

   /**
   * Get login
   * @return login
  **/
  public Object getLogin() {
    return login;
  }

  public void setLogin(Object login) {
    this.login = login;
  }

  public WebhookregistrypackagepublishedRegistryPackageOwner nodeId(Object nodeId) {
    this.nodeId = nodeId;
    return this;
  }

   /**
   * Get nodeId
   * @return nodeId
  **/
  public Object getNodeId() {
    return nodeId;
  }

  public void setNodeId(Object nodeId) {
    this.nodeId = nodeId;
  }

  public WebhookregistrypackagepublishedRegistryPackageOwner organizationsUrl(Object organizationsUrl) {
    this.organizationsUrl = organizationsUrl;
    return this;
  }

   /**
   * Get organizationsUrl
   * @return organizationsUrl
  **/
  public Object getOrganizationsUrl() {
    return organizationsUrl;
  }

  public void setOrganizationsUrl(Object organizationsUrl) {
    this.organizationsUrl = organizationsUrl;
  }

  public WebhookregistrypackagepublishedRegistryPackageOwner receivedEventsUrl(Object receivedEventsUrl) {
    this.receivedEventsUrl = receivedEventsUrl;
    return this;
  }

   /**
   * Get receivedEventsUrl
   * @return receivedEventsUrl
  **/
  public Object getReceivedEventsUrl() {
    return receivedEventsUrl;
  }

  public void setReceivedEventsUrl(Object receivedEventsUrl) {
    this.receivedEventsUrl = receivedEventsUrl;
  }

  public WebhookregistrypackagepublishedRegistryPackageOwner reposUrl(Object reposUrl) {
    this.reposUrl = reposUrl;
    return this;
  }

   /**
   * Get reposUrl
   * @return reposUrl
  **/
  public Object getReposUrl() {
    return reposUrl;
  }

  public void setReposUrl(Object reposUrl) {
    this.reposUrl = reposUrl;
  }

  public WebhookregistrypackagepublishedRegistryPackageOwner siteAdmin(Object siteAdmin) {
    this.siteAdmin = siteAdmin;
    return this;
  }

   /**
   * Get siteAdmin
   * @return siteAdmin
  **/
  public Object getSiteAdmin() {
    return siteAdmin;
  }

  public void setSiteAdmin(Object siteAdmin) {
    this.siteAdmin = siteAdmin;
  }

  public WebhookregistrypackagepublishedRegistryPackageOwner starredUrl(Object starredUrl) {
    this.starredUrl = starredUrl;
    return this;
  }

   /**
   * Get starredUrl
   * @return starredUrl
  **/
  public Object getStarredUrl() {
    return starredUrl;
  }

  public void setStarredUrl(Object starredUrl) {
    this.starredUrl = starredUrl;
  }

  public WebhookregistrypackagepublishedRegistryPackageOwner subscriptionsUrl(Object subscriptionsUrl) {
    this.subscriptionsUrl = subscriptionsUrl;
    return this;
  }

   /**
   * Get subscriptionsUrl
   * @return subscriptionsUrl
  **/
  public Object getSubscriptionsUrl() {
    return subscriptionsUrl;
  }

  public void setSubscriptionsUrl(Object subscriptionsUrl) {
    this.subscriptionsUrl = subscriptionsUrl;
  }

  public WebhookregistrypackagepublishedRegistryPackageOwner type(Object type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  public Object getType() {
    return type;
  }

  public void setType(Object type) {
    this.type = type;
  }

  public WebhookregistrypackagepublishedRegistryPackageOwner url(Object url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  public Object getUrl() {
    return url;
  }

  public void setUrl(Object url) {
    this.url = url;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookregistrypackagepublishedRegistryPackageOwner webhookregistrypackagepublishedRegistryPackageOwner = (WebhookregistrypackagepublishedRegistryPackageOwner) o;
    return Objects.equals(this.avatarUrl, webhookregistrypackagepublishedRegistryPackageOwner.avatarUrl) &&
        Objects.equals(this.eventsUrl, webhookregistrypackagepublishedRegistryPackageOwner.eventsUrl) &&
        Objects.equals(this.followersUrl, webhookregistrypackagepublishedRegistryPackageOwner.followersUrl) &&
        Objects.equals(this.followingUrl, webhookregistrypackagepublishedRegistryPackageOwner.followingUrl) &&
        Objects.equals(this.gistsUrl, webhookregistrypackagepublishedRegistryPackageOwner.gistsUrl) &&
        Objects.equals(this.gravatarId, webhookregistrypackagepublishedRegistryPackageOwner.gravatarId) &&
        Objects.equals(this.htmlUrl, webhookregistrypackagepublishedRegistryPackageOwner.htmlUrl) &&
        Objects.equals(this.id, webhookregistrypackagepublishedRegistryPackageOwner.id) &&
        Objects.equals(this.login, webhookregistrypackagepublishedRegistryPackageOwner.login) &&
        Objects.equals(this.nodeId, webhookregistrypackagepublishedRegistryPackageOwner.nodeId) &&
        Objects.equals(this.organizationsUrl, webhookregistrypackagepublishedRegistryPackageOwner.organizationsUrl) &&
        Objects.equals(this.receivedEventsUrl, webhookregistrypackagepublishedRegistryPackageOwner.receivedEventsUrl) &&
        Objects.equals(this.reposUrl, webhookregistrypackagepublishedRegistryPackageOwner.reposUrl) &&
        Objects.equals(this.siteAdmin, webhookregistrypackagepublishedRegistryPackageOwner.siteAdmin) &&
        Objects.equals(this.starredUrl, webhookregistrypackagepublishedRegistryPackageOwner.starredUrl) &&
        Objects.equals(this.subscriptionsUrl, webhookregistrypackagepublishedRegistryPackageOwner.subscriptionsUrl) &&
        Objects.equals(this.type, webhookregistrypackagepublishedRegistryPackageOwner.type) &&
        Objects.equals(this.url, webhookregistrypackagepublishedRegistryPackageOwner.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(avatarUrl, eventsUrl, followersUrl, followingUrl, gistsUrl, gravatarId, htmlUrl, id, login, nodeId, organizationsUrl, receivedEventsUrl, reposUrl, siteAdmin, starredUrl, subscriptionsUrl, type, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebhookregistrypackagepublishedRegistryPackageOwner {\n");
    
    sb.append("    avatarUrl: ").append(toIndentedString(avatarUrl)).append("\n");
    sb.append("    eventsUrl: ").append(toIndentedString(eventsUrl)).append("\n");
    sb.append("    followersUrl: ").append(toIndentedString(followersUrl)).append("\n");
    sb.append("    followingUrl: ").append(toIndentedString(followingUrl)).append("\n");
    sb.append("    gistsUrl: ").append(toIndentedString(gistsUrl)).append("\n");
    sb.append("    gravatarId: ").append(toIndentedString(gravatarId)).append("\n");
    sb.append("    htmlUrl: ").append(toIndentedString(htmlUrl)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    login: ").append(toIndentedString(login)).append("\n");
    sb.append("    nodeId: ").append(toIndentedString(nodeId)).append("\n");
    sb.append("    organizationsUrl: ").append(toIndentedString(organizationsUrl)).append("\n");
    sb.append("    receivedEventsUrl: ").append(toIndentedString(receivedEventsUrl)).append("\n");
    sb.append("    reposUrl: ").append(toIndentedString(reposUrl)).append("\n");
    sb.append("    siteAdmin: ").append(toIndentedString(siteAdmin)).append("\n");
    sb.append("    starredUrl: ").append(toIndentedString(starredUrl)).append("\n");
    sb.append("    subscriptionsUrl: ").append(toIndentedString(subscriptionsUrl)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
