/*
 * GitHub v3 REST API
 * GitHub's v3 REST API.
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.github.api.client.Enterprise;
import com.github.api.client.OrganizationSimple;
import com.github.api.client.Repository;
import com.github.api.client.SimpleInstallation;
import com.github.api.client.SimpleUser;
import com.github.api.client.User;

/**
 * WebhookOrgBlockBlocked
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-09T11:03:27.416787800+07:00[Asia/Saigon]")

public class WebhookOrgBlockBlocked {
  @JsonProperty("action")
  private Object action = null;

  @JsonProperty("blocked_user")
  private User blockedUser = null;

  @JsonProperty("enterprise")
  private Enterprise enterprise = null;

  @JsonProperty("installation")
  private SimpleInstallation installation = null;

  @JsonProperty("organization")
  private OrganizationSimple organization = null;

  @JsonProperty("repository")
  private Repository repository = null;

  @JsonProperty("sender")
  private SimpleUser sender = null;

  public WebhookOrgBlockBlocked action(Object action) {
    this.action = action;
    return this;
  }

   /**
   * Get action
   * @return action
  **/
  public Object getAction() {
    return action;
  }

  public void setAction(Object action) {
    this.action = action;
  }

  public WebhookOrgBlockBlocked blockedUser(User blockedUser) {
    this.blockedUser = blockedUser;
    return this;
  }

   /**
   * Get blockedUser
   * @return blockedUser
  **/
  public User getBlockedUser() {
    return blockedUser;
  }

  public void setBlockedUser(User blockedUser) {
    this.blockedUser = blockedUser;
  }

  public WebhookOrgBlockBlocked enterprise(Enterprise enterprise) {
    this.enterprise = enterprise;
    return this;
  }

   /**
   * Get enterprise
   * @return enterprise
  **/
  public Enterprise getEnterprise() {
    return enterprise;
  }

  public void setEnterprise(Enterprise enterprise) {
    this.enterprise = enterprise;
  }

  public WebhookOrgBlockBlocked installation(SimpleInstallation installation) {
    this.installation = installation;
    return this;
  }

   /**
   * Get installation
   * @return installation
  **/
  public SimpleInstallation getInstallation() {
    return installation;
  }

  public void setInstallation(SimpleInstallation installation) {
    this.installation = installation;
  }

  public WebhookOrgBlockBlocked organization(OrganizationSimple organization) {
    this.organization = organization;
    return this;
  }

   /**
   * Get organization
   * @return organization
  **/
  public OrganizationSimple getOrganization() {
    return organization;
  }

  public void setOrganization(OrganizationSimple organization) {
    this.organization = organization;
  }

  public WebhookOrgBlockBlocked repository(Repository repository) {
    this.repository = repository;
    return this;
  }

   /**
   * Get repository
   * @return repository
  **/
  public Repository getRepository() {
    return repository;
  }

  public void setRepository(Repository repository) {
    this.repository = repository;
  }

  public WebhookOrgBlockBlocked sender(SimpleUser sender) {
    this.sender = sender;
    return this;
  }

   /**
   * Get sender
   * @return sender
  **/
  public SimpleUser getSender() {
    return sender;
  }

  public void setSender(SimpleUser sender) {
    this.sender = sender;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookOrgBlockBlocked webhookOrgBlockBlocked = (WebhookOrgBlockBlocked) o;
    return Objects.equals(this.action, webhookOrgBlockBlocked.action) &&
        Objects.equals(this.blockedUser, webhookOrgBlockBlocked.blockedUser) &&
        Objects.equals(this.enterprise, webhookOrgBlockBlocked.enterprise) &&
        Objects.equals(this.installation, webhookOrgBlockBlocked.installation) &&
        Objects.equals(this.organization, webhookOrgBlockBlocked.organization) &&
        Objects.equals(this.repository, webhookOrgBlockBlocked.repository) &&
        Objects.equals(this.sender, webhookOrgBlockBlocked.sender);
  }

  @Override
  public int hashCode() {
    return Objects.hash(action, blockedUser, enterprise, installation, organization, repository, sender);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebhookOrgBlockBlocked {\n");
    
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    blockedUser: ").append(toIndentedString(blockedUser)).append("\n");
    sb.append("    enterprise: ").append(toIndentedString(enterprise)).append("\n");
    sb.append("    installation: ").append(toIndentedString(installation)).append("\n");
    sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
    sb.append("    repository: ").append(toIndentedString(repository)).append("\n");
    sb.append("    sender: ").append(toIndentedString(sender)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
